### ISSUE TITLE
Where is the account being created?

### ISSUE THREAD

**Issue by paulkramme** [bitwarden/browser#10]

**Comment by kspearrin** [comment]
I am not sure I understand your question completely. The account is created on the server: https://github.com/bitwarden/core

**Comment by paulkramme** [comment]
My problem is trust. I'll give you all my passwords to all my accounts.
That would give you the opportunity to create massive damage to many users.
I'd like to know where this server is hosted, which encryption, etc...

**Comment by jjshoe** [comment]
@paulkramme where ever you put it, clearly.

**Comment by joshsleeper** [comment]
I too am curious about this.

@jjshoe that makes it sound like users host their own bitwarden server, which I'm pretty sure isn't the common case (although it should be doable since all the source code is here...)

I think what @paulkramme is asking for is totally reasonable.
If I register an account with bitwarden, I'd love to know:

- Where is that account information stored? (Azure? AWS?)
- How is that account information stored? (hashed, salted, PBKDF2 iterations or likewise?)
- Does the bitwarden core server stay up to date with security patches and such?

Not accusing you of doing anything wrong @kspearrin, just so you know.
It's more the fact that I currently trust LastPass based on their documentation and how they've handled issues in the past.
While bitwarden seems super nifty (and has plenty of potential to be better than LastPass if it gets an OSS dev following), account management and storage is rarely easy and people often do it wrong.

I'd say it's even worth a more technical writeup on https://help.bitwarden.com/

**Comment by paulkramme** [comment]
Thank you very much, this is what i meant. I agree, it would be totaly
awesome to selfhost it. My data - My responsibility - My control.

**Comment by jjshoe** [comment]
@joshsleeper I'm pretty sure it is the common case.

**Comment by kspearrin** [comment]
I will work on a help article about these items soon.

**Comment by kspearrin** [comment]
Added the articles to this issue: https://github.com/bitwarden/help/issues/2

**Comment by joshsleeper** [comment]
Awesome @kspearrin, thanks so much!
bitwarden seems like a really great tool, keep up the great work!

**Comment by kspearrin** [comment]
@joshsleeper @paulkramme These questions have now been answered and can be found here: https://help.bitwarden.com/security/
