### ISSUE TITLE
Auto-fill issue on epicgames.com

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#1029]
BW 1.41.0 on FF 69.0.2 64-bit

STR:

1. Go to: https://www.epicgames.com/id/login
2. Save a login for that site in BW (can use any data; it doesn't have to be real)
3. Clear all FF caches & cookies
4. Go to: https://www.epicgames.com/id/login
5. Use BW's drop-down menu within FF to autofill login credentials.
6. Notice username will not get auto-filled, but password will.

BTW, if repeat step 5, it will work, but this should not be necessary.

**Comment by wxMichael** [comment]
The username will sometimes auto-fill, but clicking anywhere on the page will clear the username field. 
Additionally, the Log In Now button to submit the form remains disabled until I manually type or paste something into the username field.
Repeating step 5 above never allows me to log in without manual inputting the username.

Bitwarden may need to trigger an event on the field instead of just changing the input value.

**Comment by setyb** [comment]
Just to keep this issue current and accurate: Issue present with Firefox 71.0 64-bit too.

**Comment by setyb** [comment]
To keep this issue current and accurate: Issue present with BW 1.42.2 on Firefox 72.0.2 64-bit.

**Comment by setyb** [comment]
To keep this issue current and accurate: Issue present with BW 1.43.4 on Firefox 74.0.1 64-bit.

**Comment by Wever1985** [comment]
While the issue is still present, I found a workaround seems to be **holding down** the hotkeys for auto-fill (Ctrl + Shift + L on Windows/Linux, Cmd + Shift + L on macOS) for a few seconds until the username also gets auto-filled.

It really seems to be more of an issue with the website rather than with Bitwarden.

**Comment by wxMichael** [comment]
Ideally, BitWarden should auto-fill in such a way that the website is not able to tell whether I manually input my credentials.

**Comment by paschott** [comment]
Still an issue w/ FF 84.  Agreed that it seems to be something w/ Epic interfering, though I haven't seen that cause an issue w/ LastPass.

**Comment by jaw3l** [comment]
Issue still remains with Chrome 87.0.4280.88 as well. 

> Still an issue w/ FF 84. Agreed that it seems to be something w/ Epic interfering, though I haven't seen that cause an issue w/ LastPass.

**Comment by setyb** [comment]
@eliykat

Hi Thomas,

I noticed you just assigned yourself to this issue.

To give you a little help, I just performed updated testing using BW 1.48.1 on FF 85.0.0 64-bit to see if the issue still exists.  Those are the latest release versions of both products.  The issue does still exist.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by setyb** [comment]
@eliykat 
I received this issue update notification last, so I replied to the notifications I received before I got this notification. LOL.

Just for completeness (definitely not trying to spam!), here is a copy from those issue reports:

I'm sorry, I ***don't use Google***, nor do I recommend any of their products to others.  In fact, Google-run host names as well as all known Google IP addresses are completely blocked here.  ***Life is better without Google™.***

I'm happy to continue to contribute via any non-Google and non-Facebook open-source product.
