### ISSUE TITLE
Is it possible to get a promt to enter my bitwarden password once I open my browser?

### ISSUE THREAD

**Issue by gelsas** [bitwarden/browser#1040]
Is it possible to get a promt to enter my bitwarden password once I open my browser?

A lot of times I find myself forgetting to login to bitwarden and then wondering why my password is not autofilled.

Is it possible to get a promt to enter the password, when opening the browser, so I dont forget to login when opening my browser?

**Comment by kspearrin** [comment]
As far as I know, this is not currently possible due to limitations in the web extensions API.

**Comment by gelsas** [comment]
Oh okay, thank you for the info.

I also have the desktop version of bitwarden installed. Is it possible to let the desktop app make a Push Notification (or something like that) when I open my browser? 

Or is it possible that I am automatically logged in in the browser extension if the desktop version is unlocked as well?
That would be perfect! 

Best,
gelsas

P.S.: Thank you for the great work with Bitwarden

**Comment by kspearrin** [comment]
Right now the desktop and browser extensions do not share authentication or locked state.

**Comment by yfdyh000** [comment]
I think this can be done by opening a tab or notification when start up.

It will be better, if the sessions across browser restarts, provide https://community.bitwarden.com/t/overlay-popup-interface/14 or others else.

**Comment by gelsas** [comment]
Would be awesome if something like that could be added as a feature

**Comment by nukefrenzy** [comment]
It would be great to just prompt for a password the first time the keyboard shortcut is pressed.  1Password works like this and it's good user experience.  The first time you hit the Ctrl+\ the master password prompt comes up.  Otherwise, it feels like Bitwarden is inactive until you click on the extension button, which is different from just about every other extension where they are working as soon as you open your browser.

**Comment by laurens94** [comment]
I agree with @nukefrenzy , it should show the password prompt the first time you use the keyboard shortcut, and after filling in your master password it should fill in the form on the webpage (because that's what you try to do with the shortcut). 

Coming from 1Password this was the first (and so far only) thing that felt off/broken.

**Comment by Wibbbs** [comment]
I would also be great if your vault is locked that when you use the ctrl+shift+L shortcut the addon opens up to ask for your password to unlock.

many times, my vault is locked then when I use the keyboard shortcut nothing happens, then I realize the vault is locked and I have to click to enter the password. Would be nice if that prompt came up automatically.

**Comment by pomarec** [comment]
Are you thinking about https://github.com/bitwarden/browser/issues/978 ?

**Comment by scheinercc** [comment]
Keeper prompts if the vault is locked and the user visits a website it stores a login for. Maybe that could be something to be considered?

**Comment by ngoonee** [comment]
> Keeper prompts if the vault is locked and the user visits a website it stores a login for. Maybe that could be something to be considered?

You know, the information for the website is stored in the vault. And if the password manager is aware which website has been stored inside even when the vault is locked, that means that information is no longer secure (or worse, the vault isn't actually locked).

That being said, information on 'what URIs I can server' could be stored outside the vault unencrypted, but that's definitely less secure.

**Comment by scheinercc** [comment]
> That being said, information on 'what URIs I can server' could be stored outside the vault unencrypted, but that's definitely less secure.

Yes, I was thinking of that, but thought I'd put the option out there for discussion.

**Comment by devurandom** [comment]
> Keeper prompts if the vault is locked and the user visits a website it stores a login for. Maybe that could be something to be considered?

Firefox solves this in a very simple but surprisingly effective way: It prompts for the "master password" once *any* tab requires a password (or a client certificate), independently of whether that password is stored or not.

**Comment by scheinercc** [comment]
> It prompts for the "master password" once any tab requires a password (or a client certificate)

I just tried it and it does seem to be the case. I tested two scenarios, one with a login saved for a page and one login page without saved login data

**no saved login**
1. I opened a site with a login form which I don't have anything stored in FF for
2. I closed FF (with restore session and MP enabled)
3. After reopening FF and the page loaded no MP prompt appeared

**with saved login**
1. I opened a site with a login form which I do have stored in FF
2. I closed FF (with restore session and MP enabled)
3. After reopening FF and the page loaded the MP prompt appeared

It also does prompt once the sync service kicks in or if I try to send tabs to other devices (though I think this might be also connected to sync), etc.

**Comment by djsmith85** [comment]
Unlock on save login #2094  and unlock on autofill #2132 will be included in next release.

**Comment by gelsas** [comment]
Hey, just wanted to asked if you know when this next release will be live?

**Comment by eliykat** [comment]
@gelsas we will be releasing client + server updates over the course of next week.

**Comment by eliykat** [comment]
I'm closing this because @djsmith85 has [added some features](https://github.com/bitwarden/browser/issues/1040#issuecomment-957401551) that address this basic use case and most of the requests in this thread. We now track feature requests on our Community Forums, so if anyone has any outstanding requests then please create a thread there. (more info below) Thanks!

---

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.
