### ISSUE TITLE
feature request : Thunderbird

### ISSUE THREAD

**Issue by bijang** [bitwarden/browser#1045]
First many thanks to everyone for their thundering work on this, so very grateful!
This is not an issue of a bug, but more an awkwardly placed feature request, for a thunderbird  extension; though I would not want ot divert anyone's attention from the current work, now thunderbird has migrated its extension infrastructure; its future is looking brigthter, (with many bug fixes, lightening intergration, future encryption integration and plans for etesync extension) but incomplete without a decent password manager

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by beedell-roke** [comment]
@bijang, [`community.bitwarden.com/t/622`](https://community.bitwarden.com/t/support-for-mozilla-thunderbird-email-client/622?u=rokejulianlockhart) requests this (but is unfortunately closed).
