### ISSUE TITLE
Menu dialog in Firefox misaligned

### ISSUE THREAD

**Issue by pimeys** [bitwarden/browser#1046]
- OS: Arch Linux, kernel 5.3.7-arch1-1-ARCH
- Browser: firefox-nightly-71.0a1.20191021-1-x86_64
- Compositor: Wayland/Sway

When clicking the Bitwarden menu open, the menu opens several centimeters under the button, and all mouse clicks are registered from the position the buttons should be, but not where they are rendered. This behavior changed due to a nightly update last week and might be something Firefox broke.

My other extensions, such as Ublock Origin work just fine though.

![signal-attachment-2019-10-22-132636](https://user-images.githubusercontent.com/34967/67281638-6a3fae80-f4bf-11e9-92ec-6760f69e0c1c.jpeg)

The screenshot is done with my phone due to the dialog disappearing when I try to open other windows, such as the screenshot tool.

**Comment by kspearrin** [comment]
This seems like a firefox problem. We have no control over where the popup opens.

**Comment by pimeys** [comment]
Might be a related issue https://bugzilla.mozilla.org/show_bug.cgi?id=1529446

**Comment by dblueman** [comment]
The issue I reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1529446 also affects tooltips. If you also experience tooltips and/or menus opening in the wrong area (and thus hard to control) after toggling HiDpi scaling, please mention it in the report, as the bug is sadly UNCONFIRMED meaning won't get any attention.

Thanks chaps!
