### ISSUE TITLE
bitwarden doesn´t recognize Login on the following pages 

### ISSUE THREAD

**Issue by bjoernhohe** [bitwarden/browser#1074]
Bitwarden doesn´t recognize the Login on the following site:

- [ ] https://www.buhl.de/mein-buhlkonto/
- [x] https://www.dji.com/de
- [x] https://community.tomorrow.one/
- [x] https://www.ebay.de/
- [x] https://www.ea.com/

tried on osx mojave and windows 10, brave (1.0.1.)with the bitwarden extension

**Comment by kspearrin** [comment]
Every website I tested worked except the first one. See notes below.


https://www.buhl.de/mein-buhlkonto/ - Doesn't work because this site requires you to type in an email first to validate and enable the password field
https://www.dji.com/de - Works for me
https://community.tomorrow.one/ - Works for me
https://www.ebay.de/ - Works for me
https://www.ea.com/ - Works for me

**Comment by bjoernhohe** [comment]
which browser do you have?

**Comment by kspearrin** [comment]
Brave on windows 10

```
Brave is up to date
Version 1.0.1 Chromium: 78.0.3904.108 (Official Build) (64-bit)
```

**Comment by bjoernhohe** [comment]
really? ok will try again

**Comment by bjoernhohe** [comment]
nope won´t work

**Comment by bjoernhohe** [comment]
could some settings in brave prevent this? i tried it with Google Chrome and it won´t work. Could eventually uBlock interfere?

**Comment by PinkDev1** [comment]
https://www.buhl.de/mein-buhlkonto/ Doesn't work because this site requires you to type in an email first to validate and enable the password field.

Simple Work-around for users: Just press the hotkey twice. The first auto-fill will fill in the email and enable the password field. The second auto-fill will auto-fill the password field and you'll be able to log in with no further problems.

Boom, problem solved. @kspearrin, I suggest you close this issue.

**Comment by sohannin** [comment]
Also account.live.com seems to go by without noticing userid/password submit. They are on separate pages which may cause trouble.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
