### ISSUE TITLE
autofill not working on ThingSpeak (IOT)

### ISSUE THREAD

**Issue by insipidlight** [bitwarden/browser#1081]
This is a two step login (email --> email + password), and autofill is not working for the first step.
I expected it to work like it does on [Backblaze](https://www.backblaze.com/) where you only have to fill once.

[https://thingspeak.com/login](https://thingspeak.com/login)

`<input type="email" class="form-control maxlength_exempt" name="email" id="sign_in_email" placeholder="someone@example.com" maxlength="255" autocomplete="email">`

BW does recognize this and adds `data-com.bitwarden.browser.user-edited="yes"` 

`<input type="password" name="password" value="" class="form-control " id="password" aria-describedby="error" data-com.bitwarden.browser.user-edited="yes">`

The second page is filled correctly even though the email box is disabled.

Sorry I'm not very knowledgeable about web forms, I hope the code is helpful!

**Comment by kspearrin** [comment]
This fails to autofill because there is no accompanying password field on this form. With the Backblaze example you mentioned, there is a hidden password field that helps us identify the proper username field. You can target this email field on ThingSpeak for autofill by using custom fields.

See https://help.bitwarden.com/article/custom-fields/
