### ISSUE TITLE
Make Bitwarden reachable only from one IP

### ISSUE THREAD

**Issue by sb2050** [bitwarden/browser#1085]
Good day,
How is it possible to make Bitwarden reachable only from one IP.
I’ve entered IP tabeles, but these are ignored.

```
sudo iptables -A INPUT -p tcp --dport 80 -j DROP
sudo iptables -A INPUT -p udp --dport 80 -j DROP
sudo iptables -A INPUT -p tcp --dport 443 -j DROP
sudo iptables -A INPUT -p udp --dport 443 -j DROP
sudo iptables -A INPUT -p tcp -s 0.0.0.0 --dport 80 -j ACCEPT
sudo iptables -A INPUT -p udp -s 0.0.0.0 --dport 80 -j ACCEPT
sudo iptables -A INPUT -p tcp -s 0.0.0.0 --dport 443 -j ACCEPT
sudo iptables -A INPUT -p udp -s 0.0.0.0 --dport 443 -j ACCEPT
```

0.0.0.0 is a place holder.

**Comment by PinkDev1** [comment]
So, basically you want to make Bitwarden accessible from only from a certain IP within a LAN?
If so, I suggest you look at [this Microsoft Forums post](https://social.technet.microsoft.com/Forums/en-US/8cc76aa6-ea4c-429e-9535-496804f3bf92/is-it-possible-to-get-a-windows-dns-server-to-respond-to-certain-clients-with-one-response-and). However, I don't know why you'd want to do this. 

Also, this issue is unrelated to Bitwarden, and are unlikely to get a response to this problematic here. I suggest you to close this issue, and repost to [Serverfault](https://serverfault.com) or any other Networking related forum.
