### ISSUE TITLE
Add Breadcrumbs

### ISSUE THREAD

**Issue by repomaa** [bitwarden/browser#1133]
I don't consider this a feature request but my apologies if you do:

When i select an item from the vault i need a texual representation of the path it's in. Otherwise with a structure like this...

```
|
- Banking
        |
        - Bank Foo
        |        |
        |        - Credit Card
        - Bank Bar
                 |
                 - Credit Card
```

...there's no way to distinguish between the two Items.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
