### ISSUE TITLE
Autofill basic auth prompts

### ISSUE THREAD

**Issue by dralley** [bitwarden/browser#116]
For instance, some routers do this, as well as ADP iPay which is my payroll site.

Lastpass can handle this but it doesn't appear that Bit Warden can.

**Comment by kspearrin** [comment]
Are you referring to "basic authentication" windows that popup in the browser like this? https://i.stack.imgur.com/QnUZW.png

**Comment by dralley** [comment]
Yes, exactly that

**Comment by jjdelc** [comment]
I was just filing an issue about this same thing. For now I have to rely on the browser's password manager to remember this (using Firefox) and Bitwarden for websites, but now I have two password managers.

**Comment by kspearrin** [comment]
I am looking into this more now but an running into a few problems.

1. I am not able to get this working with LastPass.
  - I have the browser extension installed with a site added for "https://httpbin.org/".
  - When I visit https://httpbin.org/basic-auth/user/passwd and get a basic auth prompt I am not able to autofill from LastPass. It just does nothing when I autofill??

2. I am exploring the [browser APIs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onAuthRequired) that make this possible and see a few issues:
  - This works by intercepting web requests as that come in to the browser and detecting when it is a auth request. I can then automatically provide the credentials to the request. It appears that there is no way to provide the credentials _after_ the prompt appears. Because of this I would have to figure out what credentials to use for you. What if the user has multiple logins in their vault for this site? How would I know which to use?

**Comment by jjdelc** [comment]
I don't know if this is possible with web extensions, but last pass would add an extra select box to the auth prompt where you could pick the credentials to use:

![screenshot_2017-06-09 134506](https://user-images.githubusercontent.com/59393/26989841-371d98c2-4d1a-11e7-8182-6901d76081b5.png)

**Comment by kspearrin** [comment]
@jjdelc  Hmm, yea. That definitely isn't possible with web extensions. Is that screenshot from Chrome or Firefox? You would probably need some kind of native app installed to override that kind of stuff.

**Comment by jjdelc** [comment]
That's Firefox. 

Maybe if the request can be intercepted a previous UI can be shown to ask which credential to use and then fill up using that one. It would be a 2 step process but at least you get the option to choose. If there's only one there would be no need.

On this one screenshot it is showing me 4 options, but really only 1 is fitting. I have 3 subdomains on my personal domain:

* sub1.domain
* blog1.domain
* blog2.comain

For sub1.domain I only have a http auth password. For blog1.domain I have httpauth for when I access /admin and also the engine admin credentials itself (so 2 entriesm different kinds) and for blog2.domain only admin credentials.

Really, only one of them is necessary ever here, matching by subdomain and path and type of auth the other 3 options that I get would be ruled out and reduce the number of times a picker needs to be shown. Looks like lastpass is not making those distinctions so it shows me all (and remembers my last choice)

**Comment by piejanssens** [comment]
Detect request to matching URL from vault and for 1 matching credential automatically insert username/password in URL, otherwise show popup. 
Change URL to http(s)://username:password@hostname/path

**Comment by jjdelc** [comment]
I don't think you want to make a GET request with your credentials in the URL, that will get recorded in some access.log file.

**Comment by SylwesterZarebski** [comment]
I don't think it is recorded on server side, because form of username:password@hostname is just shortcut to fill desired request headers - it is handled by browser, not server. Or it is when used by user, don't know when address is given by addon's code.

On the other hand, this form could be seen by JS on browser side and abused.

**Comment by mhammond** [comment]
As @kspearrin mentioned, the onAuthRequired API exists and would be able the handle the case of exactly 1 set of credentials being used without user interaction - it's the "user interaction" part that I can't see a solution to - even in the case of exactly 1 set of credentials, you almost certainly still want user interaction.

It *appears* that it may be possible to open a window where the user can select a set of credentials from, but I can't see a way to make this either modal or "always on top" - so the user could accidentally send that window to the back and get confused. Nor can I see a way to open the usual panel in this case.

I did find another password manager on github and they took the approach of injecting a html "dialog" into the page being requested, but this seems both risky and destined to fail in edge cases.

The lastpass examples are all from their "legacy" addon, where customizing the builtin auth dialog is possible. I know they are working on a webextension-only version of the addon, so it will be interesting to see how they do things there - and if that turns out to be "nothing", then I guess we could agitate for a new webext API for Firefox, but that's still only 1 browser.

**Comment by jjdelc** [comment]
Is there a bugzilla ticket? So Firefox devs can be aware of the limitation to begin with.

**Comment by fwosar** [comment]
Any update on this? :)

**Comment by pannal** [comment]
I'm actively using LastPass with the binary extension enabled, to autofill basic auth requests.

With the recent price-doubling I've come across Bitwarden, which seems really interesting to me. The Open Source part is key. Supporting basic auth is a must, for me, unfortunately.

**Comment by viertaxa** [comment]
I also am migrating to Bitwarden from LastPass. This functionality is critical to me.

**Comment by kspearrin** [comment]
all: There isn't a good solution for this at the moment.

We use the web extensions API for bitwarden. Web extensions do not provide a good API to handle basic auth at the moment. Unless something changes with the web extension APIs I don't see how we can proceed with anything at this time.

As mentioned above, LastPass is using an old, deprecated API that is no longer going to be available in a few months. It will be interesting to see what they came up with to get around this problem.

**Comment by jjdelc** [comment]
> It will be interesting to see what they came up with to get around this problem.

Are they aware of the problem? Maybe file a ticket in bugzilla. I know Firefox is also ramping up their built in password manager so they could add APIs for this.

**Comment by fwosar** [comment]
I don't think there are a lot of use cases for having multiple different HTTP AUTH credentials for the same domain. So just implementing the case that if only one set of credentials exist, use those would help tremendously. If there are security concerns, you can always add a flag per credentials to mark them as HTTP AUTH credentials that a user can set to avoid situations where a rogue AUTH request on a website is able to steal your credentials.

**Comment by pannal** [comment]
@fwosar how do you come to that conclusion? I've got several http auth enabled domains with different apps on different paths with different logins.

**Comment by fwosar** [comment]
Do you have multiple credentials for the same URL though that you need to switch between? Even if you do, I would argue that not a lot of other people do. I too have dozens of HTTP AUTH credentials, but they are all for different servers/URLs.

**Comment by viertaxa** [comment]
That situation is not as uncommon as it may seem. I have several HTTP auth logins for the same domain (admin and regular login) and several different logins for different subdomains (products that do not support AD login capability).

**Comment by fwosar** [comment]
And still, you would prefer it to work at least for the cases where you only have one instead of not at all.

**Comment by pannal** [comment]
That's true.

**Comment by aquatix** [comment]
Looks related to this issue from another project that I found, which seems to have a fix: https://github.com/nextcloud/passman-webextension/issues/10

**Comment by kspearrin** [comment]
@aquatix The solution there seems to be along the lines of what we have pointed out here. It will only handle a single credential and provides no method of selection if there is more than 1.

**Comment by fwosar** [comment]
Which is still better than doing nothing at all and just wait.

**Comment by aquatix** [comment]
@kspearrin @fwosar agreed with both of you. Of course, @kspearrin it would be great to have it fixed properly, however, I have those popups several times on a daily base, so having only one option already would help me greatly.

**Comment by synotna** [comment]
Would this be possible?
* onAuthRequired block asynchronously  ( https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onAuthRequired )
* notification with call to action ( https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Notifications )
* call to action open's extension pop-up with credential choice
* choose credential
* continue with credentials

**Comment by kspearrin** [comment]
@synotna That's more or less the steps we'd have to take to achieve this except step no. 3 is not possible since a user has to physically click the popup to make it open. We'd need some alternate UI.

**Comment by mhammond** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1341126 is landing on Firefox as we speak, which adds browserAction.openPopup and pageAction.openPopup - however, currently they can only be used while directly handling user input which probably isn't going to help. There does seem to be agreement that we should also allow this while handling onAuthRequired, so I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1391093.

**Comment by kspearrin** [comment]
Thanks for that @mhammond though users should be aware that this would only be possible to do with Firefox since this would not be an cross-platform API.

**Comment by bstaruk** [comment]
+1

I will likely be abandoning bitwarden due to this missing feature.

**Comment by bstaruk** [comment]
I will likely be switching back to Lastpass due to this missing feature.

A password manager should be able to fill *all* password prompts.

Lastpass does it, so it's absolutely not impossible.

**Comment by bstaruk** [comment]
I will likely be switching back to LastPass due to this missing feature.

A password manager should be able to fill *all* password prompts.

LastPass does it, so it's absolutely not impossible.

**Comment by jyavenard** [comment]
> LastPass does it, so it's absolutely not impossible.

LastPass doesn't use web extension and no longer works with Firefox 57... So your choices very soon will be very limited.

**Comment by bstaruk** [comment]
LastPass offers a binary installer which adds support for these prompts on Chrome.

**Comment by SylwesterZarebski** [comment]
For me, LastPass 4.0 have lost basic auth in Fx 52 and newer (and since then no combination worked), then i've switched to Bitwarden.

**Comment by synotna** [comment]
For what it's worth LastPass 4.1.62 with binary is working fine for me in Firefox 55 & 56, and I'm also curious what they have planned for 57 :)

**Comment by synotna** [comment]
"except step no. 3 is not possible since a user has to physically click the popup to make it open"

Oh, the call to action feature of notifications is not enough to open the extension pop-up? Damn

Then what about onAuthRequired go to a credential selector page view in the content area? i.e. skip using the browser dialog completely

**Comment by kspearrin** [comment]
all:

I have created a solution for this in the next release using the web extension APIs that are available.

1. If you encounter a basic auth prompt and there is 1 login in your vault matching the given website, bitwarden will log you in automatically. You will never see the login prompt.
2. If bitwarden tries to perform the login from step 1 and the login credentials fail, you see the login prompt.
3. If there is no login in your vault for the given website, you see the login prompt.
4. Here's the unfortunate one for now: If there is more than 1 login in your vault for the given website, you see the login prompt. I can't know which login you want to use in this scenario. If we made the decision for you (ex. choosing the last used login), you would never be able to log in using any of the others since logging in happens automatically with these APIs. We cannot auto-login for you in this situation without the side effect of blocking you from using and others stored for the website.

It's not the best solution, but it's the only one I can see available at the moment.

related commit: https://github.com/bitwarden/browser/commit/41c32f3874f9f0cb2c10bc464a75897a8a655f75

**Comment by pannal** [comment]
Great news!

For the multiple login problem: it would help if either there was a switch for the matching strictness of a domain (like lastpass has). That way one could have 10 logins for 10 subdomains but only the one for the current subdomain gets picked if that matching strictness is set to a certain level.

Also is the favourite flag honored?

**Comment by kspearrin** [comment]
This is now live.

**Comment by eltismerino** [comment]
Hmm. With multiple logins for a domain this doesn't do anything, not even take the one with the "favourite"-flag set.

That was exactly what we talked about earlier in this ticket - I have multiple logins per domain (but different subdomains). Judging by the code, the basic auth functionality doesn't do anything when it detects more than one login per domain, why is that?

And why does it treat logins for different subdomains the same? That doesn't make any sense to me.

**Comment by pannal** [comment]
Hmm. With multiple logins for a domain this doesn't do anything, not even take the one with the "favourite"-flag set.

Judging by the code, the basic auth functionality doesn't do anything when it detects more than one login per (sub-!) domain, why is that?

And why does it treat logins for different subdomains as the same? That doesn't make any sense to me.

**Comment by kspearrin** [comment]
> 4. Here's the unfortunate one for now: If there is more than 1 login in your vault for the given website, you see the login prompt. I can't know which login you want to use in this scenario. If we made the decision for you (ex. choosing the last used login), you would never be able to log in using any of the others since logging in happens automatically with these APIs. We cannot auto-login for you in this situation without the side effect of blocking you from using and others stored for the website.

**Comment by pannal** [comment]
I understand that. But why does it treat `test1.domain.com` the same as `test2.domain.com` and skips auto-filling the basic auth for `test1.domain.com` altogether? That distinction doesn't make any sense to me.

**Comment by SylwesterZarebski** [comment]
Real problem is with _**more than 1 login in your vault**_.
In fact i have multiple websites under same domain and have exactly one login for every website, but Bitwarden sees them as whole, which is a problem - see issue #77.

**Comment by kspearrin** [comment]
@pannal  See #77

**Comment by pannal** [comment]
@kspearrin OK, thanks. I still don't understand why that's the default behaviour, though, but that's out of the scope for this ticket.

**Comment by pannal** [comment]
For multiple logins per (sub-) domain - could we have a flag that marks one login as the one to use for basic auth? Perhaps the existing favourite-flag?

**Comment by kspearrin** [comment]
@pannal see https://github.com/bitwarden/browser/issues/77 which will be able to take care of that

**Comment by pannal** [comment]
Hmm, I'm still having problems with this functionality.

I understand that it's limited to domains with only one login in BW, but even then it does nothing for me. I have a login for domainX.com, BW also shows me the little `1` besides its icon when I visit that page. It doesn't auto-fill the basic auth, though.

**Comment by kspearrin** [comment]
@pannal I just tested this in Chrome and Firefox on our local router admin page here and it worked properly. Can you give any information on the website this is a problem on?

**Comment by pannal** [comment]
@kspearrin turns out I wasn't using it correctly. The password stored was wrong, but there was no indication of BW even trying to use the login upon basic authentication.

**Comment by kspearrin** [comment]
Anyone able to check in and see what LastPass is doing in their extension now with FF 57?

**Comment by jjdelc** [comment]
I just installed it to check on nightly, and it looks like they're dropping trying to fill out the auth forms altogether. I am adding credentials but still seeing the prompt empty, not detecting it.

**Comment by Attoy** [comment]
@kspearrin LastPass can't fill HTTP Authentication, they said that this function was related to the communication between the add-on and the binary component. The new add-on (WebExtension) due to the API limitations cannot communicate anymore with the binary component hence no auto-fill HTTP Authentication (yet?).

**Comment by hluposti** [comment]
Hi, I understand the current situation and I'm okay with Bitwarden only handling a single login for a domain, however, would it be possible to differentiate between subdomains? At work we are running various services at our company domains, so you get domains like webconsole.domain.com, documentserver.domain.com, testingtool.domain.com and one of those uses basic auth prompts. Defining subdomains in the app stopped the prompts autofilling.

**Comment by kspearrin** [comment]
@hluposti That is being tracked at #77

**Comment by hluposti** [comment]
Oh, sorry about that. I will search next time.

**Comment by synotna** [comment]
Not sure myself :) Looking at the web extension docs, my thought process was instead of the browser's http basic auth dialog use a https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Extension_pages

* if https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onAuthRequired
* then instead of displaying the http basic auth dialog or sending "the one" credential that is available like now, display a https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Extension_pages that lets the user choose the credentials they wish to use or fill in new ones (iirc this is what lastpass uses for their log in page? I switched to bitwarden permanently a few months ago so my memory is rusty!)
* use the chosen credentials for the request
* if it fails, display that page again with appropriate error

**Comment by LeoTPSC** [comment]
This feature still does not seem to work for me. For example, when I go to my router login page, it does not fill in the credentials automatically or on request. I'm using Chrome.

**Comment by Crocmagnon** [comment]
Does Bitwarden detect more than one login entry for your router ? If so, that's normal (see this message https://github.com/bitwarden/browser/issues/116#issuecomment-327991012).

**Comment by LeoTPSC** [comment]
Yes, that is exactly what happens, changed the website detection parameters and it works fine now. Thanks!

**Comment by DirrtyDean** [comment]
Hey Guys,

first of all thanks for the cool Program.

I used KeePass before (and still for BasicAuth) with the Plugin Kee for Firefox https://www.kee.pm/.

They solved it with a Window, which appeas instead of the Prompt, where I can choose the needed Credential.

Maybe this can help.

Regards
Dean

**Comment by gbdlin** [comment]
Yes, it is actually possible to implement using new window - browsers will ensure to display this window on top.

**Comment by Aspire1Inspire2** [comment]
Why is this issue closed? 
I reportedly still cannot fill in pop-up password window from Firefox 67 on June 10, 2019.
Is this issue already resolved?

**Comment by SylwesterZarebski** [comment]
Did You fulfil requirements of having exactly ONE credential for site with basic auth?

**Comment by pandiloko** [comment]
I would like to see support for basic auth and multiple credentials. I really like Bitwarden and would like to switch but I do extensive use of basic auth and at this moment Keepassxc is doing a better job at that.

I think they hold the GET request until you click on the icon and select one of the stored credentials. That way you don't even see the pop-up and can have multiple creds. Of course if you only have one you are automatically logged in. Does it seem a feasible solution to implement for you? 

Anyway keep up the good job!

**Comment by Crocmagnon** [comment]
If you want to hold the request you need to have a flag telling that some perticular request will ask for basic auth, which doesn't seem very obvious to implement.

**Comment by pandiloko** [comment]
You got me there. I don't _really_ know how do they exactly do it. I kind of explained how it feels like. If I open a new tab with the developer tools enabled and try top open a protected site, the GET request just hangs up there without any data transfer going on until I click on the icon. Perhaps they do some kind of internal `wget --spider` to test for a 401 server response. A look at the code should clarify this but I mean: it should be doable.

**Comment by synotna** [comment]
Hey @kspearrin should we open a separate issue to support http basic auth choosing from multiple credentials?

I have a basic proof of concept working with https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Extension_pages

If you would not implement yourself, would you accept an MR for it?

What would your preferred UX be? 

My idea would a sort of custom bitwarden styled http basic auth page with the option to fill in username/password yourself, or choose from the credentials that are found

**Comment by kspearrin** [comment]
Sure, we can give that a try. For now, just make the UX very basic with links to usersnames to click.

**Comment by luckman212** [comment]
Hey @synotna any luck on this?

**Comment by synotna** [comment]
Over the Xmas break I managed to get an extremely rudimentary proof of concept working - an empty webextension that implemented my idea: onAuthRequired opened a tab or popup with a list of buttons that represented creds, hitting button sent the creds to the waiting tab

I followed https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onAuthRequired "Provide credentials asynchronously"

I tried to port it to bitwarden but as I have no idea what I'm doing with frontend stack (angular etc) I didn't get very far before I ran out of time... 

Unfortunately the device I had all of this on was wiped last week 😣

**Comment by Pirateguybrush** [comment]
Any chance of an update on this feature please?

**Comment by pandiloko** [comment]
So I have some sites which need Basic Auth with multiple users. Mainly for development for testing projects or managing some web applications. Not having support in Bitwarden was a deal-breaker for me but I have finally found a workaround. 

Since in my case there aren't sooo many sites and users I associated manually each user login to a specific URL with exact match, e.g.:

- example.com/admin.php is associated with admin / adminpass
- example.com/profile.php is associated with user1 / user1pass
- etc.

And each URL is saved in the Bookmarks Toolbar with the username so depending on which bookmark link I use bitwarden picks one user or the other. 

I use Firefox Multi-Account Containers extension to login with multiple users in different colored tabs at the same time (as I always have done with keepassxc) and Bitwarden is able to log me in with multiple users with this little trick. So I have been able to completely migrate everything to Bitwarden and don't miss anything. 

I hope this helps someone.

**Comment by rodfersou** [comment]
you should have a flag in the password list to indicate which one should be used for basic auth...

**Comment by rodfersou** [comment]
@pandiloko your workaround worked for me! thanks for the suggestion!

**Comment by bpsib** [comment]
@pandiloko Can you explain your workaround clearer? I can't understand it.

**Comment by pandiloko** [comment]
@bpsib glad you already figured it out. Yes, my workaround is for multiple users in the same basic-auth protected application or web site. Although this is valid for any kind of authentication. 

Just in case: the "trick" is to add each user and set the URL match to "exact" with a specific URL. It doesn't matter which one as long as each user has a unique URL. You save then those URLs in your bookmarks (indicating the user so it is easier to identify). For example for wordpress site you could use:

 - example.com/wp-admin/edit.php - editor
 - example.com/wp-admin/options-general.php - admin
 - example.com/ - commenter
 
So if you want to change wordpress settings you use the second link and Bitwarden will match the URL and log you in with admin. If you want to comment with and unprivileged user, you select the last link and will be logged in as commenter. And so on.

**Comment by ZeroMaki** [comment]
kee for keepass works very good for basic auth prompts even supports multiple choice, maybe check how they did it.
