### ISSUE TITLE
match organizationId to their names

### ISSUE THREAD

**Issue by lukasIO** [bitwarden/browser#1189]
Hi,

as I am dealing with three organizations within bitwarden (plus my private non-organization-entries) I wanted to experiment with (and ultimately submit a PR for) showing the current-tab entries grouped by organization name.
Everything seems to work so far, but if I use the `getOrganization(id)` method of the apiService for an organization that is hosted on a different server the apiService returns a 404 for that organization. 
How can I work around that ?

**Comment by kspearrin** [comment]
You can't access organizations from two different servers in the same session.

**Comment by lukasIO** [comment]
thanks for the answer @kspearrin - is there another way to get the name of the organization from the organizationId ?

**Comment by kspearrin** [comment]
`userService.getOrganization(id)` returned an organization object with it;s name

**Comment by lukasIO** [comment]
thanks, will give that a try!

**Comment by djsmith85** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) or [Github Contributions](https://community.bitwarden.com/c/github-contributions)

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
