### ISSUE TITLE
Cannot export organization from owner account via browser extension

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#1197]
Exporting works as expected from the browser extension, except it doesn't export data from any organizations that you own.

I wonder how many people think they are backing up all their data using the export function, but actually are not.

Please allow backing up data from any organizations that you own from within the browser extension.

I consider this more of a bug than a feature request because I think it's what the user expects to happen.

**Comment by turowicz** [comment]
👍🏻

**Comment by Hinton** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by Hinton** [comment]
The organizations are a separate entity from your vault, but I believe we can be more explicit about the exports being for your personal vault. I've added an internal ticket to improve the UX for this.
