### ISSUE TITLE
Suggesting auto fill

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [bitwarden/browser#1226]
Is there anyway to suggest auto fill forms when Bitwarden detect matched login or when focus in input?

**Comment by 3zero2** [comment]
This would be nice to have yes. Similar to what Safari does when it finds a matching credentials in its list.

**Comment by emmgfx** [comment]
If I understand correctly... there is already an option for that.

First option inside Settings > Options.

**Comment by AmirHosseinKarimi** [comment]
I have not used this option yet, but this will offer to fill the form by selecting a credential? Or just fill the form when page loaded and form detected?

**Comment by D3S0X** [comment]
It would be very nice if we could have a implementation similar to the one in KeePassXC's browser extension where you focus the input and it shows a drop-down list with the entries that match and what you click on them it fills the form

**Comment by AmirHosseinKarimi** [comment]
@D3S0X Yea its nice, Bitwarden for Android have this feature by Android auto fill API

**Comment by clayadams5226** [comment]
@AmirHosseinKarimi I'm not sure I understand this request. Are you saying you can't get Auto-fill to work on your device? 

If so, We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
