### ISSUE TITLE
"Copy verification code" context menu option doesn't paste verification code

### ISSUE THREAD

**Issue by ghost** [bitwarden/browser#1253]
"Copy verification code" context menu option doesn't paste verification code.
Tested with latest Bitwarden on latest Google Chrome.

**Comment by patchbank** [comment]
As the button states, it only copies the code. You then have to paste it by yourself.

I guess this is due to the fact, that the code gets automatically copied, when you autofill credentials on a website and that it gets mostly copied by hand, because the user currently isn't on the specific website and needs it otherwise (eg. on a different application).

Of course, an autofill feature for the code would be pretty neat.
