### ISSUE TITLE
Vivaldi - Autofill on page load always active. 

### ISSUE THREAD

**Issue by Kadragon604** [bitwarden/browser#1268]
the option "autofill on page load" is always active despite the option being disabled. This is happening for all stored websites.

Vivaldi | 3.0.1874.38 (Stable channel) (64-bit)
Revision | ca1a7297a62038cd7ef1a841248d749a0346cc41
OS | Windows 10 OS Version 1909 (Build 18363.836)
JavaScript | V8 8.1.307.32
Flash | 32.0.0.363
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.142 Safari/537.36

**Comment by kspearrin** [comment]
I cannot reproduce.

```
Vivaldi | 3.0.1874.38 (Stable channel) (64-bit)
Revision | ca1a7297a62038cd7ef1a841248d749a0346cc41
OS | Windows 10 OS Version 1903 (Build 18362.836)
JavaScript | V8 8.1.307.32
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.142 Safari/537.36
```

**Comment by kaleb604** [comment]
> I cannot reproduce.
> 
> ```
> Vivaldi | 3.0.1874.38 (Stable channel) (64-bit)
> Revision | ca1a7297a62038cd7ef1a841248d749a0346cc41
> OS | Windows 10 OS Version 1903 (Build 18362.836)
> JavaScript | V8 8.1.307.32
> Flash | (Disabled)
> User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.142 Safari/537.36
> ```

After looking into it further. (I'm in the process of switching password managers so I have more passwords to troubleshoot with), it only auto fills with devices on the LAN, such as my router, NAS, and printers.  All of which have a local IP of 10.0.0.x. It does not auto-fill on other websites.

**Comment by kspearrin** [comment]
Are you expecting it to autofill on page load? If so, enable that under Settings > Options.

**Comment by kaleb604** [comment]
> Are you expecting it to autofill on page load? If so, enable that under Settings > Opt

No I am not. I currently am only getting the behavior with my router. I believe it may be due to how it's log in works. When you access the web portal, instead of having a text box in the webportal to enter the login credentials, it sends a 'security popup'. Attached is a video of the behavior and what I mean. I was also able to replicate this on opera, and edge. Only for this password, I suspect, due to how it handles its log in. 


[bitWarden.zip](https://github.com/bitwarden/browser/files/4721301/bitWarden.zip)

**Comment by martywd** [comment]
> I currently am only getting the behavior with my router. I believe it may be due to how it's log in works. When you access the web portal, **instead of having a text box in the webportal** to enter the login credentials, **it sends a 'security popup**'.

Correct.  This behavior only happens when say you are opening a webpage which is configured with password protection dircetly within the webserver, for example configured in apache's .htaccess file.  Also I've seen this in rss-bridge which also throws a popup window for authentication when optionally configured to require authentication.

When I first noticed this I thought it was a bug.  But on further reflection, I realized that when the authentication window appears, all other browser functionality like accessing the bitwarden browser extension is blocked which at that point prevents the user from accessing their username/password credentials to proceed passed the webpage's challenge.  At that point, if not for the autofill functionality, the users only option would be to cancel the authentication window if the needed credentials were not readily available elsewhere.  Thus, personally, I prefer this bitwarden extension approach of automagic autofill in this edge case.

FWIW.
.

**Comment by Kadragon604** [comment]
> > I currently am only getting the behavior with my router. I believe it may be due to how it's log in works. When you access the web portal, **instead of having a text box in the webportal** to enter the login credentials, **it sends a 'security popup**'.
> 
> Correct.  This behavior only happens when say you are opening a webpage which is configured with password protection directly within the webserver, for example configured in apache's .htaccess file.  Also I've seen this in rss-bridge which also throws a popup window for authentication when optionally configured to require authentication.
> 
> When I first noticed this I thought it was a bug.  But on further reflection, I realized that when the authentication window appears, all other browser functionality like accessing the bitwarden browser extension is blocked which at that point prevents the user from accessing their username/password credentials to proceed passed the webpage's challenge.  At that point, if not for the autofill functionality, the users only option would be to cancel the authentication window if the needed credentials were not readily available elsewhere.  Thus, personally, I prefer this bitwarden extension approach of automagic autofill in this edge case.
> 
> FWIW.
> .
>  
> 

Yeah, I do see a benefit in this, and it's less of a bug. However I do feel like there are use cases for not having this behavior active. I guess best course of action would be a feature request for adding a toggle for this behavior.
