### ISSUE TITLE
Logout (instead of PIN lock) after system suspend/resume in Chromium Edge

### ISSUE THREAD

**Issue by cthu1hoo** [bitwarden/browser#1274]
My settings are - Vault Timeout on System Lock; Unlock with PIN.

Instead of locking, after suspend/resume, I'm completely logged out, have to login again with master password and enable PIN unlock.

If I close and restart Edge without suspending, vault locks as expected and I can unlock it with PIN. So it's related to suspend specifically, somehow. Chrome works properly in all cases.

I'm using a self-hosted bitwarden instance but I don't think it's relevant in this case.

Latest versions of everything (Windows 10 2004, Edge 83 stable), Bitwarden addon installed from Microsoft store (1.44.1).

I think this has started after a recent addon update which changed icon color to a deeper blue but I'm not sure about this.

**Comment by kspearrin** [comment]
This was fixed in 1.44.2.

**Comment by razorness** [comment]
How long does it take to get pushed to Microsoft Store? There is still v1.44.1 while Chrome Web store already has v1.44.2 since 4/28.

- https://microsoftedge.microsoft.com/addons/detail/jbkfoedolllekgbhcbcoahefnbanhhlh
- https://chrome.google.com/webstore/detail/bitwarden-free-password-m/nngceckbapebfimnlniiiahkandclblb?hl=de
