### ISSUE TITLE
Please offer the old color theme as an option

### ISSUE THREAD

**Issue by CodingMarkus** [bitwarden/browser#1280]
The new dark blue color is hurting my eyes. No seriously, it's almost painful to watch it on all my monitors (and I have four different monitors and one notebook display and this is not a nice color on any of them). This is a very aggressive dark blue which I've not seen in use anywhere on my desktop before.

Unfortunately there is no alternative light color theme available, the only two other alternatives are dark and everything on my desktop is light. I'd love to get the old color theme back which had a very nice blue tone.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
