### ISSUE TITLE
'Cmd + v' not supported in Opera?

### ISSUE THREAD

**Issue by Lillebo** [bitwarden/browser#1287]
Pasting values from clipboard using `Cmd + v` into any input field does not work. `Right click + Paste` works however.

**OS:** MacOS
**Browser:** Opera version: 68.0.3618.125

**Comment by cscharf** [comment]
Hi @Lillebo , our QA team has re-tested this issue, seems like the Cmd-V key is now working with the Opera extension and Opera 69. Closing this issue for now, please let us know if you do not experience the same results; otherwise it does appear to be a limitation of Opera as we've tested in multiple other extensions and Opera was blocking that keyboard shortcut command in all of them.
