### ISSUE TITLE
Feature Request:  Password Generator utilize previous password parameters

### ISSUE THREAD

**Issue by patmann03** [bitwarden/browser#1305]
## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Browser: [e.g. Firefox 73.0.1]
- Build Version (go to "Settings" → "About" in the app): [e.g. 1.42.2]

## Additional Context

When using the password generator it uses the last password generated to determine the length and password requirements.  It would be great if when generating a new password on a site, if it used the last passwords length and requirements.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
