### ISSUE TITLE
Safari: extension not showing anymore

### ISSUE THREAD

**Issue by v4ld3r5** [bitwarden/browser#1318]
## Describe the Bug

Bitwarden extension icon not showing anymore on Safari

## Steps To Reproduce

1. Go to 'Safari -> Preferences -> Extensions'
2. Click on 'check box' aside Bitwarden extension

## Expected Result

Bitwarden extension gets reenabled

## Actual Result

The box grays out for a second but remains unchecked

## Environment

- Operating system: Mac OS Catalina
- Browser: Safari 13.1.1
- Build Version: 1.45.0

## Additional Context

When checking on systems logs I see:

17:53:40.488137+0200	Safari	Updating secure cursor assertion state to: Valid
17:53:43.532310+0200	Safari	Window is occluded, cannot enable extensions
**17:53:43+0200	Safari	Not enabling extension due to security measures**
17:53:43.539380+0200	Safari	Updating secure cursor assertion state to: Invalid

**Comment by cscharf** [comment]
Hi @v4ld3r5 , this is actually a known bug/issue in Safari on macOS Catalina which has yet to be resolved. From what I've seen/read there are mulitple ways to work around this issue if it's impacting you:

[Found this detailed explanation](https://lapcatsoftware.com/articles/enable-extensions.html)
[Found this on Reddit with quite a few possible workarounds](https://www.reddit.com/r/MacOS/comments/ez5eud/cant_enable_extensions_in_safari_10153/)

Let me know if any of those workaround solves this for you in the interim, however we'll otherwise need to wait for Apple to release a fix/patch for Safari.

**Comment by v4ld3r5** [comment]
Hi @cscharf , thanks for your fast answer.
I was able to workaround it as explained in the first link. I'm using Duet to extend the screen to an iPad, so I tried moving the Safari Preferences window from the main screen into iPad's screen. Then tried to enable the extension from there and it worked!

Hope this helps anybody else, I will close this issue.
Thanks again
