### ISSUE TITLE
Lock after timeout won't work if popped out or in sidebar

### ISSUE THREAD

**Issue by EMostafaAli** [bitwarden/browser#1334]
I setup timeout to 1 hour and the action to lock Bitwarden. Normally, it works great. However, if I pop out Bitwarden in a new window, auto lock will never happen even after resuming OS from sleep.

## Steps To Reproduce

1. Go to Bitwarden settings and set timeout to 1 hour & action to Lock
2. Click on pop out in a new window and keep it open

## Expected Result

After 1 hour, I will expect bitwarden to be locked.
## Actual Result

As long as you keep the pop out window open, lock option will never happen.

## Environment

- Operating system:Windows 10
- Browser: Firefox 78.02
- Build Version (go to "Settings" → "About" in the app): 1.45.0

**Comment by kspearrin** [comment]
This is currently the expected functionality. We treat an open window as an active state, meaning the timeout timer does not start until after the popup window is closed. Perhaps we should change this when dealing with "pop out" window vs "pop up" window.

**Comment by EMostafaAli** [comment]
@kspearrin , I second separate "pop out" from "pop up" case. In 'pop up', when I click away it will automatically close; while "pop out"  will still be open behind other windows and it is a security hazard to let it block auto lock.

**Comment by eliykat** [comment]
I started looking into this and ran into the following questions:

1. How should the "Immediate" vault timeout option work in the "pop out" case? Currently the pop out window is treated as active state, so the timeout never starts to run. If this is changed as suggested and the vault is set to timeout immediately, the pop out window will timeout after 0 seconds of inactivity which makes it unusable. Possible solutions:
   - treat the pop out as active state while it is in focus, and only let the timeout start to run once focus changes to another window. However, with an immediate timeout, this would still prevent any incidental changing between windows (e.g. to copy/paste passwords) which I think would make it similarly unusable.
   - treat the pop out window differently in this case (e.g. set it to timeout after 1 minute even with the "immediate timeout" option) - however this would be confusing and difficult to explain to the user

2. Should there be any change to the sidebar timeout functionality for similar reasons? Is it more similar to the popup, because it's part of the user's main window and is less likely to be forgotten about (and therefore no change required); or is it more similar to the pop out, which can be forgotten and left in the background (and therefore a similar change is required)? I think no change is required for the sidebar, but is this a clear distinction for the user?

**Comment by ajayyy** [comment]
My PR kind of solves this, as it uses the OS "idle" check. It would do it 1 hour after the mouse hasn't moved at all, even if windows are open.

https://github.com/bitwarden/browser/pull/1159

Available on my fork https://github.com/ajayyy/browser/releases/

**Comment by boofthebear** [comment]
I am new to Bitwarden and just started using it. But I stumbled across the same issue and was about to say good-bye to Bitwarden until I read the comments about the pop-up window blocking the timer. Before I did not even knew that there is a pop-up view and so was wondering why my 5 minutes timer would not work. After closing all the Bitwarden pop-ups which for some reason were all active on all the multiple Firefox instances I have usually open.
Reading through eliykat's explanation it is now understood that there is a use case for the pop-up and so to block the timer.

Anyways what would be on my wishlist before I can really commit to using Bitwarden as my password manager is to lock the FF add-on once Windows is locked, sent to sleep or hibernation.

@ajayyy : Would the "Lock on System Lock" feature from your PR solve my request? 
https://github.com/bitwarden/browser/pull/1159

**Comment by ajayyy** [comment]
@boofthebear Yes, it will lock when you sleep or hibernate.

**Comment by rainplease** [comment]
Been meaning to look at this for some time. I'm a user not a programmer.

My setting is a timeout in 15 mins.  The settings do not say timeout - except for pop outs and sidebars. The expected behaviour from a user's point of view is that BitWarden will timeout. BTW, the pop out does not lock on hibernate or sleep (Win 10).

Now I know what's going on I can ensure the pop out is closed, however it is easy to forget, and difficult to train others to do so. IMHO, it is a security issue in an otherwise good piece of software.

You could create different timeouts for each variation, but this is over complicated from a user's point of view, who may not even understand what a pop out or sidebar is.

   > However, with an immediate timeout, this would still prevent any incidental changing between windows (e.g. to copy/paste passwords) which I think would make it similarly unusable.

My expectation is that "immediate" would be after any action has been completed, i.e. allow reasonable time for copy paste. If a user has selected "immediate" they should not be surprised that it locks.

**Comment by JonathanLindsey** [comment]
I believe this is still an issue and in some way a security issue as `rainplease` pointed out.

**Comment by JonathanLindsey** [comment]
My opinion is the browser extensions should be made to act more like the desktop app. The desktop app times out if there has not been any activity (mouse clicks or key presses) _within the context of the BitWarden window_ for the specified time. I think the behavior between the pop-up, pop-out, and side-bar should be consistent, such that if there is a click or key press within the pop-up, pop-out or side-bar, that should be considered activity and reset the timer. The timer should never be turned off. If I do other things on my computer for a while (even in the same browser window as the sidebar) without touching BitWarden, I want the vault to lock; meaning using the OS idle state would allow BitWarden to stay unlocked for too long.

I just now noticed, if you open the simple pop-up and then leave your computer, the vault will stay unlocked. I think it should lock after the specified time just like the desktop app.

The 'immediately' case would need to be handled a little differently. I think it should be handled like the 1 minute case except that once its window looses focus, it waits for a few seconds (maybe 10 seconds) and then times out.
