### ISSUE TITLE
Login fails in Colombian bank with autofill

### ISSUE THREAD

**Issue by jonorozcoc** [bitwarden/browser#1347]
## Describe the Bug

I try to use an entry to login in colombian bank. When I push the login button it generates an error. There is no error when I copy the password manually.

## Steps To Reproduce

1. Go to **https://www.banco.colpatria.com.co/banca-virtual/login/**
2. Enter the login details from autofill
3. Click on "Ingresar" button

## Expected Result

Login and enter to bank portal

## Actual Result

Javascript error and no login action

## Environment

- Operating system: Windows 10
- Browser: Chrome 84.0.4147.105
- Build Version 1.45.0

## Additional Context

Nothing else

**Comment by cscharf** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
