### ISSUE TITLE
Extension closes and does not save when trying to attach a file

### ISSUE THREAD

**Issue by mathiser** [bitwarden/browser#1354]
## Reproducing the bug:

1) click on the extension logo
2) add new login
3) add attachment, choose a file and click save
4) The extension closes and non of  the information in the new login is saved.

## Expected Result
Successful file attachment

## Actual Result:
Unsuccessful file attachment

## Environment

- Operating system: Kubuntu, 20.04 LTS
- Browser: Version 1.14.29 Chromium: 85.0.4183.59 (Official Build) nightly (64-bit)
- Build Version (go to "Settings" → "About" in the app): 1.45.0

**Comment by kspearrin** [comment]
This is a known bug on different browsers, depending on the platform.

**Comment by dofl** [comment]
I've bough premium for this feature, but after not being able to upload an attachment and reading this I'm left with a 10 dollar donation instead of extra functionality

**Comment by mathiser** [comment]
@dofl you can still do attachments in the webvault and through the desktop client.

**Comment by dofl** [comment]
Thanks, I didn't see the option at first in the Web Vault. Now it works.

**Comment by ACodingGenie** [comment]
+1 Pop!_os 20.10 Brave Browser.

**Comment by eliykat** [comment]
This is a limitation at the browser level, so we've worked around it by popping out the edit attachments page into its own window. You can also use the sidebar in Firefox or the desktop client, which don't have this issue. Thanks for bringing this to our attention!

**Comment by TomasTokaMrazek** [comment]
@eliykat Shoudn't the user be at least informed or not be allowed to upload an attachment, when tried from popup? Or it is not possible due to Firefox nature? Not gonna lie, I lived for a few days with the impression, that attachments are indeed uploaded as soon as I click on the file. Later I found that it is not the case and I had to dug deeper, fixing minor self-hosting bugs with proxy and eventually ended here.

**Comment by eliykat** [comment]
@TomasTokaMrazek The issue is that as soon as the system "open file" dialog is opened, the Bitwarden popup loses focus and we can't run any more code from that point onwards - which is why the file upload was being lost without any warning. This was not the intended behaviour, so we also didn't have any warning for the user.

This will be fixed in the next update so that if you try to add an attachment from the popup, it will automatically open Bitwarden in a new pop-out window. It won't just fail silently like it does now.
