### ISSUE TITLE
Bank website claims no password chars are entered

### ISSUE THREAD

**Issue by mjanczykowski** [bitwarden/browser#1366]
## Describe the Bug
A password entered by Bitwarden is rejected by the form on https://www.pekao24.pl

## Steps To Reproduce

Create the following entry in Bitwarden (the form is quite complicated):
- username: 12345678
- website: www.pekao24.pl
- custom fields:
```
customer   |  12345678
regex=-0$  |  0
regex=-1$  |  0
regex=-2$  |  0
regex=-3$  |  0
regex=-4$  |  0
regex=-5$  |  0
regex=-6$  |  0
regex=-7$  |  0
regex=-8$  |  0
regex=-9$  |  0
regex=-10$ |  0
regex=-11$ |  0
regex=-12$ |  0
regex=-13$ |  0
regex=-14$ |  0
regex=-15$ |  0
```

1. Go to https://www.pekao24.pl/
2. Change the language to EN
2. Autotype the username (actually the customer input)
3. Click Next
4. Autotype again (the masked password)
5. Click Log in

## Expected Result

The password should be accepted by the form.

## Actual Result

The following error message is displayed:
"All fields must be completed!" ("Wszystkie pola muszą zostać wypełnione!")

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/3852592/90563192-b7ee7b80-e1a3-11ea-89c6-6d85c5317379.png)

## Environment

- Operating system: Windows 10
- Browser: Chrome 84.0.4147.125
- Build Version 1.45.0

**Comment by zyphlar** [comment]
A lot of times websites will detect if a key has actually been pressed in a form text input, as opposed to just having a value (they're written with the assumption that people will type their password, not use some automated input, which is usually a good thing for security except in this case) so my personal workaround for this is to either remember the last character of my password, delete and retype it, or type a random character at the end (and then delete it if needed.)

Bitwarden would need to inject the keypress/keyup/keydown events into the form in order to get around this issue, and even then if a website really wants to mess with automated password tools it almost always can.

**Comment by clayadams5226** [comment]
The above comment is correct. This website is essentially blocking password managers and not allowing the use of auto-fill.

**Comment by fliespl** [comment]
@mjanczykowski Running this snippet after filling password field with bitwarden works if you are interested. Not sure if it does any good for you, but sharing just in case.

```
document.querySelectorAll('[type="password"]').forEach(function(input) {
    input.dispatchEvent(new Event('input', { bubbles: true }))
});
```

**Comment by fliespl** [comment]
Actually @zyphlar @clayadams5226 maybe adding such event after filling field is not a big deal? Haven't checked how does BW currently fill those?
