### ISSUE TITLE
User ID (auto)fill on banking sites not working

### ISSUE THREAD

**Issue by pduchnovsky** [bitwarden/browser#1378]
## Describe the Bug

Browser extension fails to fill user id fields for banking sites.

## Steps To Reproduce

- Go to either https://sk.unicreditbanking.eu/sk/login_form or https://nib.vub.sk/nibr/login
- Try to autofill user ID (no matter if it's the beta autofill feature or manually clicking on fill within extension or fill shortcut)

## Expected Result

Autofilled saved user ID

## Actual Result

Nothing is autofilled whatsoever in the user ID field(s)

## Screenshots or Videos

![](https://i.imgur.com/MS9zyLD.gif)

## Environment

- Operating system: Windows 10
- Browser: Chrome
- Build Version: 85.0.4183.83

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
