### ISSUE TITLE
Change Shortcut

### ISSUE THREAD

**Issue by MrTomRod** [bitwarden/browser#1387]
The shortcut `Ctrl` + `Shift` + `Y` conflicts with another addon I would like to use ([deepl](https://addons.mozilla.org/en-US/firefox/addon/deepl/reviews/)), but neither addon allows me to change the shortcut.

Please add the option to **disable** or **change** BitWarden's shortcuts!

**Comment by Greenderella** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a section for submitting, voting for, and discussing product[ feature requests](https://community.bitwarden.com/c/feature-requests/5) like this one.

Please [sign up on our forums](https://community.bitwarden.com/) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

**Comment by MrTomRod** [comment]
Oh! Sorry.

For future reference, [there was already such a feature request](https://community.bitwarden.com/t/ability-to-change-keyboard-shortcuts-in-firefox-60/42/8).

The issue has already been solved: Firefox contains the feature of managing shortcuts of addons:

> Navigate to your addons/extensions options (about:addons), click the settings cog, and select “Manage Extension Shortcuts” from the dropdown menu. Bitwarden should be there.
