### ISSUE TITLE
Autofilling passwords ignores the username in separate-pages login forms

### ISSUE THREAD

**Issue by amyspark** [bitwarden/browser#1403]
## Describe the Bug

When Bitwarden encounters a login form split across **physically** separate pages (i.e. separate across a form POST, see <https://www.twilio.com/blog/why-username-and-password-on-two-different-pages>), it may try to auto-fill the username. However, after moving to the password page, it fills the password field with the credentials from the *first* matched entry, which may not be the one corresponding to the user name.

## Steps To Reproduce

1. Make sure you have two or more credentials for the example site (here 'afip.gob.ar').
1. Go to 'https://www.afip.gob.ar'
2. Click on 'Ingresar'
2. Fill in the username manually, and press <kbd>Enter</kbd>.
3. Check the autofilled password in the next page.
4. Press <kbd>Enter</kbd>.

## Expected Result

A successful login.

## Actual Result

Failed login, due to mixed up passwords.

## Environment

- Operating system: macOS 10.14.6
- Browser: Firefox 82.0a1 (2020-09-20)
- Build Version (go to "Settings" → "About" in the app): 1.46.1

**Comment by Greenderella** [comment]
Hi @amyspark, if you have more than 1 credential stored specially with this split login pages, you will want to cycle through the passwords with the corresponding hotkey:

`Windows: Ctrl + Shift + Y`
`Linux: Ctrl + Shift + U`
`macOS: Cmd + Shift + Y`

More information here: https://bitwarden.com/help/article/auto-fill-browser/#keyboard-shortcuts-hot-keys

I have tested this myself and I'm able to successfully login that way.

**Comment by cscharf** [comment]
@xusoo , Could this be unintentional behavior related to the cycling behavior added in the last release? Don't mean to spam you on this but in most scenarios I've found auto-fill will continue to use the _last_ credential used (unless explicitly re-running the auto-fill command, so that works well, however I don't believe we've tested this scenario yet (split login-form with auto-fill on page load enabled).

**Comment by xusoo** [comment]
First of all, I can't get Bitwarden to autofill the username. Not on page load, not with the shortcut and not from the popup:

![image](https://user-images.githubusercontent.com/5207653/93914802-56bc4980-fd07-11ea-91b0-e3a2ef4785af.png)

So, by manually (in "Fill in the username manually, and press Enter") @amyspark, you mean typing it number by number, without Bitwarden? Because if that's the case it won't work indeed. Bitwarden doesn't read the previously entered username (manually) to find a better match among your logins, if that's what you mean.

That being said, you could create a custom field named "F1:username" and put the username there. In that case the auto-filling works well, both from shortcut and from page load.

---

@cscharf There are different possible scenarios that I can think of:
1. **Hidden password field**, like Google or Yahoo do (to mention some of the ones in the [link](https://www.twilio.com/blog/why-username-and-password-on-two-different-pages) from OP). This one works fine because Bitwarden can find the hidden field and fill it in the same keystroke/page load, no need to fill the password independently after clicking 'Next'.
2. Password in a different page, **with a different URL** (the slightest change will do). This should also work fine, because the cycling state is only saved by URL, so if you try to auto-fill the password, it will reset the cycling order and start again from the last used login (which is the one you used for the username).
3. And then, there is this case: you have a different password page, **but the URL doesn't change**, so if you have "Auto-fill on page load" enabled there is no problem (it will load the last used login correctly), but if you don't and you try to use the shortcut a second time for filling the password **within 3 seconds** (cache TTL) after having filled the username, it will indeed fill the incorrect password (next login).

Solution for third scenario... detect when the tab has changed (after a form submit or a redirect, for example). This is what I mentioned in [the original PR](https://github.com/bitwarden/jslib/pull/142#issuecomment-670849827) as a possible implementation. Maybe we could use the page load listener along with the timer to cover as much scenarios as possible.

**Comment by cscharf** [comment]
Thanks @xusoo for the quick response and explanation! Let's wait for the OP and get some clarity on the use-case and see if there's any additional action necessary here.

**Comment by amyspark** [comment]
My use case is a straight migration from Firefox Lockwise - I have to manually enter the user name (or choose from right click -> Bitwarden -> Autofill/Copy username/...). Then, on the next screen, the password is automatically filled in with the wrong value.
Firefox is aware of the previously entered username and fills the password correctly.

**Comment by xusoo** [comment]
> My use case is a straight migration from Firefox Lockwise - I have to manually enter the user name (or choose from right click -> Bitwarden -> Autofill/Copy username/...). Then, on the next screen, the password is automatically filled in with the wrong value.
> Firefox is aware of the previously entered username and fills the password correctly.

Try to do what I said: create a custom field for the username. That way you won’t need to fill up the username manually, and also the password will be filled up correctly in the next page.
