### ISSUE TITLE
Enabling U2F/2FA doesn't ask to re-authenticate

### ISSUE THREAD

**Issue by mfrade** [bitwarden/browser#1406]
## Describe the Bug
Enabling the U2F (or any other 2FA method) should be treated like a change in the master password and request the bitwarden clients already authenticated to re-authenticate. Currently this doesn't happen and the clients stay authenticated without requesting the newly setup U2F (or 2FA).

## Steps To Reproduce

1. setup bitwarden account without U2F (or other 2FA)
2. install the bitwarden browser extension 
3. authenticate into the browser extension 
4. use the bitwarden browser extension to confirm it's working
5. go to bitwarden account and enable U2F (or other 2FA)
6. use the bitwarden browser extension 

## Expected Result

After enabling the U2F (or other 2FA) all clients already authenticated should be bloked and requested to re-authenticate with the newly setup U2F  (or other 2FA)

## Actual Result

The bitwarden clients remain authenticated without any change or notification and they don't ask for the U2F (or other 2FA) authentication

## Environment

- Bitwarden brwoser extension version:  1.46.1
- Operating system: Ubuntu 18.04 (64 bits)
- Browser: 
  - Brave version 1.14.81 Chromium: 85.0.4183.102
  - Firefox version 80.0.1 

## Additional Context

This behavior also happens with the Bitwarden Android client version 2.6.0 (3162)  on Android 8.0.0

**Comment by kspearrin** [comment]
Hi thanks for the suggestion. This is currently the expected functionality. What is the purpose of making existing clients authenticate again?

**Comment by mfrade** [comment]
Hi kspearrin. It is my understanding that if the authentication method changes from 1 factor to 2 factors all the clients must be re-authenticated so that all clients have the same level of authenticity. Currently, it is possible to have different authenticated clients that coexist some with 1 factor and others with 2 factors. The request of all clients to re-authenticate after enabling U2F/2FA already happens on services such as Google accounts and Lastpass. I think this behaviour is the best practice, although I understand that it might not be in the priority list of things to be addressed by the developers.

**Comment by clayadams5226** [comment]
Hi @mfrade, Thanks for the suggestion. We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
