### ISSUE TITLE
Bitwarden fails to minimize background activity

### ISSUE THREAD

**Issue by hlieberman** [bitwarden/browser#1414]
Currently, the Bitwarden extension does a tremendous amount of work in the background, even when the browser is idle.  This should be minimized or eliminated, down to some reasonable threshold.

The tasks I see being reasonable to occur in the background are:

- Syncing, on some n minute interval
- Reading URIs from new tabs to determine if a login is found in the archive for that domain. (If not, it should not search the page for login boxes).
- Firing a timer for locking the vault because of idle delay.

Everything else should be deferred to when the user actually interacts with the extension.

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
