### ISSUE TITLE
Avoid using recursive setTimeouts in content scripts

### ISSUE THREAD

**Issue by jahtalab** [bitwarden/browser#1417]
## Describe the Bug
Currently some content scripts such as [notificationBar.ts](https://github.com/bitwarden/browser/blob/master/src/content/notificationBar.ts#L186), register recursive setTimeouts to update the extension. These timeouts affect the page performance. They also make debugging harder.

## Steps To Reproduce

1. Go to any web page with the extensions default options
2. Check the recursive setTimeouts in devtools

## Expected Result
No recursive setTimeouts.

## Environment

- Operating system: Mac
- Browser: Chrome 84
- Build Version 1.46.2

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
