### ISSUE TITLE
Missing feature: language selection

### ISSUE THREAD

**Issue by andreasbrett** [bitwarden/browser#1418]
The browser extensions as well as the mobile apps adopt to the system's language settings. While being quite handy I'd rather see an option to override that automatic behaviour with a manual language setting. I do like my security apps to be in english while my OSes are in german. I setup the web and desktop application of BW to be in english and I'd be happy if I could set the browser extension and mobile app to english as well. It's inconsistent to have that option on some platforms while others are "stuck" with an auto setting that can't be overridden.

Note: This had been raised [some days ago](https://github.com/bitwarden/browser/issues/1415) and got closed quickly (reason: it's a feature not a bug). I do think though that having the option to decide the display language per app/extension would be beneficial.

**Comment by cscharf** [comment]
Thanks for the report @andreasbrett ! 

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
