### ISSUE TITLE
login on website that redirect to different domain doesn't show save password promt

### ISSUE THREAD

**Issue by ravelgwong** [bitwarden/browser#1419]
## Describe the Bug

When logging in to a website that redirect to a different domain name, bitwarden does not show any password save promt.

## Steps To Reproduce

Go to a login page of a website that use a different domain for it's login and main page. 
Try to login/register

## Expected Result

The save password prompt should be shown on both login domain and main domain.

## Actual Result

The prompt is only shown on login page, and as the page redirect to the authenticated page, the prompt disapper.

## Environment

- Operating system: Ubuntu 20.04 LTS
- Browser: Google Chrome 85.0.4183.121
- Build Version : 85.0.4183.121

**Comment by bradns** [comment]
I'm also seeing this problem. I consider it to be a very serious issue. In the right circumstances, it could lead to a user changing their password for an important service and then **immediately** losing the password. Please look into this soon.

Operating System: Mac OS 10.15.7
Browser: Google Chrome 86.0.4240.75

**Comment by Alex-Samari** [comment]
I have this issue too. It's an extremely annoying problem with bitwarden which has been a huge headache for me after switching from Firefox password manager to Bitwarden. I've had to reset my passwords at least a dozen times

**Comment by eliykat** [comment]
Can you link me to some websites that experience this issue, so that I can recreate / debug it on my end?
Does the login need to be successful (i.e. valid username and password) for the issue to arise?

As a workaround in the meantime, you can add the login to the website first, and then use it to autofill the registration or change password form.

**Comment by eliykat** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1620. Please also direct any discussion or questions to that issue. This issue will now be closed.

**Comment by Alex-Samari** [comment]
> Can you link me to some websites that experience this issue, so that I can recreate / debug it on my end?
> Does the login need to be successful (i.e. valid username and password) for the issue to arise?
> 
> As a workaround in the meantime, you can create the login in Bitwarden first, and then use it to autofill the registration or change password form. Also, if you've "lost" a password generated by Bitwarden, you may be able to recover it in the Bitwarden extension > Generator > Password History.

This is cumbersome. What I've seen in other password managers such as LastPass is the ability to "Save the login BEFORE signing up". Meaning LastPass will show a popup to save the "filled login form" before the "signup" button is pressed. It's a must-have feature for me and would love to see it in bitwarden.

As for which sites this happen to, any website that redirects from the signup page to another domain will have this issue with Bitwarden. I suggest implementing my suggestion above instead of trying to handle re-directions as it would be very complicated compared to an easy and UX-friendly fix of "saving logins before signup"

**Comment by eliykat** [comment]
@Alex-Samari That's interesting, I didn't know LP handles it like that. How is the save prompt triggered - does the user press a key or open the extension before pressing submit?
