### ISSUE TITLE
Place of the scroll is not remembered

### ISSUE THREAD

**Issue by Neurotoxin001** [bitwarden/browser#1439]
## Describe the Bug
I have 127 items in my vault and when I scroll to the bottom and open an item and then close it to go back to items list I always get in same place and must scroll again and again, this happens only in the bottom of the list

## Steps To Reproduce

1. Open "Without folder" list of items
2. Scroll to the bottom
3. Open any item
4. Click close to go back
5. You appear not where item that you click, but little bit above it

## Screenshots or Videos
https://i.imgur.com/GBA9uj1.mp4

## Environment

- Operating system: Windows 10 LTSB 1809
- Browser: Google Chrome 86.0.4240.111
- Build Version: 1.46.2

**Comment by clayadams5226** [comment]
Hi @Neurotoxin001 this is actually the intended behavior and not a defect. 

We use GitHub issues as a place to track bugs and other development-related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
