### ISSUE TITLE
Incorrect variable referenced in if statement

### ISSUE THREAD

**Issue by eliykat** [bitwarden/browser#1441]
https://github.com/bitwarden/browser/blob/3629c2c0d53ec754bd6951629148092f2afe177a/src/services/autofill.service.ts#L243-L257

The if statement on line 255 does not match the description in the comment. It should test `autoFillResponse` to test if the autofill was successful. `fromCommand` is a boolean that indicates whether or not the function was triggered by a keyboard shortcut, which is unrelated.

I am happy to submit a simple PR to fix this if I have understood it correctly.

**Comment by cscharf** [comment]
Thanks @eliykat , the comment is correct there, as is the logic, but the comment is incomplete IMO, a simple PR to fix the comment would be cool, basically we only want to update the lastUsedIndexForUrl if this is being done from an explicit keyboard command.... which that line would naturally only get executed if there is not an exception, in the case of an exception the rest of the that method would be missed because the exception would bubble up the execution chain once thrown.

If autofill is not successful, the `doAutoFill` method will throw an exception, which is not handled here by the promise since we're using `await` and therefore would bubble that exception.

The `autoFillResponse` (return value from `doAutoFill`) is either going to be a TOTP code or `null`, which has no bearing on whether we update the last used index.

**Comment by eliykat** [comment]
Gotcha - I'll submit a PR so that no-one else gets confused by the comment like I did ;)

**Comment by wusatosi** [comment]
> Gotcha - I'll submit a PR so that no-one else gets confused by the comment like I did ;)

Please checkout the pull request #1517 and see if this makes it better :)
