### ISSUE TITLE
Microsoft Edge not asking for Yubikey in FIDO U2F mode

### ISSUE THREAD

**Issue by theonlybrand** [bitwarden/browser#1474]
## Describe the Bug
!!!Microsoft Edge only!!!
Yubikey 5 is registered as FIDO U2F device. When logging in I instantly have an HOTP sent to my mailbox (as I have mail set up as fallback for U2F).

## Steps To Reproduce

Requirement: Have a Yubikey configured for FIDO U2F.

1. Open "Microsoft Edge"
2. Navigate to vault.yourdomain.com
3. Login with your credentials and wait for second factor.

## Expected Result

Get prompted with Windows Hello dialogue to enter my Yubikey PIN.

## Actual Result

Mail gets sent to my inbox, which is configured for fallback purposes.

## Environment

- Operating system: Windows 10 20H2 (OS Build 19042.630)
- Browser: Microsoft Edge: 87.0.664.47
- Build Version: 2.17.0

**Comment by Greenderella** [comment]
Due to platform limitations, FIDO U2F cannot be used on all Bitwarden applications. You should enable another two-step login provider so that you can access your account when FIDO U2F cannot be used. 

Supported platforms: Web vault and browser extensions on a desktop/laptop with a U2F enabled browser (Chrome, Opera, Vivaldi, or Firefox with FIDO U2F enabled).

**Comment by timcappalli** [comment]
https://github.com/bitwarden/web/issues/703
