### ISSUE TITLE
Allow multiple password and keyfile 

### ISSUE THREAD

**Issue by petitminion** [bitwarden/browser#1484]
Hello, 

This is a feature request to allow multiples master password and the use of a keyfile. 

This way, we could unlock the vault automatically at boot in a secure environment if we wish to. 

I know some think a master password should only exist in one's head, but thus of us who don't because of our specific OPSEC should have the opportunity to log-in with a very strong password that only a machine can remember. Maybe add a warning to the security risk of using a keyfile or hidding a little the feature could prevent people not aware to exposed their passwords.

Thx ! :)

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
