### ISSUE TITLE
Autosave new login

### ISSUE THREAD

**Issue by elo613** [bitwarden/browser#1485]
**Issue:** Bitwarden does not save new account registration passwords for several websites

**Examples**: BBC, Student Room 

Example - Student Room
1. Go to https://www.thestudentroom.co.uk/
2. Click Sign up
3. Click Sign up with email
4. Fill out the form and slide the button

**Expected outcome**: 
Bitwarden would offer to save my new account

**Question**: is this solvable? Is there a setting I have to fix? 

**Environment**: Chrome web-browser plugin (installed on 7/Dec/2020) on Windows machine. I do not have any other password manager including chrome-built in activated

**Comment by wusatosi** [comment]
This is a duplication with #320.

**Comment by eliykat** [comment]
This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1620. Please also direct any discussion or questions to that issue.

**Comment by awslabspl** [comment]
> This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1620. Please also direct any discussion or questions to that issue.

Oh yeah......... tell us more of this............

Fact is that **this issue is experienced by broader and broader audience and is related to every website out there, This feature is simply broken.
The fact that BW-team tries to blame whoever/whatever else but not themselves, speak volumes. I will not demand refund and/or fill a lawsuit, but I regret spending $10 as the way of supporting team. I will NOT do this again.
