### ISSUE TITLE
Current activity lost when closing the vault

### ISSUE THREAD

**Issue by sylbru** [bitwarden/browser#1490]
## Describe the Bug

When I’m in the middle of an operation (creating a new identifier usually) and I have to click somewhere in the page, the vault automatically closes. When I open it again, it has forgotten everything that I had just typed.

Is this intentional? It feels annoying.

## Steps To Reproduce

1. Open Bitwarden vault (browser extension)
2. Start any kind of operation : search for a couple characters, or start adding an item without validating
3. Click anywhere in your current web page. The extension panel closes.
4. Open the extension panel again.

## Expected Result

I would expect the extension panel to remember the ongoing operation for some time.

## Actual Result

When you open the extension panel again, it has forgotten all about what you were doing.

## Environment

- Operating system: all
- Browser: all
- Build Version 1.47.1

**Comment by NiavlysB** [comment]
I think just a 30 second "grace period" would do it for me!
But I would also think it wouldn’t harm to remember any ongoing operation for as long as the vault is unlocked. Operations that don’t involve any kind of input should be ignored.

Love the software and pricing policy by the way!

**Comment by daviddem1971** [comment]
I do find it annoying too. Luckily I use Firefox, and the Bitwarden sidebar does not behave like that (unlike the extension itself).

The downside of the sidebar is that for as long as it's open, the vault won't autolock after the set timeout period.

**Comment by tobiasgraeber** [comment]
Same here. I would even go further and say: The Popup should NOT close automatically by clicking back into the website, when opened - that would make it a lot easier to, for example, copy/paste credentials or any other information between a web page and a vaults entry on editing or initial add

**Comment by deefdragon** [comment]
> I would even go further and say: The Popup should NOT close automatically

Unfortunately, as far as I was able to look up real quick, this is [an intentional design decision](https://developer.chrome.com/docs/extensions/mv3/faq/#faq-persist-popups), but is indeed rather infuriating.

I think the only solution to this is to save the state the editor is in when the popup closes, and return to that state on opening again, which I suspect would be a rather large ask.

I think it is an ask worth it myself, given I have nearly lost some VERY important passwords because the editor closed before they were saved.

**Comment by elpiel** [comment]
I want to vote on this issue as well. It's annoying but mainly it makes it harder to use BitWarden at the end.

**Comment by aster94** [comment]
I still consider this a great improvement for bitwarden

**Comment by sylbru** [comment]
Yes, apparently I’m not the only one concerned with this issue. It really makes Bitwarden painful to use in some cases.

**Comment by elpiel** [comment]
I consider as a great improvement too.

**Comment by dwbit** [comment]
Hey everyone, since this is an ongoing discussion/request, we'll be directing follow-up to the Bitwarden Community Forums. You add your feedback and vote on the following request:

- [Persist Bitwarden UI and maintain unsaved data](https://community.bitwarden.com/t/persistent-bitwarden-ui-and-maintain-unsaved-data/5470)
