### ISSUE TITLE
'Successfully edited' green bar at bottom covers horizontal row of icons

### ISSUE THREAD

**Issue by OddHouseGames** [bitwarden/browser#1509]
After editing an entry using the Bitwarden browser extension for Firefox, the green bar with text for a successful edit, is completely covering the bottom row of icons for  tab, my vault, generator, settings.

It would be optimal for the message to not appear at the very bottom of the browser extension window.

Changing the placement to above the row of icons or centered in the window, or near the top would be an improvement.

The benefit would be that you could instantly resume using the icons at the bottom without having to wait for the green text bar to fade.

**Comment by SergeantConfused** [comment]
Hi there,

Thank you for your input. Please note that you can click on that banner to acknowledge and remove it, instead of waiting for it to go away.

I hope that helps. Please let me know if you have any questions.

All the best,

**Comment by OddHouseGames** [comment]
Thanks, I did realize that, but from a UX/UI point of view, what is the purpose/advantage of having the banner cover the home row of icons at the bottom?

It seems like the banner could be place so not to cover the interaction area at the bottom?

**Comment by clayadams5226** [comment]
Hi @OddHouseGames , We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by OddHouseGames** [comment]
Hi Clay,

I wouldn't categorize optimizing the placement of the 'successful edit' banner as a feature request, it's an issue with accessibility. It is covering the navigational UI when it could easily appear above it.

It blocks navigation and requires an unnecessary click to remove it.
