### ISSUE TITLE
Confirmation of settings change blocks navigation of plugin

### ISSUE THREAD

**Issue by thetruetigerlily** [bitwarden/browser#1519]
## Describe the Bug
Confirmation of settings change blocks navigation of plugin. Takes too long to dissipate and makes getting passwords take too long.

## Steps To Reproduce

1. Go to Settings
2. Click on Sync
3. Click on Sync Now

## Expected Result

Confirmation should appear at the top away from the buttons.

## Actual Result

Confirmation appears over buttons.

## Environment

- Operating system: Windows 10
- Browser: Chrome 87.0.4280.88
- Build Version (go to "Settings" → "About" in the app): 1.47.1

**Comment by SergeantConfused** [comment]
Hi there,

Please note that you can tap or click on that banner to remove it, no need to wait for it.
I hope this helps.

All the best,

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
