### ISSUE TITLE
Bitwarden saves a random string of letters and numbers as the password, instead of what was actually typed and entered.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/browser#1527]
## Describe the Bug
When logging into specific sites and clicking 'Yes, Save now' on Bitwarden's prompt to save those credentials and add them to the vault, Bitwarden saves a random string of characters instead of what was actually typed into the password field. 

## Steps To Reproduce
1. Go to: https://testservices.nic.in/examsys/root/Home.aspx?enc=WPJ5WSCVWOMNiXoyyomJgLE35Lxb9T1jSXt18xUK2R70CHN5WAWQJ7zG6tKAYKvF
2. Enter '123' into the Application No field.
3. Enter 'passwordtest' into the Password field.
4. Enter the Security Pin (CAPTCHA).
5. Click on Sign In.
6. Click on Yes, Save now on Bitwarden's prompt.
7. Open the new vault item in your extension and look at the password.

## Expected Result
To see 'passwordtest' in the Password field.

## Actual Result
A random string of numbers and letters is present in the Password field.

## Screenshots or Videos
N/A.

## Environment

- Operating system: Windows 10 Pro.
- Browser: Chrome Version 87.0.4280.88.
- Build Version: 1.47.1.

## Additional Context
N//A.

**Comment by DejfCold** [comment]
I also found this on some websites. I believe the problem is that the website itself replaces the password with random string on blur (or right before submit) and stores the actual password somewhere else. Bitwarden then just reads the content of the password field on submit, which the website itself changed.

However when I tried your website, it works fine. Or at least it works fine if the security pin is not entered thus form is not submitted.

I changed the password's field type to `text` so it's easy to visualise. But the same happens if the type is the default `password`.
![image](https://user-images.githubusercontent.com/12591578/105866501-581ebb00-5ff4-11eb-9e76-de32d7d6d818.png)
