### ISSUE TITLE
[Feature req] please allow to remove the item count badge from the addon icon

### ISSUE THREAD

**Issue by gpioneer90** [bitwarden/browser#1546]
When Bitwarden detects a login for a website you are on it will display how many matching logins are available. 

Addons like uBlock Origin and others that have counters too, all allow you to turn these counters off from the icon. 

Please consider implementing this on Bitwarden too as an option in the menus. 

Thanks!

**Comment by clayadams5226** [comment]
Hey @gpioneer90, We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
