### ISSUE TITLE
Unable to install Bitwarden Safari Extension on M1 Mac

### ISSUE THREAD

**Issue by tensojka** [bitwarden/browser#1547]
## Describe the Bug

After installing the Bitwarden extension from the Mac App Store, clicking on "open" in the App Store does nothing and the extension doesn't appear in Safari settings nor Launchpad. 

## Steps To Reproduce

1. Open Mac App Store, type Bitwarden 
2. Install Bitwarden, enter password if required.
3. Instead of "Install", App Store now shows "Open".

## Expected Result

After clicking on Open or opening Safari Preferences, Bitwarden should be present. 

## Actual Result

Bitwarden doesn't show up in Safari even after a reboot.

## Environment

I do NOT have Rosetta 2 installed. When I try to open DuckDuckGo Privacy Essentials, installed from the Mac App Store, a banner saying that I must install Rosetta 2 pops up. That doesn't happen with Bitwarden, though.

- Operating system: Mac OS Big Sur
- Architecture: arm64

**Comment by cscharf** [comment]
Hi @tensojka , Rosetta 2 is currently required in order to run Bitwarden on an M1 Apple Silicon Mac (for now). We're working on native support but likely won't be ready for that until Feb'ish this year. We are not planning on adding a formal banner/notification for the Rosetta 2 requirement at the moment given the need for engineering resources and short time-frame before native M1 Mac support.

**Comment by porcherie** [comment]
On my M1 Macbook the extension functionality depends on the installation of Safari Technology preview. I tried to uninstall it and the extension was gone. Re-installed safari and the extension was magically back where it should be. 
Just my 2 cents
