### ISSUE TITLE
Vault blocking after log off doesn't work on Brave Browser

### ISSUE THREAD

**Issue by tkielarbb** [bitwarden/browser#1551]
## Describe the Bug

Blocking the vault option in Brave extension doesn't work when set to lock when loggin off. It will block the vault even when just restarting browser.

## Steps To Reproduce

1. Open Browser extension
2. Go to settings and change the vault blocking behaviour to "after logging off"
3. Just restart the browser
## Expected Result

Still be able to access the vault without PIN

## Actual Result

It's locked and prompts for PIN

## Screenshots or Videos

None

## Environment

- Operating system: Windows 10
- Browser: Brave 1.19.86 Chromium: 88.0.4324.96
- Build Version: : 1.48.0

**Comment by SergeantConfused** [comment]
Hi there,

This is the expected behaviour. Once you restart your browser, regardless of your Vault Timeout Action, you would need to unlock your vault. More on this here: https://bitwarden.com/help/article/vault-timeout/

I hope this clarifies everything up for you. Please let me know if you have any further questions.


All the best,
