### ISSUE TITLE
Have to use biometrics twice in order to unlock browser extension

### ISSUE THREAD

**Issue by pduchnovsky** [bitwarden/browser#1553]
## Describe the Bug

Unlocking with biometrics is either designed not in the best way or bugged.
I have to unlock vault on my desktop app with biometrics and then I have to unlock the browser extension AGAIN with biometrics, why doesn't the browser extension unlock WITH the desktop app ?
This is beyond my understanding.

## Steps To Reproduce

- Start desktop app
- Unlock it with biometrics
- Start browser
- Browser extension is still locked, have to open it, press "unlock with biometrics', then the same app that is already unlocked asks for biometrics in order to unlock browser extension

## Expected Result

- Browser extension upon loading checks whether desktop app is unlocked and unlocks vault if it is.

## Actual Result

- Browser extension is not unlocked when desktop app is unlocked

**Comment by ikjadoon** [comment]
Agreed. 

Either the desktop app should send its unlocked state to a newly-opened browser extension or [we should be able to disable the system app's forced unlock on boot](https://community.bitwarden.com/t/far-too-many-prompts-to-unlock-with-biometrics-windows-hello-browser/17142) (as I do not use the system app for anything except unlocking the browser extension).

**Comment by pduchnovsky** [comment]
I'd personally prefer to actually unlock the app upon logging in to the system with biometrics, having to unlock the extension separately is always cumbersome. 
I mean, system where I install an extension is trusted for me and when I login using my biometrics it means I want it really unlocked.
What's the point separating this, at least it should be an option.

**Comment by clayadams5226** [comment]
This is the current expected behavior for bio unlock. If you'd like to suggest a change to it I recommend making the request on our community forum. 

The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
