### ISSUE TITLE
Vault Timeout 'On System Lock' option not available on Firefox extension

### ISSUE THREAD

**Issue by rabader** [bitwarden/browser#1554]
## Describe the Bug

Version 1.48.0 of the Chrome extension has an option under 'Vault Timeout' to set a value of 'On System Lock'. The same version (1.48.0) of the Firefox extension does not have this option.

## Steps To Reproduce

1. Using the Firefox extension, go to 'Settings'.
2. Under the 'SECURITY' section, click on the drop-down menu under 'Vault Timeout'.

## Expected Result

An option of 'On System Lock' should exist, as seen on Chrome/Edge extensions.

## Actual Result

This option does not exist.

## Environment

- Operating system: Windows 10
- Browser: Firefox 84.0.2 (64-bit)
- Build Version: 1.48.0

**Comment by douglasparker** [comment]
I think that I read somewhere that the reason this wasn't implemented was because Firefox doesn't support the necessary API for this functionality.

I very briefly just look a look and found the [idle](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/idle) API for Firefox.

Wouldn't this allow Bitwarden to provide the on system lock functionality for the Firefox extension? I'd love to see this implemented as it works really well with my workflow.

**Comment by kspearrin** [comment]
@douglasparker Please see the compatibility chart at the bottom of your link that highlights Firefox's lack of support for `locked` events.

**Comment by douglasparker** [comment]
> @douglasparker Please see the compatibility chart at the bottom of your link that highlights Firefox's lack of support for `locked` events.

@kspearrin Ah, I just assumed that because `idle.onStateChanged` was supported that it could be implemented.

I do see that `idle.onStateChanged.locked` is not supported though. I imagine this means it's partially implemented?

Regardless, hopefully Firefox fully implements this so that Bitwarden can take advantage of it in the future. We'll have to keep an eye on this. 😀

**Comment by clayadams5226** [comment]
Closing this task for now since there isn't anything we can do from our side.

**Comment by enz0nun3s15** [comment]
What about a homemade solution with a "monitor process" where Bitwarden makes periodic checkpoints and compares to the last saved timestamp? If there is a huge gap between the timestamps, something happened and Bitwarden should lock itself. This would open doors to implement other features like periodic password leak check or live notifications.
