### ISSUE TITLE
Inactive TOTP buttons shown for non-premium members

### ISSUE THREAD

**Issue by nils-werner** [bitwarden/browser#1556]
## Describe the Bug

Bitwarden shows dead TOTP button for non-premium members. The button is there, greyed out, and does nothing,

## Steps To Reproduce

1. Have a Free account
3. Unlock vault
4. All logins show a TOTP button

## Expected Result

Do not show the button if I cannot use them

## Actual Result

A greyed out button is shown.

## Environment

- Operating system: Linux
- Browser: Firefox 84.0.2
- Build Version 1.48.0

## Additional Context

I am aware that as a free member I cannot use TOTP. However, as a free member, I also don't want to see buttons that I cannot use anyways.

**Comment by Greenderella** [comment]
Hi @nils-werner, we use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

**Comment by nils-werner** [comment]
I think you are misunderstanding: This is a bug.

I am suddenly seeing buttons that I didn't see before, and I can't use any of them.

**Comment by jjoonathan** [comment]
This bug is locking me out of coinbase.
