### ISSUE TITLE
Inactive TOTP buttons when TOTP isnt there

### ISSUE THREAD

**Issue by Prajwal-Koirala** [bitwarden/browser#1559]
Hello,
So the issue is when there is no TOTP, it will still show the button and its confusing so can u make a PR where if its not there than it will not show.

**Comment by SergeantConfused** [comment]
Hi there,

Please consider joining our community and submitting your suggestion directly on our Feature Request page here: https://community.bitwarden.com/c/feature-requests/5 to allow the members of our community to vote for it. If your idea resonates with the community, it may make its way into a future version of Bitwarden.

I thank you in advance for your understanding and cooperation.


All the best,

**Comment by Zeik0s** [comment]
@SergeantConfused in my Opinion that's not a Feature Request, more like a regression (i hope that's a term for a bug that appeared in a new version, but wasn't there before). It shouldn't be an extra Feature, that the button for TOTP is not displayed when there is no TOTP secret stored.

**Comment by cscharf** [comment]
Hi @Zeik0s , the TOTP copy button feature was added in this last release as an enhancement for easy access / 1-click copying of the TOTP code for a saved login within your vault. Understanding there are some users who do not have TOTP (free version) or the login does not use TOTP, the button becomes disabled. This is in following a consistent pattern within Bitwarden as when functionality is not applicable or not there, it's simply disabled on-screen vs. hidden.

To change this portion of Bitwarden's consistent UX, that would be a change request/enhancement and something to be considered as a feature request since it deviates from the standard Bitwarden behavior to suit preferences. I'm not saying it's right or wrong, simply stating that it's a change to behavior and warrants a feature request on our community forums to advocate for that change with the broader community and our product team.

Thanks again for your feedback and have a great day!

**Comment by Prajwal-Koirala** [comment]
@cscharf 
I have bitwarden pro and when i don't have TOTP enabled for a certain website it will still show the button and that is confusing as hell so i try and copy the TOTP but there is nothing there.

This is a very minor change, and bitwarden already pulled out their HR department.

**Comment by Zeik0s** [comment]
@Prajwal-Koirala please upvote: https://community.bitwarden.com/t/show-totp-copy-button-only-when-totp-is-stored-enabled/17071 😉
