### ISSUE TITLE
Cannot export only selected folders or entries

### ISSUE THREAD

**Issue by TesterMan247** [bitwarden/browser#1572]
Currently, its very easy to export exactly what entries you need to export in KeePass, however, you cannot easily do the same thing on Bitwarden.

Please see here for more information:
https://community.bitwarden.com/t/how-do-you-export-only-select-folders/16776

**Comment by Greenderella** [comment]
Hi @TesterMan247 , we use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so (like in this case), you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

**Comment by TesterMan247** [comment]
Hi @Greenderella

Thanks for letting me know.

I have done so as requested.

Here is the link in case someone comes to follow on from this:
https://community.bitwarden.com/t/ability-to-export-only-selected-folders-or-entries-instead-of-the-whole-vault/17063
