### ISSUE TITLE
Can't login with 2FA U2F Yubikey

### ISSUE THREAD

**Issue by 7redeagle** [bitwarden/browser#1579]
## Describe the Bug

Can't login through the extension with the 2FA U2F yubikey.

## Steps To Reproduce

1. Login via the browser extension
2. Input password 
3. Then insert yubikey and press the button

## Expected Result
After inputting password, the screen should allow login via yubikey.

## Actual Result
After inputting password, the screen keeps showing loading circle for the u2f input but after a minute, the extension closes and I had to re-input the password. 

## Environment

- Operating system: Chrome OS
- Browser: Chrome 
- Build Version: Version 88.0.4324.109 (Official Build) (64-bit)

**Comment by clayadams5226** [comment]
Hey @7redeagle, Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
