### ISSUE TITLE
Bitwarden in Firefox's UI box opens up with half the size

### ISSUE THREAD

**Issue by mystic-githuber** [bitwarden/browser#1582]
Bitwarden in Firefox sometimes is half the size when opening the addon. This issue is there every other time it opens-up. Sometimes its normal and sometimes its not.

Firefox 85
Bitwarden 1.48.1

![Bitwarden Bug](https://user-images.githubusercontent.com/66426048/106289067-b7710b00-6240-11eb-83f0-3b0fdfd8a663.png)

**Comment by douglasparker** [comment]
This happens to me as well. :(

Firefox v85
Bitwarden v1.48.1

**Comment by Greenderella** [comment]
Hi, I'm sorry to hear you are experiencing this issue. We have been unable to reproduce this issue on the team.

Will you first try uninstalling the extension, removing any leftover data, resetting your device and re-installing? Does this issue still persist?
Removal of the leftover data is important. New installation may hold on to old installation files and cause the same issues.
Guide to the leftover data: https://help.bitwarden.com/article/where-is-data-stored-computer/

**Comment by cho-m** [comment]
Do you have `privacy.resistFingerprinting = true` in `about:config`?

I see the same behavior with this config, which I assume is due to Firefox spoofing browser information.  The Firefox API that Bitwarden accesses is probably providing fake data.

There could also be some other Firefox configs that do something similar.  You would need to start with a clean config/user.js to find out.

**Comment by mystic-githuber** [comment]
@cho-m @Greenderella 

You are right, the fingerprinting resist in the config file was turned on.

**Comment by douglasparker** [comment]
Thank you so much @cho-m, `privacy.resistFingerprinting` was indeed the culprit!

Strange because this was a fresh install and I don't remember changing anything in `about:config`

Solved regardless! Thanks!

**Comment by paulverbeke** [comment]
Is it solved though ? 
I have `privacy.resistFingerprinting = true` in Firefox for the last year and Bitwarden was working fine until recently.
What if we want to keep this setting on ?
Have something changed recently in Bitwarden codebase regarding UI rendering ?
Thanks for any input.

**Comment by cho-m** [comment]
@paulverbeke I took a look through Bitwarden's code and I don't think anything changed. At bottom of reply, I included what seems to be the logic to handle resize and the code is 3 years old.

It looks like there are 3 possible heights based on reported `availHeight`:
- 300px (< 600),
- 500px (600-800),
- 600px (> 800)

Also, it is possible that TOR and/or Firefox could have modified their fingerprint spoofing logic during the last year.

I think `availHeight` is used since it should correspond to your display resolution and the resize logic allows people with older/low-res displays to use Bitwarden. Firefox probably spoofs this value since it is a roughly static value that relates to your display resolution, so it can help uniquely identify you.

I can't comment much on if there is a way to get around this behavior. Someone will need to look further into TOR/Firefox's implementation of `resistFingerprinting` and if there is another way to determine usable height.

Maybe the sizing implementation of other popular extensions can be used as a basis for rewriting the way Bitwarden sizes the popup.
A last ditch solution would be to provide some user-modifiable extension option to always use 600px for popup size.

---

- https://github.com/bitwarden/browser/blob/dae739bc1766243cb9df514696f033f6067bb991/src/popup/services/services.module.ts#L82-L85
  - Last changes 3 years ago from [Git Blame](https://github.com/bitwarden/browser/blame/dae739bc1766243cb9df514696f033f6067bb991/src/popup/services/services.module.ts#L82-L85)


---

- https://github.com/bitwarden/browser/blob/dae739bc1766243cb9df514696f033f6067bb991/src/popup/scss/base.scss#L28-L36
  - Last changes 3 years ago from [Git Blame](https://github.com/bitwarden/browser/blame/dae739bc1766243cb9df514696f033f6067bb991/src/popup/scss/base.scss#L28-L36)

**Comment by paulverbeke** [comment]
Thanks for all that.
Just for the sake of clarifying: the size is wrong each first time Bitwarden is openned PER tab.
When on tab A, when I first open Bitwarden the size is half, I close an open it again and now the size is fine, and the size will be fine for every other times openned on this tab.
I move to tab B and same deal, when I open Bitwarden for the first time the size is half, openning again "fix" the size.
You're probably right though, the changes must be on Firefox end.

**Comment by cho-m** [comment]
Doing some more searching, it looks like issue has been around for at least 2 years. There is a topic on Bitwarden forum from January 2019.

This comment has some good analysis of issue, which should explain what you are experiencing: https://community.bitwarden.com/t/bug-invalid-window-size-in-firefox/3683/9

In summary, the first time you open the extension, it uses `screen size = window size` so `availHeight=0` and will always give you smallest window (300px). If you reopen quick enough, it will use previous value (in my case `availHeight=600`) and then increase the size to next option (500px for me).

The post also includes a possible fix by adopting LastPass's approach of scaling height to contents and probably dropping some support for low-res displays.

We probably need input from someone on Bitwarden's core team to comment if Bitwarden's sizing behavior can be changed to match the behavior of competitors (e.g. LastPass) and/or other popular extensions.

**Comment by paulverbeke** [comment]
Cho-m thanks for your help and investigation.
I removed resistFingerprinting as that became really annoying.
And by removing this I realised that it was causing a lot of problems I had in Firefox over the last year like extensions problems, graphical glitches,... Anyway I'll leave resistFingerprinting at disabled for now on

**Comment by luoe** [comment]
This issue has reappeared (I assume with FF 118, at least on Linux).
_privacy.resistFingerprinting_ was not set to true in the advanced config.

However, setting _Enhanced Tracking Protection_ to Custom and disabling _Known fingerprinters_ resolves this issue (make sure to restart FF or just click _Reload All Tabs_).
I don't mind having _Enhanced Tracking Protection_ enabled (except for Cookies) since UBlock Origin is doing a great job.

![Screenshot_20231002_224610](https://github.com/bitwarden/clients/assets/24625682/80fe61cf-a13d-4b6c-9488-320ad16a05ec)


Did not want to open a new issue. Also pinging #3221, if someone sees this issue first.
