### ISSUE TITLE
The field Notes exceeds the maximum encrypted value length of 10000 characters (when it is false)

### ISSUE THREAD

**Issue by mcvendrell** [bitwarden/browser#1618]
## Describe the Bug

When trying to save text of 7720 bytes length (Notepad++ data) the error about length of 10000 is thrown

## Steps To Reproduce

Simply paste any text greater than 7480 chars

## Expected Result

Save up to 10000 chars

## Actual Result

The error appears and user cannot save

## Environment

- Operating system: Windows 10
- Browser: Chrome
- Build Version (go to "Settings" → "About" in the app): 1.48.1

**Comment by Wqrld** [comment]
Coming from lastpass im having the same issue. Can't import even though ive removed all notes from my file. it just fails on a random line and removing that has no effect.

**Comment by eliykat** [comment]
@mcvendrell - The char limit applies to your data after it's been encrypted. Our encryption algorithms increase the length, so 7480 -> 10000 sounds about right. This is why the error message refers to "encrypted length".

@Wqrld - the line numbering refers to the CSV index numbers, not just the line number in the file. You'll have to open it with Excel or Google Sheets (or similar) to get the correct line numbering, and then adjust for header rows. See our help article here: https://bitwarden.com/help/article/import-data/#troubleshooting-import-errors. This can unfortunately take a little trial and error, we're working on better error messages at the moment to make this process a little smoother.

If you're still having issues, please contact our customer success team to help you further: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed.

**Comment by mcvendrell** [comment]
@eliykat good to know. So, to be more clear to users, maybe will be a good idea to say in the error "The field Notes exceeds the maximum value length of 7500 characters (aprox)" No one knows about the algorithm, but an aprox number should be enough for almost all users.
