### ISSUE TITLE
Should ask for confirmation if I close popup without saving changes

### ISSUE THREAD

**Issue by stevemarksd** [bitwarden/browser#1632]
## Describe the Bug

create a new entry
close

should ask for popup to confirm. I lost data so many times that I can't count!

## Steps To Reproduce

4. Click on '...'

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Browser: [e.g. Firefox 73.0.1]
- Build Version (go to "Settings" → "About" in the app): [e.g. 1.42.2]

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
