### ISSUE TITLE
Blue icon in Safari

### ISSUE THREAD

**Issue by olitus** [bitwarden/browser#1643]
## Describe the Bug
I am using Safari Version 14.0.3 and would like the icon to be grey instead of blue.

## Steps To Reproduce
1. Install Bitwarden Safari extension for Safari Version 14.0.3.
2. Add the Bitwarden icon to the Toolbar.

## Expected Result
I would like it to be grey.

## Actual Result
It is blue.

## Screenshots or Videos
<img width="364" alt="Screen Shot 2021-02-27 at 6 07 11 PM" src="https://user-images.githubusercontent.com/5354501/109402776-a04c3880-7926-11eb-951b-9ddfebad32d0.png">

## Environment

- Operating system: Mac OS Catalina
- Browser: Safari Version 14.0.3 
- Build Version: Version 1.24.5 (513)

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
