### ISSUE TITLE
Website not responsive

### ISSUE THREAD

**Issue by probablykasper** [bitwarden/browser#1651]
If you resize the website to under 1000px wide, the website doesn't resize to fit.

Edit dialogs aren't responsive either, if you try resizing the window under 800px wide.

The edit dialog is also pretty tall. The Custom Fields dropdown could be removed somehow. The "CUSTOM FIELDS" title could be normal bold text like the other titles, and the "Name" and "Value" titles could be placeholders instead.

## Environment

- Operating system: macOS 10.14.6
- Browser: Brave 1.20.110

**Comment by cscharf** [comment]
Thanks @probablykasper ,

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
