### ISSUE TITLE
Edge Extension locks vault even when timeout set to Never

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/browser#1677]
## Describe the Bug

Even When we set the timeout to Never,  Extension on Edge is still locked when we restarted the browser.

## Steps To Reproduce

1. Set extension timeout to never
2. Close browser
3. Start browser

## Expected Result

Vault remains unlocked

## Actual Result

Vault is locked

## Environment

- Operating system: Windows 10
- Browser: Edge

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by sso-bitwarden** [comment]
The user who reported this found the root cause. 
This issue only happened when we install the extension from Chrome web store. The issue will be fixed if we install the extension from Microsoft store instead.
