### ISSUE TITLE
Bitwarden biometric login not prompting confirmation from desktop app. 

### ISSUE THREAD

**Issue by ravinduks** [bitwarden/browser#1680]
## Steps To Reproduce

1. Go to '.the extension.'
2. Click on 'settings
3. Scroll down to 'Unlock with biometrics'
4. Click on 'the checkbox. '

## Expected Result
Biometric access to browser extension allowed. 

## Actual Result
No prompt to enable it on the desktop app. 

## Environment

- Operating system: [Windows 10]
- Browser: [Chrome 89.0.4389.82]
- Build Version (1.48.1)

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
