### ISSUE TITLE
Allow custom fields to hold a reference to the username/password of the login item

### ISSUE THREAD

**Issue by undermark5** [bitwarden/browser#1683]
As mentioned by [this comment](https://github.com/bitwarden/browser/issues/1621#issuecomment-786749492_) an easy way to handle websites that have unusually named credential fields or aren't properly found for whatever reason is to utilize the custom fields. This is great, except that I don't see any way of the custom fields referring back to the actual credentials of the item stored in the vault, which means that if I need to use a custom field for a password, I need to remember to also update the custom field if the password ever needs to be changed for whatever reason. It is my opinion that having to remember to change such values of a custom field should not have to be done by the user, and defeats one of the conveniences of using a password manager like Bitwarden.

If this functionality already exists, it does not appear to be well documented, and if it does not exist, this is a feature request for it. 

User story:
As a user, I would like the ability to reference any of the named items on the vault item via some sort of escape sequence (e.g. `%password%`, `%username%`) or some other method (e.g. a property of the custom field that I can select saying it is the same value as another entry)

Here is the existing [feature request](https://community.bitwarden.com/t/custom-field-variables-for-username-and-password/8389/8) on the community forums

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
