### ISSUE TITLE
Can't use browser extension for the new send feature with a file.

### ISSUE THREAD

**Issue by jebeaudet** [bitwarden/browser#1688]
## Describe the Bug

Can't use browser extension for the new send feature with a file.

## Steps To Reproduce
1. Open web extension
2. Click on Send
3. Click on + to create a new send
4. Click the "Choose file" button
5. The extension window closes with the prompt to choose a file, dismissing the send you're trying to configure!

## Expected Result

We should be able to send a file with the chrome extension.

## Screenshots or Videos
![Peek 2021-03-12 09-38](https://user-images.githubusercontent.com/3722096/110955305-7546e900-8317-11eb-9c2a-dce8e141a34b.gif)

## Environment

- Operating system: Ubuntu 18.04 with Cinnamon
- Browser: Chrome Version 89.0.4389.82 (Official Build) (64-bit)
- Build Version : Version: 1.49.0

**Comment by cscharf** [comment]
@jebeaudet , we certainly experienced this issue with Firefox, which is why the experience is very different in popping out the file upload page into a new tab from the pop-up because we can't control that behavior, most no one on the team has experienced that with a Chromium based browser; but perhaps because we haven't tested it on Ubuntu.

Are you able to upload a file as an attachment to a vault item? That would/should suffer the same issue if it's what I think it is, otherwise if it's only Send something else... Please let us know either way.

cc: @clayadams5226

**Comment by jebeaudet** [comment]
Thanks for answering @cscharf!

I just tried attaching a random file to a secure note and I get the popup you mentioned and I succesfully manage to attach a file to the note. It's not the same behavior with the Send feature, I don't get the popup you mention, I get the baked in file chooser from Chrome.

I'd be happy to test a custom version if it can help you out.

**Comment by cscharf** [comment]
Thanks, our QA team is taking a look

**Comment by kapitainsky** [comment]
works with Firefox on macOS. But it is a bit clumsy end user experience - wouldn't it work better as new tab? The same way like Firefox preferences are handled nowadays?
