### ISSUE TITLE
Bitwarden firefox extension broken since latest update for Waterfox Classic 2021.02

### ISSUE THREAD

**Issue by SpiritBob** [bitwarden/browser#1689]
[Waterfox 2021.02](https://www.waterfox.net/blog/waterfox-2021.02-release/) fails to launch the newest version of the bitwarden extension. Upon opening it, you just see a snaking circle spinning endlessly.

If you need any more details let me know.

**Comment by nemo-xs** [comment]
I confirm.
The same situation on IceDragon, latest release.

**Comment by pringleprng** [comment]
Having the same issue.

**Comment by Hinton** [comment]
Due to the large number of browsers we cannot provide official support to each and every version of browsers. In this case t seems Waterfox Classic is based upon Firefox 56, which is 4 years old at this time, and lacks many of the required APIs for Bitwarden to function.

We officially provide support for the two most recent versions of Google Chrome, Mozilla Firefox, Opera, Microsoft Edge, and Safari. For Vivaldi, Brave, and Tor, only the most recent version is supported. https://bitwarden.com/help/article/getting-started-browserext/
