### ISSUE TITLE
Safari Extension locking up custom mouse profile (Logitech MX Master using LogiOptions)

### ISSUE THREAD

**Issue by peetakim** [bitwarden/browser#1697]
## Describe the Bug

 When the vault is unlocked and subsequently locked after use, custom mouse profile stops working. Still able to right and left click and move the cursor, but unable to scroll (changed from default of natural scroll direction to standard) or use custom misc buttons (i.e., volume control, mission control, page forward/back)

## Steps To Reproduce

1. Be using MX Master mouse and Logi Options (unconfirmed for other mice/programs)
2. Launch Safari and unlock vault
3. Manually lock vault

## Expected Result

 Vault is locked and all mouse functions work

## Actual Result

 Vault locks successfully but after a short period of time (30 seconds or so), only the right and left click function and cursor movement works. All other custom functions of the mouse stops working.

## Environment

- Operating system: MacOS 11.2.3
- Browser: Safari 14.0.3 (16610.4.3.1.7)
- Build Version: BitWarden 1.25.0 (516)

## Additional Context

 This issue only happens when the Vault is manually locked through the Safari extension. <strike>Does not occur when Vault automatically locks after time out</strike> Upon further investigation the vault automatically locking does cause the mouse lockup as well. Problem persists across the system, and is not localized just to Safari. Mouse will continue to function normally if the vault is unlocked again and either remains unlocked <strike>or locks itself after timing out</strike>, or if Safari is exited (using command + q). Have tried uninstalling and reinstalling BitWarden, uninstalling and reinstalling LogiOptions, rebooting the computer, and 'forgetting' the mouse from bluetooth and reconnecting.

**Comment by mportune-bw** [comment]
I experience this as well with a MX Master 3 using Chrome and the web vault automatically locks in a tab _somewhere_.  The problem goes away once I find the vault tab and click outside of the password/PIN field to remove focus.  

@cscharf @vincentsalucci  I'm not sure where the blame lies on this one because I'm pretty sure I've experienced it with some other site where a timeout occurred and it focused on the password field for me.  However since our web vault and/or plugin is always front and center it's usually the trigger - might be worth revisiting whether auto-focus on vault lock (manual or automatic) is really necessary.
