### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by nehalvpatel** [bitwarden/browser#17]
Something to look into. Safari has a lot of the same APIs that Chrome offers, they're just named or implemented differently.

https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/SafariExtensionsConversionGuide/Chapters/Chrome.html

The options would be:
1. We can use `if` statements to use different APIs by detecting which browser the extension is running on. This is what I've done in my own projects.
2. Or we can make some sort of polyfill for the chrome.\* object and implement Safari APIs that way.

Thoughts?

**Comment by kspearrin** [comment]
Supporting Safari would be great. If someone is familiar with the Safari API I would love to work with them to get this done. The polyfill sounds like the best option to me.

**Comment by MojoJojo** [comment]
Not sure if anyone is looking at FireFox/Safari/IE extensions.if not, then I'd love to take it up.

**Comment by kspearrin** [comment]
The extension is built using the chrome web extension api, which is supported already today by Chrome, Firefox, Opera, and Edge. So no work is needed there. The extensions are going through a review process already to be made available on these browsers. The only major browser that does not support web extension API is Safari, which is what this ticket is meant for. If you would like to help with adding Safari support, that'd be great.

**Comment by MojoJojo** [comment]
Thanks for the clarification. Would be happy to assist with the Safari Plugin.

**Comment by SpoonBytes** [comment]
Not sure if MojoJojo is working on this, but I will take a look into getting a working version for Safari. I do not have any experience with browser extensions so it may be some time, but I'll learn and do what I can.

**Comment by chrislaing** [comment]
Could anyone involved with this give a short update on progress on this issue?

**Comment by kspearrin** [comment]
@chrislaing There has not been any progress as far as I know due to other priorities.

**Comment by SpoonBytes** [comment]
Any news regarding a Safari extension? I have been waiting to make Safari my primary browser and this is the last thing holding me back!

**Comment by kspearrin** [comment]
@SpoonBytes Sorry, no news :(

**Comment by sysread** [comment]
I am quite interested in a plugin for Safari on desktop. Any chance of this getting dev attention?

**Comment by mdalpi** [comment]
I'm waiting for this too, meanwhile maybe this can be helpful: https://github.com/mozilla/webextension-polyfill

**Comment by Mattel88** [comment]
Any info when it will be released?

**Comment by eapen** [comment]
I took a look at this and there is quite a bit of work involved to do this - so I ended up making FF my primary browser. :-(

**Comment by MojoJojo** [comment]
Anyone willing to sponsor on Upwork or any other platform? I can tackle it sometime next week.

**Comment by sysread** [comment]
What scale of sponsorship are we talking about?

Jeff Ober

Old programmers don't die; they just parse on...

**Comment by kspearrin** [comment]
If people want to sponsor @MojoJojo working on a Safari port that is fine. We will be glad to review any work done, but please note that @MojoJojo is not affiliated with the bitwarden team in any way.

**Comment by sysread** [comment]
@kspearrin Thank you for the clarification. Any sponsorship (from me, anyway) would be predicated on the assumption of review by the bitwarden team as well as an OSS/public/commons/whatever license to ensure the possibility of community review and improvements (it is dealing with our most sensitive information, after all).

**Comment by Mattel88** [comment]
Would love to see it on Safari. I got all my bookmarks there and it synches best with iOS device which I only use.

**Comment by eapen** [comment]
I don't think desktop Safari extensions work on iOS devices. However, the existing bitwarden app for iOS works with Safari already.

**Comment by praveenperera** [comment]
Any updates this? I was about to switch from lastpass today but I mostly use safari.

**Comment by simplenotezy** [comment]
Would love to see Safari supported. Was actually surprised that it is not working with Safari already.

**Comment by carlo** [comment]
Please add Safari support. I can't leave 90% of my organisation behind in terms of browser support.

**Comment by GeorgeNance** [comment]
Please bring Safari support. I will have to switch to 1password if it doesn't get support.

**Comment by kolanos** [comment]
Was switching from LastPass, too. A Safari extension is a must have for me.

**Comment by Duartemartins** [comment]
Plis - use it very occasionally but it becomes a pain to use Safari without it.

**Comment by chessgriffin** [comment]
Please add support for a Safari extension.  Thanks.

**Comment by dustindauncey** [comment]
+1 for Safari support.

**Comment by nribault** [comment]
+1 too

**Comment by linuxtm** [comment]
+1 for Safari extension

**Comment by luxio** [comment]
+1

**Comment by MojoJojo** [comment]
HI,

I've created a bounty for this on boutysource: https://www.bountysource.com/issues/38267513-safari-extension
I will pick this up after the holidays in January and aiming to raise about 4K to cover my expenses for a month. 
Look forward to your kind donations 🙏

**Comment by frickenate** [comment]
Having a third party developer throw together a Safari extension feels wrong. It might seem better than nothing, but keep in mind that bitwarden is in constant active development. New updates will be released in sync on every other platform, while Safari will be lagging behind until an external party gets around to pushing an equivalent update. Creating a Safari extension is not a one-time, one-month project. It will require constant attention, every couple of weeks.

Without trying to be a dick about it, some people are in fact paying a little money for bitwarden - probably too few of us, and perhaps paying too little? If a Safari extension is worth doing, it should be coming from the official source - in a way that is guaranteed to work identically to the other platforms. It's fantastic that bitwarden is open source, but considering the security implications of a password manager, it's necessary to caution users that opening their vault up to third-party applications poses additional risks. Even if bitwarden audits the initial release, they cannot possibly provide any guarantee that every update to that extension will be reviewed before it gets pushed to users.

Being open source, nobody can actually stop a third party developer from creating unofficial applications. And that's technically a great thing! The fact remains, however, that a password manager is an extremely serious product - to the point where trusting the official company is frankly terrifying enough. ;)

**Comment by jacotec** [comment]
I've switched from Enpass to Bitwarden today as I love the ability to host it locally. Purchased the family subscription to support. Great project, but we're using Safari on our MacBooks ... so a big fat "+1" for the Safari extension.

From my opinion I support @frickenate - it should come from the Bitwarden team. There are too many projects with 3rd party plugins and/or extensions outside which stopped working at some point due to a mismatch of the core and the extensions.

**Comment by kspearrin** [comment]
Just a update here: We've been slowly refactoring parts of the codebase over the past several months to make Safari support more possible. It is on the TODO list for 2018.

**Comment by kspearrin** [comment]
I stared messing with this today and was actually able to get the extension interface loading in Safari where I could log in, browse my vault, add and edit items my vault, etc. There's much more to do but that's a significant step forward.

**Comment by kspearrin** [comment]
Good news everyone. **It's ready!** 🍾 

Before we go live I would like to run a quick beta test here for those that are interested in helping test.

## Download It

You can download the current Safari extension beta here: https://bitwardentestp9vwtmm7.blob.core.windows.net/misc/bitwarden-beta.safariextz

When it has finished downloading just double click it and it should install.

## Feedback

Please post and feedback or bug reports here in this thread so they can be addressed. We may follow up with updated beta version to address any bugs. I will post here if/when that happens. The beta extension will not auto-update since it is not in the official Safari gallery yet.

## Features Missing

A could of things worth noting about the Safari version vs. others (Chrome, Firefox, etc):

- There are no right-click context menu options for bitwarden.
- There are no keyboard shortcuts available (autofill, open popup, generate password, etc).
- The toolbar icon is static. It does not change with the a lock icon, number of logins for the webpage you are on, etc.

These features are not available because Safari does not provide the APIs needed in order to implement them like other web browsers do.

----

Thanks for helping. Hopefully this will be officially released soon!

**Comment by shila77** [comment]
Saw this an hour ago. As far as I tested everything is working as expected.

Thank you very much. I think this is the thing a lot of user (including me) have waited for!

**Comment by dustindauncey** [comment]
Is it true that there are no keyboard shortcuts because of a Safari limitation? I know that the 1Password Safari extension has a keyboard shortcut to activate the auto-fill, so was just curious if that was because 1Password also has an agent running on the desktop or if it was taking advantage of something in Safari which we just don't know yet?

**Comment by BooBerry** [comment]
> The toolbar icon is static. It does not change with the a lock icon, number of logins for the webpage you are on, etc.

Huh, there has to be a way to do at least the number of logins, as I see Tampermonkey displaying a number when injecting userscripts on a website. Adblockers like uBlock Origin and AdGuard Adblocker display the numbers of ads blocked in the icon too.

As for further feedback, the bitwarden Safari extension lacks an icon under Safari's Preferences > Extensions section. Other extensions have icons associated with them, whereas the bitwarden extension doesn't.

**Comment by kspearrin** [comment]
@BooBerry 

1. There is a way to change the icon, but we havent figured out how it scales when doing so. For example, these are our two icons for lock/unlock:

![icon18_safari 2x](https://user-images.githubusercontent.com/1190944/35044653-3840b3e4-fb5f-11e7-9f4f-f5f0716e915b.png)
![icon18_safari_locked 2x](https://user-images.githubusercontent.com/1190944/35044654-38531674-fb5f-11e7-8678-7176eee5936a.png)

They are the same size, yet when we change them they end up scaling differently and it looks odd....

2. We have fixed the icon you mentioned for next version.

3. Safari only allows you to add context menu options at the top level menu. They are not nestable like in other browsers.

**Comment by kspearrin** [comment]
@dustindauncey Likely coming from their desktop app communicating with the extension. Though there may be a way for us to inject a content script into the current website that will listen for shortcuts via Javascript and then communicate them back to the extension. Though this would only work while you are focused on that webpage which should always be the case when autofilling I guess.

**Comment by kspearrin** [comment]
As described above I was able to add a workaround to get limited support for keyboard shortcuts through an injected content script. Currently support will exist for:

- Autofill - This is currently set to `Command + Shift + L` (like the other browsers) but this seems to conflict with an existing safari shortcut to open the history sidebar. Suggestions on another mapping for this?
- Open popup - `Command + Shift + Y`

Not supported:

- The generate password shortcut cannot be supported since safari does not allow access to the clipboard without direct user interaction, which this does not classify as.

**Comment by kspearrin** [comment]
For autofill, it seems 1Password uses `Command + \` so I have changed it to that for now.

**Comment by kspearrin** [comment]
All: Updated beta version is now available here: https://bitwardentestp9vwtmm7.blob.core.windows.net/misc/bitwarden-beta2.safariextz

Uninstall old version (beta1) before installing beta2. 

Updates:

- Added extension icon
- Added keyboard shortcuts for autofill (`Command + \`) and open popup (`Command + Shift + Y`).
- Small bug fixes

Let me know how the new shortcuts are working for you.

**Comment by cassianoleal** [comment]
Hi, I found a small issue with the latest beta.

I've imported a bunch of logins using the web vault but they wouldn't appear on the extension. After I restarted safari, they were there.

I waited about 5 minutes before quitting the browser.

**Comment by kspearrin** [comment]
@cassianoleal The extension wont instantly sync. This is the case with all browsers. It syncs automatically every 6 hours or you can manually sync from Settings -> Sync. A Sync will also happen when it is first opened.

**Comment by JanJastrow** [comment]
Meta-Question: Is there already a repo for the source of the safari extension?

**Comment by peterkeanu** [comment]
I have Duo as a 2 step login verification and it won't get pass that(send a push or code text), it will just stay on "logging you in..."Any ideas why?

**Comment by yatesco** [comment]
Installed perfectly for me on macOS using Authy as the 2FA.

**Comment by kspearrin** [comment]
All: Updated beta version (beta3) is now available here: https://bitwardentestp9vwtmm7.blob.core.windows.net/misc/bitwarden-beta3.safariextz

Uninstall old version (beta1 or beta2) before installing beta3.

Updates:

- Added support for Duo 2FA. Flow for this is different than other browsers since Safari does not allow iframes in the popup. 😕 
- Fixed issue where "open popup" shortcut would open the popup in a different window than the active one.
- Fixes error on 2FA "pick another method" page.

@peterkeanu Can you please test the new Duo flow and let me know if you have any issues now?

**Comment by peterkeanu** [comment]
The added support for Duo 2FA works now. Thanks for the update

**Comment by kspearrin** [comment]
The beta is now over. You can download the official release of bitwarden for safari from our website homepage. You should manually uninstall the beta version before doing so. Future updates should be automatic. We have also submitted the extension to the Safari Extension Gallery and are awaiting approval from Apple to be distributed there. We will post a blog post when that happens.

Thanks for the feedback all.

**Comment by x4vl** [comment]
Here is the link to the Safari Extension Gallery:

https://safari-extensions.apple.com/details/?id=com.bitwarden.safari-LTZ2PFU5D6

**Comment by StoppingBuck** [comment]
I think an update to Safari has broken the extension discovery. The link by @xavi-dev above just links to a special Extensions gallery in MacOS Mojave, and Bitwarden does not seem to be among the listed extensions :/

**Comment by xavi-dev** [comment]
@stoppingbuck you need the Bitwarden mac app with the new Safari

**Comment by Alex0007** [comment]
<img width="154" alt="image" src="https://user-images.githubusercontent.com/1143226/66757646-019c7480-eeb6-11e9-885a-4a8761ae1c88.png">

I'm the only one who thinks that extension icon doesn't match style of other safari icons? 🤔
