### ISSUE TITLE
Shortcut ignored if vault is locked

### ISSUE THREAD

**Issue by fooflington** [bitwarden/browser#1701]
## Describe the Bug
If the vault is locked then the shortcut does nothing rather than prompting to unlock.

## Steps To Reproduce
Vault in "locked" (waiting for PIN) state, press auto-fill key combo.

## Expected Result
Plugin should awaken and prompt to unlock

## Actual Result
Nothing happens

## Environment

- Operating system: macOS 10.15.7
- Browser: Firefox 86 (64 bit)
- Build Version: 1.49.0

**Comment by kendratodd** [comment]
Hi @fooflington! We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

I do see a similar request in our community forums over [here](https://community.bitwarden.com/t/autofill-shortcut-should-open-login-window-when-vault-is-locked/1494). Please feel free to [sign up](https://community.bitwarden.com/signup) and add your vote for this feature (and any others!) or contribute to any discussions about it, so that it can be properly tracked.

This issue will now be closed. Thanks!
