### ISSUE TITLE
Amex UK not working for months

### ISSUE THREAD

**Issue by thorrrr** [bitwarden/browser#1704]
## Steps To Reproduce
General logging in 

Try to login if you have an account
## Environment

Win 10 Pro 
Chrome

**Comment by eliykat** [comment]
Hi @thorrrr, unfortunately this is not enough information for us to understand or help with your problem.

* If Bitwarden is not autofilling your username or password on this site, we have a single issue set up to help manage these reports: see #1621 
* If Bitwarden is not offering to save your username or password on this site, we also have an issue for that: see #1620 
* For all other issues, please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by thorrrr** [comment]
> 
> 
> 
> 
> ## Describe the Bug
> 
> 
> 
> 
> 
> 
> 
> ## Steps To Reproduce
> 
> General logging in 
> 
> 
> 
> 
> 
> Try to login if you have an account
> 
> ## Expected Result
> 
> 
> 
> 
> 
> 
> 
> ## Actual Result
> 
> 
> 
> 
> 
> 
> 
> ## Screenshots or Videos
> 
> 
> 
> 
> 
> 
> 
> ## Environment
> 
> 
> 
> Win 10 Pro 
> 
> Chrome 
> 
> ## Additional Context
> 
> 
> 
> 
> 
> 

I have sent two support tickets with images and videos and your own support team says it is an error.
I am not paying for a service then spending hours reporting the same error 3 times for the identical issue. Speak to you support team and look at the tickets

**Comment by thorrrr** [comment]
Try looking at my 2 support tickets with images and speaking to your support colleagues.

**Comment by cscharf** [comment]
Thanks @thorrrr , I'll follow up with our customer success team, however if you would like to post the issue here on GitHub, as Thomas mentioned, we need more information and we already have a general issue pinned for reporting these specific types of problems.

Thanks again!

**Comment by thorrrr** [comment]
Chad
There is no more info I can provide
I gave you O/S, Browser, website, and detailed description.
You have 2 support tickets with 5 images.
I am not adding my login details for obvious reasons
What more do you need?




Dale Holden


STARLIGHT COTTAGE, LEYLAND RD,SOUTHPORT, MERSEYSIDE, PR9 0NJ
