### ISSUE TITLE
Chrome extension Timeout

### ISSUE THREAD

**Issue by Visiharanv** [bitwarden/browser#1707]
## Describe the Bug
When you have set your "**Box Time out**" to x min/hours or "**When system is locked**". It behav like it's set to "At restart of the browser". 

Because of this, i have to re-enter master password everytime i have restartet my browser. But if have another browser open, and open a new one, then i should not re-enter master password. 

## Steps To Reproduce

1. Click on Bitwarden chrome extension
2. Click on settings
3. Go to **Box timeout**
4. Set **Box timeout** to "**When system is locked**" or "**4 hours**"
5. Restart your browser and check if you need to re-enter your master password. 

## Expected Result
That i can choose other box timeout options. 

## Actual Result
Don't accept other options than "When restart browser"

## Environment

- Operating system: Windows 10, Build 19042.867
- Browser: Chrome
- Build Version: 1.49.0

**Comment by cho-m** [comment]
This is the intended behavior of current implementation as mentioned in: https://bitwarden.com/help/article/vault-timeout/

Supporting new behavior would be a new feature, and is tracked on https://community.bitwarden.com/

One new feature request is sync'ing login/timeout with Desktop app, which will run in background even when browser is closed:
https://community.bitwarden.com/t/login-to-browser-extensions-when-logging-into-desktop-app-and-vice-versa/1635

Trying to do this in isolation inside browser can result in worse security due to having to retain encryption key on device.

**Comment by eliykat** [comment]
@cho-m has basically covered this, but just to explain more fully: it would be a security risk to let your unencrypted vault remain in memory after the extension has been closed. We dump it out of memory and only keep the encrypted data, which means you have to decrypt using your master password when you open your browser again.
