### ISSUE TITLE
Switching windows closes bitwarden editor 

### ISSUE THREAD

**Issue by brianhatchet** [bitwarden/browser#1720]
## Describe the Bug

As a user coming from LastPass to Bitwarden, I am having some trouble managing my secure information with the browser extension

Using the Firefox extension on Mac Big Sur, when I open and edit a password, the window only stays open while the browser has focus. If I click to another window, say to copy and paste sensitive information in, the window closes and discards all unsaved edits.

## Steps To Reproduce

Open the extension in firefox
Click on View
Click on edit
Add some information
Click off the window

## Expected Result

Depends on the user story, but

It prompts to save.
It saves the changes.
Or
It stays open and retains its state until I come back and can edit/save

## Actual Result
The editor closes and the information is discarded.

## Screenshots or Videos

![bitwarden edit switching windows](https://user-images.githubusercontent.com/13663402/111679010-7d56cb00-87e6-11eb-979a-4a20115b7588.gif)

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Browser: [e.g. Firefox 73.0.1]
- Build Version (go to "Settings" → "About" in the app): [e.g. 1.42.2]

**Comment by brianhatchet** [comment]
My bookmarks in that screen capture reveal I am a giant nerd, but it also shows a small, frustrating edgecase.

I have no idea how much control you have over the window state in browser so this could very well be a Firefox UI update loop that causes this, but I figured it was worth looking into

**Comment by freekvh** [comment]
I am in the process of migrating from KeepassXC (and cleaning my db up in the process) and I thus often copy paste both the Username and Password from one to the other. Doing this via the BW Plugin is pretty frustrating because of the closing and subsequently fully resetting (loosing all entered fields), of the pop-up window.

But when I'm not migrating, sometime I click outside the pop-up window, and the fact that this makes you loose everything you entered can be pretty frustrating.

I'm on Firefox 86, plugin version 1.49.1.

Other than this, I love BW! Keep up the good work!

**Comment by eliykat** [comment]
I believe this behaviour is controlled by the browser - we can't prevent the popup window from closing if the user clicks out of it. The "pop-out" button is provided as a workaround:

![Screen Shot 2021-03-19 at 9 08 06 am](https://user-images.githubusercontent.com/31796059/111709049-aaf94e00-8892-11eb-8ed7-04154fae251b.png)

As an additional step, maybe we could save the state of the popup between opening and closing it. That would be a feature request you could make on our [forums](community.bitwarden.com).

There is already a report for this at #1490, so I'll close this as a duplicate. Please continue discussion there if you have any other suggestions or feedback.
