### ISSUE TITLE
Enhancement: Add fingerprint authentication

### ISSUE THREAD

**Issue by sivin-git** [bitwarden/browser#1723]
Can you add fingerprint authentication in web browser extensions in Edge, Chrome, Firefox, Safari which helps faster for users to login as same as in desktop application.

**Comment by cscharf** [comment]
Hi @sivin-git , this is implemented on Edge and Chrome; as well as Firefox v87+. Safari is next up. Closing this as we normally reserve feature requests for the [Bitwarden Community Forums](https://community.bitwarden.com).

Since this is a feature already implemented (for the most part) or already planned, there's no need to open another thread/issue there.

Please see the help article, [Unlock with Biometrics](https://bitwarden.com/help/article/biometrics/), for more information.
