### ISSUE TITLE
Autofill card expiration is in wrong date format

### ISSUE THREAD

**Issue by kukovecz** [bitwarden/browser#1727]
## Describe the Bug

I have a mastercard saved in the vault, which has an expiration date of let's say 03/2029.
All of the sites I am paying with the card expects the expiration date in "MM/YY" format (e.g. 0329) but the autofill is always writing "2029-03". I am using Chrome.
I think it should either:
* Be "smart" enough to know how should it fill right
* Let me save the fill-format into the vault paired to the saved card

## Steps To Reproduce

1. Save a card to the vault
2. Use chrome browser extension for autofill
3. Click on the bitwarden extension
4. Click on the card
5. The autofill will be in the mentioned undesirable format

## Expected Result

The format of the expiration date on my card should be MM-YY during autofill.

## Actual Result

The format of the expiration date on my card is YYYY-MM during autofill.

## Environment

- Operating system: Windows 10
- Browser: Chrome 
- Build Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by deferred** [comment]
+1 I have this behavior as well using Firefox extension

**Comment by eliykat** [comment]
I'm going to close this in favour of tracking all autofill issues in #1621, per the standard wording below. That issue is broad enough to include incorrectly autofilled CC information. Please submit the Google Form in #1621 and include some example sites that we can use for reproduction and testing. Thanks!

---

Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
