### ISSUE TITLE
search info with only one character!!!

### ISSUE THREAD

**Issue by scriptkitz** [bitwarden/browser#1750]
When I only remembered one character about the password information, I used one character to search, but I used one character to search without any results.

**Comment by eliykat** [comment]
This is currently the expected behaviour - a single character is rarely unique in the context of a user's entire vault, and in the vast majority of cases would not return any useful results. Search will only return results after a minimum of 2 characters.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). This would be considered a feature request.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. (I have seen some discussion already about improving our search.) If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
