### ISSUE TITLE
When Edit and Save Item - An Error Has Occurred. The cipher you are updating is out of date

### ISSUE THREAD

**Issue by ikwyl6** [bitwarden/browser#1766]
## Describe the Bug
When I try to edit and save two different items I cannot save these items after I edit and try to save. The error shows in an orange box at the bottom of this entries edit screen within the web browser extension. The text of the error is:

 "An error has occurred. The cipher you are updating is out of date. Please save your work, sync your vault, and try again."

Only on certain items/entries (2) in BW does this error occur at the bottom of the Edit screen. If I do follow what it says and sync the vault (Settings->Sync->Sync Vault Now) and try to edit and save this same entry again, I just keep getting the same error. The two entries that I have issue with editing and saving are two items that have the same base url (subdomain1.domain.com and subdomain2.domain.com). I can edit and save other entries no problem.

## Steps To Reproduce

1. Click on bitwarden extension button in browser
2. Search for the item you want to edit
3. Click on item
4. Click on Edit button in top right of extension
5. Edit the Name or the NOTES section of this item
6. Hit Save button in the top right of the extension

## Expected Result
- Save item correctly without throwing error

## Actual Result
- Doesn't save and throws errors.

## Environment

- Operating system: Linux Ubuntu 20.4
- Browser: Brave Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)
- Build Version 1.49.1

**Comment by LunchBoxStevieC** [comment]
I'm having this same problem.  After the extension has been running a while.  Only fix is to close the browser and re-open to reload the extension. 

Even if you try to force a sync it says it has completed but changes are not updated.

**Comment by SergeantConfused** [comment]
Hi there,

This happens when the client you're using finds a more up-to-date version of that same vault item in your cloud vault. Please log out of your browser extension, reboot your machine, log back into your browser extension, and let me know if you continue to encounter this.
Also, please make sure you do not have any of those vault items open in Edit-mode in any other Bitwarden client, just to be on the safe side.

I thank you in advance for your understanding and cooperation.

**Comment by ikwyl6** [comment]
A restart of the browser fixed this but when I was getting this error I did not have any other clients open or another client editing one of these two items.

**Comment by aj-bw** [comment]
Thank you for getting in touch! We'd like to assist you further if the issue is continuing. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
