### ISSUE TITLE
Ability to set display name for Send, instead of sending users account email in plain text

### ISSUE THREAD

**Issue by OddHouseGames** [bitwarden/browser#1767]
For example, sync.com lets you choose a display name for the send.

**Comment by eliykat** [comment]
We're adding an option that allows the creator of a Send to hide their email. It should be in the next release.

If you'd like to be able to set a display name as well, you can lodge it as a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
