### ISSUE TITLE
Site access set to "on click" breaks things in Edge and Chrome

### ISSUE THREAD

**Issue by zEdS15B3GCwq** [bitwarden/browser#1777]
In Chrome and Edge (and probably other chromium-based browsers), settings "site access" of an extension to "on click" prevents access to a site's data until the extension's icon is clicked on. This setting creates several issues in BitWarden:

1. (tested in Chrome) Adding a site to the vault manually fails with "fetch error". E.g. I tried to add one of my gmail accounts to the vault, filled in the URI, name, user and pass fields, pressed save -> fail.
2. (tested in Edge) Could not perform the initial login to my existing account after installing the extension.
3. (tested in Chrome) auto-popup to remember new login details doesn't appear, e.g. after logging into a gmail account not stored in the vault.

OS Win10 x64 20H2
Browser: Edge 89.0.774.68 / Chrome 89.0.4389.114
BitWarden v1.49.1

Problems with the "on click" setting have been mentioned in at least one other thread (https://github.com/bitwarden/browser/issues/1612#issuecomment-787692919), but I think it deserves to have a dedicated post.

Basically, the "on click" setting breaks some things. While in Chrome I am able to log into my account and use existing logins, new logins are not added automatically (in at least a couple of sites) and manually adding them doesn't work either. In Edge, first login kept failing until I changed "on click" to "allow on all sites" (wording might be slightly different). Naturally, I did click on the extension's icon to enable it. Changing back to "allow on all sites" fixes all the issues. In Edge, setting to "allow on all sites", logging in to initialise the account, then setting back to "on click" allowed further logins without problems.

This setting also breaks stuff in LastPass, so all might not be BitWarden's fault. Auto-adding a new login to gmail didn't evoke an automatic pop-up to save in LastPass either, until the "on click" setting was changed.

I'm aware that I might be mixing slightly different issues in Edge and Chrome, sorry for the sloppiness, but because these browsers share the same engine, I'm going on the assumption that the site access setting works the same way in both. If some of these issues cannot be confirmed, I can do more thorough testing.

**Comment by cho-m** [comment]
> Problems with the "on click" setting have been mentioned in at least one other thread ([#1612 (comment)](https://github.com/bitwarden/browser/issues/1612#issuecomment-787692919)), but I think it deserves to have a dedicated post.

All the issues you listed are most likely due to the same reason as #1612.
No need to create a duplicate issue.

As a recommendation, next time, you should add comments to existing issue as it reduces logistics overhead of dealing with duplicate bugs (based on personal experience as software engineer).

---

I don't have full details, but I think that by setting **"On Click"**, you have essentially made Chrome/Edge block Bitwarden from being able to communicate with its own servers.

Bitwarden browser extension needs to reach the following sites to login/sync/etc:
- https://identity.bitwarden.com/
- https://api.bitwarden.com/

When you **"Click"** the extension, you provide access to the current site you are on, which is most likely neither of the Bitwarden sites.

So, with click setting on a new install (your Edge issue), it will block entire login.
While on existing install (your Chrome issues), it will operate in "Offline" (read-only) mode.

---

This should all be due to same root cause as other issue relating to CORS.
Someone else can comment if it is possible to do anything about this in the extension itself.

For now, I would recommend whitelisting Bitwarden's servers by using **On Specific Sites** option with the 2 above sites. This should still behave like **On Click** for all other sites.

<img width="664" alt="site-access" src="https://user-images.githubusercontent.com/20700669/114832707-a46fd080-9d83-11eb-92ec-08cd6ad560b4.png">

**Comment by zEdS15B3GCwq** [comment]
> > Problems with the "on click" setting have been mentioned in at least one other thread ([#1612 (comment)](https://github.com/bitwarden/browser/issues/1612#issuecomment-787692919)), but I think it deserves to have a dedicated post.
> 
> All the issues you listed are most likely due to the same reason as #1612.
> No need to create a duplicate issue.

Hi, you're absolutely right, upon checking it another time it's obvious that that thread was about the same thing. Sorry for the duplicate issue. My brain must've short-circuited for a few moments.

**Comment by tonymet** [comment]
> I don't have full details, but I think that by setting **"On Click"**,

@cho-m thank you for helping resolve this issue . i had been trying to sort this for > 1 year.
