### ISSUE TITLE
Auto-fill failing on app.element.io

### ISSUE THREAD

**Issue by magthe** [bitwarden/browser#1795]
## Describe the Bug

Bitwarden consistently fails to insert the password for app.element.io.

## Steps To Reproduce

1. Go to app.element.io
2. Choose to auto-fill your credentials using the context menu.

## Expected Result

Both username and password should be filled in.

## Actual Result

Only the username is filled in

## Environment

- Operating system: Linux
- Browser: Firefox 88.0
- Build Version (go to "Settings" → "About" in the app): 1.49.1

**Comment by sso-bitwarden** [comment]
The team is aware that some sites' login forms aren't been autofilled by our extension. This is something we are actively working on, so if you could please follow this link and complete the form: https://github.com/bitwarden/browser/issues/1621 that would help us a lot.

Thank you for your cooperation and understanding. 

As a workaround, you can use keyboard shortcut or context-menu (right click) to autofill this website

**Comment by magthe** [comment]
Ah, no, it doesn't auto-fill _at all_.

I have automatic auto-fill turned off, so I always use the context menu, and that fails too.

**Comment by kapitainsky** [comment]
app.element.io works for me on Firefox 89 beta - not sure if browser version matters here or different OS (I am on macOS).

But I had similar issues with some other websites after migrating from lastpass and in my case it helped to delete and recreate bitwarden login entries - I never bothered to look into details what was the problem (must be e.g. some extra space somewhere or similar).

**Comment by magthe** [comment]
@kapitainsky what matrix instance do you have your account on, the default, `matrix.org` or another?

**Comment by kapitainsky** [comment]
https://matrix-client.matrix.org

**Comment by kapitainsky** [comment]
Behaves the same regardless if I trigger autofill from right click menu or extension icon:

![Apr-22-2021 16-00-12](https://user-images.githubusercontent.com/15635386/115737342-f3b99080-a383-11eb-96bc-d3fcc16d18ce.gif)

**Comment by magthe** [comment]
https://user-images.githubusercontent.com/327270/115773943-3c3b7300-a3b1-11eb-9c38-e8fabd130d34.mp4

**Comment by cho-m** [comment]
I think when you use a non-default matrix instance, **app.element.io** sets the `disabled` attribute (https://www.w3schools.com/tags/att_input_disabled.asp) on form while doing homeserver discovery (maybe 1-2 seconds).

Bitwarden will probably try to fill the form ASAP. The `disabled` attribute will block form filling and thus leave you with your password unfilled.

The other example of clicking `Auto-fill` button in View mode doesn't touch the `Username`, which avoids the issue of the webpage blocking auto-fill.

---

As already mentioned, you should fill out #1621 so that Bitwarden can identify all variations of autofill issues. This particular issue may require some extra logic to provide retries/timeouts/script-detection/etc.

**Comment by eliykat** [comment]
I'm closing this because we're collating all auto-fill issues under #1621 , as a few people have already mentioned. However, please feel free to continue the discussion here on any workarounds for this specific site. (I'm not familiar with it so I can't make any informed suggestions - [custom fields](https://bitwarden.com/help/article/custom-fields/) can sometimes be a helpful workaround, but that may not be much help here.)

**Comment by magthe** [comment]
@eliykat I did follow the link to the Google form in #1621 and fill in the info to the best of my ability. Is there something more I should do to fully register this auto-fill issue?

**Comment by eliykat** [comment]
Thanks @magthe! That's all you need to do - lots of people have been vocal about this issue so it's definitely on our radar.
