### ISSUE TITLE
Unexpected logout

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [bitwarden/browser#1806]
## Describe the Bug

Few minutes ago I looking to Bitwarden logo in browser which show the number of credentials on page, but before I click on extension entry to fill the credential it changed color from blue to gray and logged out automatically.
I am wonder why it happen?

## Steps To Reproduce

its happen unexpected without any action.

## Environment

- Operating system: Ubuntu 20.04
- Browser: Firefox Developer Edition 89
- Build Version (go to "Settings" → "About" in the app): 1.49.1

**Comment by honestby-dev** [comment]
I also can confirm that. Already happened twice today

OS: Debian 10
Browser: Firefox 87.0 (flatpak)
Build Version: 1.49.1

**Comment by eliykat** [comment]
Hi @AmirHosseinKarimi, have you checked your vault timeout options? This can lock your vault or log you out automatically after a certain period of inactivity. See this article for more information: https://bitwarden.com/help/article/vault-timeout/. If you never want your vault to lock/log out automatically, you can set "Vault Timeout" to "Never".

Please let me know if this fixes your problem.

**Comment by AmirHosseinKarimi** [comment]
Hi @eliykat , Thank you for reply.
It set to lock when browser restart, But the problem is Bitwarden was logged out and I authenticated again, Also it ask for verification code!

**Comment by eliykat** [comment]
Hi @AmirHosseinKarimi, I think we'd need more information to help understand your problem. Can you please contact our customer success team using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. They'll help you try to fix the issue, and if it is a bug they can reproduce, they can reopen this ticket. In the meantime, the issue here will be closed and moved over to our Help Desk. Thanks!
