### ISSUE TITLE
Biometrics not working on Vivaldi on Windows 10

### ISSUE THREAD

**Issue by zany130** [bitwarden/browser#1808]
## Describe the Bug

Biometrics not working on Vivaldi on Windows 10
## Steps To Reproduce

install bitwarden
Install the bitwarden extension on vivaldi
setup with windows hello
enable browser integration on destop bitwarden
try to enable biometrics in chrome extension

## Expected Result

Extension and app sync up and alow me to use my biometrics to open bitwarden on vivaldi
## Actual Result

extension complains that browser integration is not enabled even though it is.
## Environment

- Operating system: [Windows 10 20H2]
- Browser: [Vivaldi] 3.7.2218.58
- Build Version 1.25.1

**Comment by sso-bitwarden** [comment]
Try to enable "Allow access to file URLs" in the Chrome plugin's option,  and re-toggle the "Enable browser Integration" option on our desktop.

**Comment by zany130** [comment]
<img width="960" alt="Screenshot 2021-04-29 130542" src="https://user-images.githubusercontent.com/25832539/116590398-b1480480-a8eb-11eb-9713-8fff7fcf3680.png">
same issue after enabling accses to file URLs in the plugin settings

**Comment by tgreer-bw** [comment]
Is this from the MS Store by chance? Biometrics on Windows actually requires the direct download version.

**Comment by zany130** [comment]
> Is this from the MS Store by chance? Biometrics on Windows actually requires the direct download version.

no I installed form the .exe

**Comment by zany130** [comment]
Has anyone been able to reproduce this issue? I'm still having it

**Comment by eliykat** [comment]
Hi @zany130, as you're experiencing this bug across Firefox and Edge as well, it must be some problem with your Bitwarden installation/configuration rather than just with Vivaldi.

Please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. They'll help you troubleshoot this issue and hopefully fix your install. If I'm wrong and it is a reproducible bug, we'll reopen this thread with the additional info they provide.

You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.

**Comment by zany130** [comment]
I contacted support through email and explained the issue and have not heard back since the last email 2 days ago

**Comment by eliykat** [comment]
Hi @zany130, we've been unable to reproduce the bug, and so working through it with Customer Success will be the best channel to resolve it. I've alerted them to your comment here. If I'm wrong and it is a bug, this thread will be reopened with the additional information gathered during the customer support process.
