### ISSUE TITLE
Please don't autofill non-password inputs

### ISSUE THREAD

**Issue by DileSoft** [bitwarden/browser#1809]
If autofill is on, it sometimes autofill inputs with type=text, not password.

**Comment by Greenderella** [comment]
Hi @DileSoft . You may just need to create a custom field for that kind of pages where autofill it's not accurate. Please see this helpful article for more information: https://help.bitwarden.com/article/custom-fields/

**Comment by SZemanek** [comment]
it would be nice if the right-click context menu had a "fill username" and "fill password" instead of just "auto-fill" options for sites that have annoying login screens.

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
