### ISSUE TITLE
set a folder not to participate in auto-fill & display accounts record stored in witch folder

### ISSUE THREAD

**Issue by darkskygit** [bitwarden/browser#181]
In keepass, I can set a password folder not to participate in auto-fill, hope bitwarden has same feature.
And in the ”label“ tab, when I have multiple accounts will display multiple records, I hope can display the record stored in which folder

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/disable-autofill-on-page-load-option-for-specific-logins/22

This issue will now be closed. Thanks!
