### ISSUE TITLE
Timeout not respected when laptop hibernates

### ISSUE THREAD

**Issue by ianmperryman** [bitwarden/browser#1811]
## Describe the Bug
The password database was not locked when the laptop slept then hibernated.

## Steps To Reproduce
Not sure how this happened, 
Bitwarden timeout is set to 30 min, action is set to Lock

Windows power setting send laptop to sleep also after 30 min

Laptop left overnight and hibernated from sleep.

When laptop "woken up" bitwarden vault was still unlocked.

## Expected Result

Expected vault to be locked after hibernation

## Actual Result

Vault is not locked

## Environment

- Operating system: Win10
Edition	Windows 10 Pro
Version	20H2
Installed on	‎10/‎4/‎2020
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

- Browser: Chrome: Version 90.0.4430.93 (Official Build) (64-bit)
- Build Version Bitwarden 1.49.1

## Additional Context

I did not see a setting that allowed me to lock the (browser) vault on system sleep/hibernate.

**Comment by BloodyIron** [comment]
Yeah I'm seeing this regularly on my work laptop (Ubuntu 20.04) with Google Chrome (latest version). I don't know if it's related to sleep, but it probably is. Many times I log back in the next day and my Bitwarden browser plugin, in Chrome, still lets me use content without asking for my password, yet we have forced policy for lock timeout for plugins and otherwise.

This is a tangible security issue here, and we need to have this tied to a milestone @cscharf please take a look into this (if you need me to E-Mail more details or whatever, LMK). I have seen this behaviour over weeks/months, unsure if this has always been like this, or a regression. But this is active as of this writing.

**Comment by cscharf** [comment]
This is in our internal tracker waiting for recreation / action from our QA team.

**Comment by ianmperryman** [comment]
I have not experienced this behavior lately.  I am now more careful when I "pop out" the password manager extension in Chrome. Now I always close the popped out window.  I think perhaps the issue was that I left the popped out window open.  

I think I would like the popped out window to have  a timeout as well, and definitely closed on sleep or hibernate.

**Comment by BloodyIron** [comment]
> This is in our internal tracker waiting for recreation / action from our QA team.

Yay! If there's anything we can do to help pls LMK here or E-Mail. Thanks for looking into this!

**Comment by BloodyIron** [comment]
@cscharf should this be retested? I haven't tested recently.

**Comment by dwbit** [comment]
Hey @BloodyIron, thanks for checking in! We will run some QA on this one and get back to you.

**Comment by Larry-Sussman** [comment]
Our QA team ran through testing this issue on Windows and Mac and we were unable to reproduce this issue with the browser extension "closed."  I believe the extension needs to be "closed" (meaning only the badge is shown) for the vault timeout to take effect. If the extension is popped out like @ianmperryman mentioned, it is considered "open" (in use) and won't be affected by a vault timeout action. 
Because of this, I'm going to close this issue report, but please don't hesitate to let us know if you run into any other issues!

**Comment by ianmperryman** [comment]
Thank you for the efforts.  I now know to close the pop out window to ensure proper timeouts.

I guess that is a feature.
