### ISSUE TITLE
Unable to unlock Brave Extension after pc crash, have to logout/login.

### ISSUE THREAD

**Issue by felixvalin** [bitwarden/browser#1819]
## Describe the Bug

This happened on my work pc (remote). It froze at the end of the work day, and the next morning I had to ask for a reboot (this might be a cause for the issue). When I relogged onto it, and tried "unlocking" bitwarden, it kept saying my master password was wrong even when I had just entered it on the desktop version. What seems to have worked was to logout/login from bitwarden and that fixed the issue. 

## Steps To Reproduce

There are no clear steps to reproduce this since my PC crashed last night, and I'm not sure if that is the reason why this bug happened.  But basically, I restarted the pc, opened my browser, tried unlocking the extension with my master password. This gave me the "wrong master password" error. 

## Expected Result

I expected my master password to work! Or the extension to log me out automatically if that was necessary.

## Actual Result

I had to manually logout myself since the password didn't work to simply unlock the account.

## Environment

- Operating system: Windows 10 v1909
- Browser: Brave 1.23.75
- Build Version 1.49.1

**Comment by SergeantConfused** [comment]
Hi there,

This is most likely the result of corrupt data due to the freeze and system restart because when you're unlocking the vault, you're only decrypting the data that's present on that device. When you logged out and logged back in, you downloaded a fresh copy of your vault. If you believe something else was the cause of this and you find a way to consistently reproduce it, please be sure to let us know.

Thank you in advance,

**Comment by felixvalin** [comment]
Ah that definitely sounds right. I'll keep an eye out for it if something similar ever happens again! 

And you are very welcome!
