### ISSUE TITLE
Making the generated password hidden

### ISSUE THREAD

**Issue by Gaming-Fan** [bitwarden/browser#1822]
## Describing the enhancement

For more security i suggest to hide the password when is generated (invisible like this ********) on the generator and also from the history of all generated passwords

## Expected Result

Hidden password

**Comment by kendratodd** [comment]
Hi @Gaming-Fan! 

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. This [request](https://community.bitwarden.com/t/hide-do-not-show-the-new-generated-passwords/8690) may be fairly similar to your request - if so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
