### ISSUE TITLE
Popup vault passwords remain unencrypted when locked.

### ISSUE THREAD

**Issue by KenyaAdams** [bitwarden/browser#183]
When the extension is locked, the passwords can still be extracted from the popup vault window.  The usernames are also visible along with the site info.

Tested on Chrome 59.0.3071.115 using Bitwarden 1.13.5

**Steps to reproduce:**
1. Sign into the Bitwarden extension using the master password
2. Click the 'My Vault' button
3. Click the popup button to open Bitwarden in a new window
4. Lock the Bitwarden Extension (timeout, on lock, or lock now)

**Issue:** 
The popup vault displays '[error: cannot decrypt]' when clicking an entry but the user can still access the 'Copy Password' button.  The site and username are also displayed.

Love the product!

**Comment by kspearrin** [comment]
This is because those items are already loaded into memory on that page you have open. I don't really see a way to get around that besides maybe polling to see if locked or something and closing the tab.

Opening the vault into another tab should probably not be left open if you plan for it to lock automatically and be protected.
