### ISSUE TITLE
(Firefox) Extension - How to edit login without going to URL

### ISSUE THREAD

**Issue by webtroter** [bitwarden/browser#1850]
## Describe the Bug

I have a login for example.org . They choose to change and redirect everything to example.com . I now cannot edit my login from the extension, since the view button is replaced by a button to launch the login, sending me to the redirect.

## Steps To Reproduce

Add a login for watchnebula.com

Then try to edit it from the extension.

## Expected Result

I expect to be able to edit logins without having to access the url linked to that login

Maybe an option to not replace the view button by a launch button

## Actual Result

The view button is not accessible

## Comment

If I could view a login from anywhere, that would solve the problem.

And I'm ready to hear a reason for it being the way it is.

**Comment by eliykat** [comment]
Hi @webtroter, you can still view/edit your items in the "My Vault" page of the browser extension by clicking on them. (Not on any of the icons - just on the name of the login.)

We use GitHub issues as a place to track bugs and other development related issues. If you'd like help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
