### ISSUE TITLE
Enhancement Req: Add Identities to context menu menu

### ISSUE THREAD

**Issue by STaRDoGG** [bitwarden/browser#1853]
A quick screenshot of my list of identities available, and the lack of an option to fill forms with them via the context menu:

![image](https://user-images.githubusercontent.com/1524526/118699158-d33ff300-b7d6-11eb-80af-767eebe50832.png)

Would it be possible to include the ability to also fill forms with identities using the context menu?

**Comment by cscharf** [comment]
Thanks for the post @STaRDoGG !

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
