### ISSUE TITLE
bitwarden, can the Chrome plug-in provide the password management drop-down box selection function that comes with the Chrome browser?

### ISSUE THREAD

**Issue by huyifanstar** [bitwarden/browser#1874]
Other functions are good, but my website still has many accounts
Now I need to use shortcut keys to replace my username and password frequently. Can you provide a drop-down box for me to choose?

**Comment by Greenderella** [comment]
Hi @huyifanstar 

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
