### ISSUE TITLE
Issue with "Generator" and "Settings" buttons in italian user interface

### ISSUE THREAD

**Issue by fabriziobagala** [bitwarden/browser#1881]
## Describe the Bug

In the Italian language user interface, the `Generatore` and `Impostazioni` buttons at the bottom are too close together.

## Steps To Reproduce

1. Open Firefox
2. Click on 'Bitwarden icon'

## Expected Result

The `Generatore` and `Impostazioni` buttons must have the right distance between them.

## Actual Result

The `Generatore` and `Impostazioni` buttons are too close together.

## Screenshots or Videos

![immagine](https://user-images.githubusercontent.com/62190484/120920014-e995ec00-c6bc-11eb-9ec3-76bacd8a0109.png)

## Environment

- Operating system: macOS Big Sur 11.4
- Browser: Firefox 89
- Build Version: 1.50.0

## Additional Context

The issue occurs with all web browsers.

**Comment by dario-piotrowicz** [comment]
Actually `La mia cassaforte` really looks terrible, it is too long I would suggest finding an alternative name (maybe just `cassaforte` and dropping the precse one-to-one translation?)

I actually think that if `La mia cassaforte` were shorter than `Generatore` and `Impostazioni` would have more room and their issue could also just get fixed as a side effect in this way.

Also I wanted to mention that `Send` is still in english, not sure why, I mean, if that is in english why not keeping `Scheda` as `Tab` too, etc...?

**Comment by fabriziobagala** [comment]
@dario-piotrowicz I think you are right. Leave just `Cassaforte`, it would be nicer to read and simultaneously improve the space between `Generatore` and `Impostazioni`.

I think `Send` is in English because it is the name of the feature, but it would be better to use the Italian translation `Invia`.

A translation of all features into Italian is important because Bitwarden is a password manager used by many Italians and not everyone knows English. As you said, one-to-one translation is often not the best solution for the Italian language.

**Comment by eliykat** [comment]
All our translations are done via CrowdIn - there's more information in the [Contributing guide](https://github.com/bitwarden/browser/blob/master/CONTRIBUTING.md), including how you can help improve them.

@fabriziobagala, we rely on translators and native speakers to help improve our translations - if you think they can be improved, please check out the link above and consider signing up to CrowdIn. Your help is appreciated!

@dario-piotrowicz is correct that 'Send' is specifically marked for our translators not to translate, because it is a proper noun.

As this seems to be a translation problem rather than a development bug, I'll close the issue here. Please direct any further discussions about translations to CrowdIn.
