### ISSUE TITLE
bitwarden doesn't match hostname correctly when autofilling

### ISSUE THREAD

**Issue by Spongman** [bitwarden/browser#1884]
## Describe the Bug

I have multiple logins registered in bitwarden for multiple hosts in a single domain. each login has a different account and password associated with it.

for example:
- host1.domain.com
- host2.domain.com
- host3.domain.com
- ...
- host20.domain.com

I have autofill enabled in bitwarden. when I visit a URL on one of those hosts, it always autofills the _last_ login that I used on _any_ of the hosts on that domain.

eg. if I visit host1, and select my host1 bitwarden login, it logs in fine. but if I then visit host2 it autofills the host1 credentials _even though_ there is a login available in bitwarden for host2.

## Expected Result

it should chose the correct login for the host, if available.

## Environment

- Operating system: win10 x64
- Browser: Chrome 90
- Build Version: 1.50.0

**Comment by eliykat** [comment]
Hi @Spongman, this is expected behaviour. The default match detection matches using the base domain only, so it will match to different subdomains. You can change the default match detection in Settings, or change it for each login individually. In your case, I think you want the "Host" option.

There is more information about URI matching here: https://bitwarden.com/help/article/uri-match-detection/.

We use GitHub issues as a place to track bugs and other development related issues. If you'd like more help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.

**Comment by Spongman** [comment]
i would have expected it to automatically match by host if there are logins for multiple hosts defined in a single domain, and match by domain otherwise.

**Comment by waclaw66** [comment]
I have the same problem, Bitwarden autofills login for a random subdomain. If there are multiple logins for the same base domain, the host match should be applied.

**Comment by Spongman** [comment]
yeah, the two behaviors 'domain' and 'host' are insufficient when there are domains where most hosts/subdomains share a single login yet some hosts/subdomains have specific logins. the current scheme is too simplistic.
