### ISSUE TITLE
Start "Unlock with Biometrics" without pressing button first

### ISSUE THREAD

**Issue by rggjan** [bitwarden/browser#1887]
I have unlock with biometrics enabled in the Safari extension, and it is super useful. For maximum security, I have auto-lock enabled after 5 seconds or so.

However, whenever I want to unlock on a new website, I first have to press the Bitwarden icon, wait, press "Unlock with biometrics", and then do the fingerprint reading.

It would be great if it was possible (at least as an option) to automatically start the fingerprint reading when the Bitwarden icon is clicked, making the second click unnecessary...

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by rggjan** [comment]
Will do, sorry :)
