### ISSUE TITLE
Unlock with biometrics cannot be activated in Sidekick browser.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/browser#1971]
## Describe the Bug
When you try to activate 'Unlock with biometrics' inside the Bitwarden browser extension inside the Sidekick browser, you would receive an error stating 'Browser integration is not enabled' while it is enabled and 'Allow access to file URLs' is enabled, as well.

## Steps To Reproduce
1. Install Sidekick browser (https://www.meetsidekick.com/).
2. Install the Bitwarden browser extension inside it from the Chrome Web Store.
3. Log into your Bitwarden account.
4. Try to activate 'Unlock with biometrics'.

## Expected Result
For the feature to become activated.

## Actual Result
At first, you'd grant the 'communicate with cooperating native applications' permission, and then you'd receive the 'Browser integration is not enabled' error message.

## Screenshots or Videos
N/A.

## Environment
- Operating system: macOS 11.5.
- Browser: Sidekick 90.10.12.11435.
- Build Version: 1.51.1.

## Additional Context
N/A.

**Comment by Sviridon** [comment]
I'm really looking forward to the solution, thanks! 😊 🙏

**Comment by amatsus** [comment]
The feature seems to be enabled in 1password. Is it difficult in bitwarden?

https://1password.community/discussion/134450/sidekick-browser-functionality-biometric-login-multiple-1pw-accounts

**Comment by BritAngeles** [comment]
Same issue. Anyone have a solution?

**Comment by iam-thewalrus** [comment]
Same issue.  Update?

**Comment by x-o-r-r-o** [comment]
This issue is still not resolved. I just tried to use it and got the same error and due to that Passkeys are not working also on sidekick browser saved in bitwarden. Instead Enpass Password manager worked perfectly since i am using bitwarden as backup for enpass i think i will stick to the enpass for sidekick and enpass passkeys are also working with sidekick browser. This isssue is raised since 2021 and bitwarden team is not able to resolve it or either ignored it since they think this is useless than i think bitwarden is useless and no point to use an application where requirements are ignored just because they do not use sidekick browser.
