### ISSUE TITLE
Firefox Extension not Autofilling on any webpage [M1 Mac]

### ISSUE THREAD

**Issue by taylrfnt** [bitwarden/browser#2017]
## Describe the Bug

The extension on Firefox 93 does not autofill any saved logins.  The extension will move the cursor to the correct field, but no information will be autofilled.  Several errors show up in the debug console whenever running the extension and clicking on the login to fill.  This issue persists when using secondary click>bitwarden>login.  I just upgraded and was running the same setup on an Intel based Mac a week ago with no issues.  All other extensions are disabled.  Firefox is able to autocomplete saved logins, so this seems to be isolated to the extension (perhaps an issue with virtualized inputs?  I'm not familiar with the error logs to know what the break point is).

## Steps To Reproduce

1. Go to website to log into via Firefox on M1 device.
2. Try to autofill
3. Fail.

## Expected Result

Expected result is autofilled login.

## Actual Result

No login is autofilled.

## Environment

- Operating system: Mac OS Big Sur
- Browser: Firefox 93.0a1 (Nightly) or most current Firefox build.
- Build Version (go to "Settings" → "About" in the app): 1.51.1

**Comment by eliykat** [comment]
Hi @taylrfnt, this is a known issue with FF Nightly: see #2000. The bug has already been fixed in our code, but it's missed the release window for the release this month. There's some discussion in #2000 if you want to load the latest build manually, otherwise you can downgrade Nightly or switch to regular FF in the meantime.
