### ISSUE TITLE
BUG: No auto-submit/login appears in settings

### ISSUE THREAD

**Issue by drduker** [bitwarden/browser#2021]
## Describe the Bug

There is no option to autosubmit or login documented or available which should be there.  That is a bug because this is supposed to automate login to make my life easier and spend more time away from the computer.  Sad day.

## Steps To Reproduce

Settings of entry --> area doesn't seem to be loading for doing js or button clicking for submit/login buttons.

## Expected Result

See the option appear in my settings for auto-submit.

**Comment by djsmith85** [comment]
Hi @drduker thank you for your report. I'm not quite sure what exactly you are requesting, I assume it has to do with the auto-fill functionality. Please have a look here: https://bitwarden.com/help/article/auto-fill-browser/ 

If the provided link helps: Please close this issue
If the provided link does not help, and you encountered a bug: Please provide more details, so we can possible reproduce the issue.
If this is a feature request: Please close this issue and signup to the [Bitwarden Community Forums](https://community.bitwarden.com), this has a dedicated area for submitting, voting for, and discussing feature requests

Kind regards,
Daniel

**Comment by mamema** [comment]
i'm coming here to add to this request. Other browser plugins from roboform for example, act differently. there is an icon near at the login field, which presents the login information in a drop down fashion to select with one click and you  got logged in without an additional press of a button.

bitwarden has only the icon in the plugin extension area. difference here is:
- 1 press to drop down the login possibilities
- 1 press to select the correct one. Login information gets filled out
- 1 press of the login / enter button

this are 3 clicks for one login in contrast to 1 click like the roboform solution

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
