### ISSUE TITLE
Doesn't sort multiple items for the same domain by name

### ISSUE THREAD

**Issue by wpuckering** [bitwarden/browser#2022]
I have multiple logins with different names which appear in the list when on a page with the same domain. They aren't sorted alphabetically (asc or desc) and there doesn't seem to be a way to configure this. They look like they are sorted somewhat in the order I used each last, but alphabetically would be ideal for me, since it would be much easier to find which login I'm looking for with a better level of predictability. I find myself scrolling through many items sometimes looking for a particular login because they are pretty much randomly ordered.

See attached screenshot as an example:

![Capture](https://user-images.githubusercontent.com/3478486/129959124-a804ade0-e922-4e5c-88f8-5e622ab585de.png)

Can we get some sort of option to sort by name any items appearing in the list?

**Comment by djsmith85** [comment]
Hi @wpuckering , thank you for your report.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
