### ISSUE TITLE
Browser ext: settings selections broken in firefox/fedora

### ISSUE THREAD

**Issue by fastbeats** [bitwarden/browser#2030]
## Describe the Bug

Fedora 34/Firefox 91.0. Browser extension does not lock after restart. timeout options not available. locking from settings doesn't work. Vault will not autolock.

## Steps To Reproduce
1. install bitwarden add-on in firefox
2. login through extension
3. attempt to configure vault timeout and timeout action.
4. restart browser. 
5. restart machine.

## Expected Result
Vault timeout settings should be configurable
Vault should lock in a variety of situations. 

## Actual Result
vault does not lock
timeout action and timeout can not be configured.

## Environment

- Operating system: fedora 34
- Browser: firefox 91.0

**Comment by eliykat** [comment]
* Does uninstalling and reinstalling the extension solve the problem?
* What do you mean by "can not be configured"? Do you mean that the settings revert to their defaults, or something else?
* What happens when you try to lock the vault manually? (Settings > Lock Now)
* What timeout and action settings have you tried?
* When the vault is not timing out, can you confirm that you don't have any Bitwarden browser extension windows open? (popup, popout or sidebar)
* What build of the browser extension are you using? (Click Settings > About to get the version number)

**Comment by eliykat** [comment]
Thanks for getting in touch! We'd like to assist you further. Please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. They'll help you troubleshoot this issue. If it's a reproducible bug, I'll reopen this thread with any additional information that Customer Success have gathered.

You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed in the meantime.
