### ISSUE TITLE
Chrome Extension sync failed

### ISSUE THREAD

**Issue by hkbertoson** [bitwarden/browser#2049]
## Describe the Bug
If I open the chrome extension and attempt a sync. It shows 'Sync Failed'

## Steps To Reproduce

1. Go to Chrome Extension
2. Click on Settings
3. Click on Sync

## Expected Result

It should sync. 

## Actual Result

Sync Failed

## Screenshots or Videos

![Screen Shot 2021-09-01 at 8 36 12 AM](https://user-images.githubusercontent.com/44106297/131681096-92bf2990-de80-4ff3-8ff7-c8fa4e7e64b1.png)

## Environment

- Operating system: Mac OS Big Sur 11.5.2
- Browser: https://whatismybrowser.com/w/ELSSTLM
- Build Version: Version: 1.52.1

## Additional Context

Items do also not delete properly from the web extension.

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
