### ISSUE TITLE
Extension popup dismiss when unlock with biometrics on macOS's Firefox

### ISSUE THREAD

**Issue by SukinoSenze** [bitwarden/browser#2055]
## Describe the Bug
Currently, when trying to unlock Bitwarden with biometrics on macOS's Firefox, the extension popup will dismiss. I have to open it again.

## Steps To Reproduce
- Open Firefox on macOS which has the Bitwarden extension installed.
- Open the Bitwarden popup by click on the extension icon or CMD + SHIFT + Y
- Click `Unlock with biometrics`
- BOOM! extension popup dismiss 😢 

## Expected Result
- macOS biometric confirmation screen popup and Bitwarden extension popup also still exist
Noted: this expected behavior can see with Chromium-based browsers like Google Chrome and Brave, they are working correctly.

## Actual Result
- Bitwarden extension popup dismiss instantly after macOS biometric screen come out.

## Screenshots or Videos
https://vimeo.com/598589649

## Environment

- Operating system: macOS Big Sur 11.5.2
- Browser: Firefox 92.0b9
- Build Version: 1.52.1

**Comment by Hinton** [comment]
@SukinoSenze This is unfortunately due to a platform limitation in Firefox. Firefox immediately closes the popup window when it loses focus compared to Chrome where it stays open until another component of the browser receives focus.

However the extension should still unlock in the background after receiving the biometric response.

Going to close this but feel free to re-open it if the extension doesn't unlock.
