### ISSUE TITLE
Password generator does not retain/persist some configuration settings

### ISSUE THREAD

**Issue by ziffusion** [bitwarden/browser#2061]
## Describe the Bug

Password generator does not retain/persist settings for `Minimum Numbers` and `Minimum Special`.

These revert back to the default of 1 after every browser restart.

## Steps To Reproduce

1. Go to Generator and set `Minimum Numbers` and `Minimum Special` to 2.
2. Restart the browser.
3. Go to Generator and check the values for `Minimum Numbers` and `Minimum Special`.

## Expected Result

 `Minimum Numbers` and `Minimum Special` should retain/persist it's setting of 2.

## Actual Result

 `Minimum Numbers` and `Minimum Special` values revert back to the default of 1.

## Screenshots or Videos

N/A

## Environment

- Operating system: Windows 10
- Browser: Firefox 92.0
- Build Version: 1.52.1

## Additional Context

None

**Comment by eliykat** [comment]
We've been unable to reproduce this bug using the instructions you've provided. Please contact our Customer Success team using our contact page, here: https://bitwarden.com/contact. They will help you troubleshoot the problem. If it can be reproduced as a defect, we'll reopen this issue for further attention.

You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
