### ISSUE TITLE
Verification for browser integration is broken

### ISSUE THREAD

**Issue by kapitainsky** [bitwarden/browser#2075]
### Steps To Reproduce

Enable Verification for browser integration in BW application and Unlock with biometrics in BW browser plugin

Start Firefox browser and attempt to unlock plugin. As expected BW application is started  showing passphrases. 

Go to BW app - there is prompt with verification passphrases. Assuming they are the same press approve. Now biometrics verification prompt appears. Press Cancel.

Go back to Firefox browser - this time when trying to unlock plugin it is unlocked immediately with only biometric verification.

### Expected Result

Without verified  browser integration pluging should remain locked.

### Actual Result

Browser integration is established without verification.

### Additional Context

As it works now it is just a gimmick without any security value.

### Operating System

macOS

### Operating System Version

11.6

### Web Browser

Firefox

### Browser Version

93

### Build Version

BW software  1.28.2 (534) and Firefox extension  1.52.1

**Comment by eliykat** [comment]
Hi @kapitainsky, thanks for the report! We've been unable to reproduce this, so we may need more information from you or it may be an issue with your installation. Please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
