### ISSUE TITLE
First time click to unlock is too slow

### ISSUE THREAD

**Issue by enz0nun3s15** [bitwarden/browser#2126]
### Steps To Reproduce

1. Set vault timeout is set to "on System Lock"
2. Lock the system (sleep)
3. Unlock the system 
4. Wait any amount of time (like minutes)
5. Click the extension to unlock the vault
6. The "Verify Master Password" screen takes a lot of time to show up (+10 seconds)

### Expected Result

The "Verify Master Password" screen to render fast in the first time as the next times. 

### Actual Result

First time rendering the screen takes a lot more, usually a little more than 10 seconds. If I click the extension again (even still locked), the loading is at a acceptable speed.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/92552606/137649605-39e21ad5-621b-4801-b792-2f95febf7d17.png)
After clicking, the extension stays like 10 seconds at this loading mode before showing the unlock screen

### Additional Context

Possibly related: https://github.com/bitwarden/browser/issues/668

Linux - Kubuntu 20.04
Chrome 94.0.4606
Bitwarden version 1.53.0

**Comment by eliykat** [comment]
We've been unable to reproduce this bug using the instructions you've provided. Please contact our Customer Success team using our contact page, here: https://bitwarden.com/contact. They will help you troubleshoot the problem. If it can be reproduced as a defect, we'll reopen this issue for further attention.

You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
