### ISSUE TITLE
Browser integration on macOS app has to be toggled off/on if Bitwarden browser extension is reinstalled on Google Chrome

### ISSUE THREAD

**Issue by ghost** [bitwarden/browser#2133]
### Steps To Reproduce

1. Setup browser integration biometrics between Bitwarden app, and Chrome browser extension
2. Remove Bitwarden Chrome extension
3. Install Bitwarden Chrome extension
4. Toggle browser integration biometrics in Bitwarden Chrome extension

### Expected Result

Bitwarden Chrome extension will login with biometrics

### Actual Result

Bitwarden Chrome extension will refuse to login with biometrics until Bitwarden app browser integration is toggled off, then back on, not detecting that actual selection

### Operating System

macOS

### Operating System Version

11.6

### Web Browser

Chrome

### Browser Version

95.0.4638.54

### Build Version

1.53.0

**Comment by aj-bw** [comment]
Thank you for getting in touch! I tested on the versions listed in your description as well as MacOS 12.1, Chrome 97.0.4692.71 and Bitwarden extension 1.55.0 and could not reproduce on either configuration.
 
We'd like to assist you further if you are still experiencing this issue. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
