### ISSUE TITLE
Copy button not working

### ISSUE THREAD

**Issue by Samisafool** [bitwarden/browser#2143]
### Steps To Reproduce

1. Open firefox extension.
2. Open password generator or any login.
3. Click copy
4. Paste anywhere

### Expected Result

It should copy to my clipboard.

### Actual Result

It does not copy to the clipboard.

### Operating System

Linux

### Operating System Version

Fedora KDE 34

### Web Browser

Firefox

### Browser Version

Firefox 93.0

### Build Version

1.53.0

**Comment by eliykat** [comment]
Hi @Samisafool, thank you for the report. We've been unable to reproduce this on Fedora KDE 34, Firefox 93, and Bitwarden 1.53.0. If you're still experiencing this issue, please contact our Customer Success team for help. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
