### ISSUE TITLE
No master password necessary to view contents of a secure note

### ISSUE THREAD

**Issue by michie1** [bitwarden/browser#2149]
### Steps To Reproduce

1. Go to a secure note.
2. Enable master password re-prompt.
3. Hide Bitwarden
4. Open Bitwarden again
5. Go to the same secure note

### Expected Result

A master password re-prompt.

### Actual Result

No master password re-prompt.

I see the re-prompot when I click on edit, but the contents are already visible before that. The behaviour is different compared to https://vault.bitwarden.com, where it's necessary to provide the master password before seeing the contents.

### Additional Context

Version: 1.53.0. (1.54.0 not yet ready to download.)

### Operating System

Linux

### Operating System Version

Ubuntu

### Web Browser

Firefox

### Browser Version

93.0

### Build Version

1.53.0

**Comment by michie1** [comment]
As a user I have two workarounds. Move the contents of a secure note to:
1) a custom field of type hidden.
2) an attachment.

**Comment by Hinton** [comment]
Hi @michie1,

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

I believe https://community.bitwarden.com/t/require-re-prompt-for-entire-item-view-edit-etc/31737 should match your feature request.

This issue will now be closed. Thanks!

**Comment by michie1** [comment]
@Hinton Please reconsider this. I think it's a bug (or actually a security issue), because the web client already has this feature and the browser addon does not work like this.

**Comment by Hinton** [comment]
@michie1 I understand the sentiment, but as this is a change that modifies the existing scope of the function, and is better tracked as a feature request.

The current "Master password re-prompt" requires a confirmation when viewing/copying/editing hidden fields. The web vault behaves slightly different since the view page is also the edit page, therefore confirmation is requested before viewing.
