### ISSUE TITLE
Cannot choose which login to use on a website

### ISSUE THREAD

**Issue by LEOMODE** [bitwarden/browser#2157]
### Steps To Reproduce

4. Click on '...'

### Expected Result

When using Bitwarden on any device on any platform (at least ones I used were Windows/iOS/Mac OS), if you have multiple logins there is no way to choose what you want, instead, you're forced to see whatever that has the lowest alphabetical in order (e.g. if you have 2 logins on a website: aaa@aaa.com and bbb@bbb.com, even though you always want to login as bbb@bbb.com as a priority, you always will see aaa@aaa.com prompt, and you need to manually go into Bitwarden settings and choose bbb@bbb.com to login. 

### Actual Result

When using Bitwarden on any device on any platform (at least ones I used were Windows/iOS/Mac OS), if you have multiple logins there is no way to choose what you want, instead, you're forced to see whatever that has the lowest alphabetical in order (e.g. if you have 2 logins on a website: aaa@aaa.com and bbb@bbb.com, even though you always want to login as bbb@bbb.com as a priority, you always will see aaa@aaa.com prompt, and you need to manually go into Bitwarden settings and choose bbb@bbb.com to login). 

### Operating System

Windows, macOS, iOS

### Web Browser

Chrome, Safari, Microsoft Edge

### Build Version

Latest version as of today

**Comment by clayadams5226** [comment]
hey @LEOMODE, Bitwarden should default to the last used login. Is that what you are seeing? 

If you'd like the option to set your own default that would be a feature request. We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
