### ISSUE TITLE
By default Bitwarden sets user to forget master password.

### ISSUE THREAD

**Issue by gdzien** [bitwarden/browser#2165]
### Steps To Reproduce

0. Get a new job, need to create new vault... 

1. Install BitWarden
2. Create new account
3. Use extension for 3-4 weeks, never being prompted to re-enter password.
4. Forget password
5. BitWarden logs you out after a ~month.
6. Loose access to your company passwords.

### Expected Result

By default user should be prompted to re-login into his extension every 24h or something like that. To make sure user remember password.

### Actual Result

Curent UX is set to make user forget their password.

### Operating System

macOS

### Web Browser

Chrome

### Build Version

1.54.0

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
