### ISSUE TITLE
Linux: extension cannot integrate with desktop app

### ISSUE THREAD

**Issue by timkgh** [bitwarden/browser#2175]
### Steps To Reproduce

Ubuntu 21.10, install BW desktop app and Firefox extension.
Try to enable biometrics/desktop app integration.
The extension keeps saying:
```
Browser integration is not enabled in the Bitwarden Desktop application. Please enable it in the settings within the desktop application.
```
even though it is enabled in the desktop app ...

### Expected Result

Browser/desktop integration and biometrics should work on Linux

### Actual Result

It doesn't work, even though Ubuntu 21.10 supports fingerprint authentication.

### Operating System

Linux

### Operating System Version

Ubuntu 21.10

### Web Browser

Firefox

### Build Version

1.54.0

**Comment by timkgh** [comment]
This seems to be a problem when the desktop app is installed as a Snap on Linux. AppImage seems to work, but not sure it's useful as fingerprint auth is not supported in Linux yet :(

**Comment by eliykat** [comment]
Hi @timkgh , currently we do not support biometrics on Linux. This is a feature request which is being tracked on our Community Forums: https://community.bitwarden.com/t/linux-fingerprint-and-or-biometric-support/16715.

---

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
