### ISSUE TITLE
Autofill keyboard hotkey/shortcut does not work in Safari if non-English keyboard layout selected

### ISSUE THREAD

**Issue by flaksp** [bitwarden/browser#2191]
### Steps To Reproduce

It seems like BitWarden in Safari listens only for <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd> shortcut. But if keyboard layout changed to another language, Russian in my case, it thinks that <kbd>Д</kbd> letter instead of <kbd>L</kbd> is pressed, but physically it's the same key on Russian keyboards.

Much likely this problem is actual for all users who use non-latin layouts often, not only for Russian.

### Expected Result

Behavior should be the same for <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd> and <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>Д</kbd>. The behavior should depend on actual physical keys pressed, not on current user's keyboard layout. 

### Actual Result

On non-latin keyboard layout (Russian in my case) Safari sidebar (with tab groups, reading list) is opened, which is default behavior for <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd> shortcut, as if BitWarden extension wasn't installed. Instead of expected form autofilling it opens me sidebar.

It is very annoying because we use both US English and Russian keyboard layouts all the time and in half of the cases I accidentally open Safari sidebar. To prevent the annoyance, I should look at my keyboard layout first, and only then I can press the combination of keys, but it kills all benefits of having such shortcut - it's faster to fill form from context menu or popup-window.

### Operating System

macOS

### Operating System Version

macOS Monterey, 12.0.1

### Web Browser

Safari

### Browser Version

15.1 (17612.2.9.1.20)

### Build Version

1.54.0

**Comment by eliykat** [comment]
We can only listen for particular key presses based on what the keyboard layout tells us - we have no way of knowing the physical location of a key on the keyboard. However, you can configure what hotkey is used for autofill: https://bitwarden.com/help/article/auto-fill-browser/#configuring-keyboard-shortcuts. If you're frequently changing between keyboard layouts, maybe you can choose a key combination that doesn't move around?

If that doesn't help, then you can make a feature request on our forum for better support in this area, preferably outlining what kind of solution you'd like to see. More information on that below.

---

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
