### ISSUE TITLE
Context menu "Copy verification code" fails on first attempt

### ISSUE THREAD

**Issue by molove** [bitwarden/browser#2196]
### Steps To Reproduce

1. Go to : Paypal with 2FA
2. Click on : Enter email and password, Right click to bring up context menu
3. Scroll down to: Bitwarden>
4. Click on: Copy verification code>Paypal
5. Paste contents of clip board to "Enter Your Code" 

### Expected Result

The verification code to be copied to the clipboard

### Actual Result

 the verification code is not copied to the clipboard on the first attempt, and needs to be copied again for it to work properly

### Operating System

Windows

### Operating System Version

10 Pro 20H2

### Web Browser

Firefox

### Browser Version

94.01

### Build Version

1.54.0

**Comment by eliykat** [comment]
We've been unable to reproduce this bug using the instructions you've provided. Please contact our Customer Success team using our contact page, here: https://bitwarden.com/contact. They will help you troubleshoot the problem. If it can be reproduced as a defect, we'll reopen this issue for further attention.

You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
