### ISSUE TITLE
Secure notes are displayed even though master password re-prompt is required

### ISSUE THREAD

**Issue by szakeetm** [bitwarden/browser#2204]
### Steps To Reproduce

1) Create a secure note with "master password re-prompt" enabled and save
2) Search your vault for the new item and click on it
3) Your secure note will be displayed without master pass re-prompt

### Expected Result

Hide secure note until master password is typed.

### Actual Result

Secure note revealed

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/5345762/143839045-1856c3f1-6b94-4c8d-bc6e-3a79d61acaf2.png)
![image](https://user-images.githubusercontent.com/5345762/143838994-0b668821-d17b-4e1d-a0f5-7eec464d398b.png)

### Additional Context

Same on desktop app, iOs and web

### Operating System

Windows, macOS, Linux, Android, iOS

### Web Browser

Chrome, Brave

### Build Version

1.54.0

**Comment by eliykat** [comment]
This is currently by design; reprompt protection does not apply to the entire item, only to protected fields in the item (e.g. the password). There is a feature request on our forums to change this functionality here: https://community.bitwarden.com/t/require-re-prompt-for-entire-item-view-edit-etc/31737. I recommend you add your vote and voice to that thread. We have received a few requests for this and we are tracking it internally.

---

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

This issue will now be closed. Thanks!
