### ISSUE TITLE
Feedback from a new user

### ISSUE THREAD

**Issue by yatesco** [bitwarden/browser#221]
Hi - so thanks for Bitwarden, I can see it has huge potential. A modern, open-sourced, affordable password manager.

I hope you take this feedback the way it is intended - only as constructive criticism.

I strongly suggest that extracting a 'consumer' orientated UI and a business orientated UI would simplify the consumer one enormously. As a family guy I want the following:
 - a place where I can store passwords local to me
 - a place where I can store passwords local to my wife
 - a place where I can store passwords owned by myself and my wife
repeat for each of the children.

I can achieve this but I have to navigate a bunch of different screens, and create Organisations and then Collections, neither of which are particularly intuitive. I also have "Folders" as well.

The documentation does a good job of explaining this, but it isn't particularly use-case orientated. The documentation answers the question "what does X mean in Bitwarden", I really wanted "how do I achieve X in Bitwarden".

My ideal:
 - the ability to create a "Vault", because a "vault" is where I put sensitive things
 - the ability to tag things in a vault
 - the ability to have magical vaults which contain only those items with certain tags
 - the ability to invite others on a read only/read write basis to have access to a vault
It would be awesome to store files, notes, scans etc. in there as well.

And that's it :-).

A UI which talks about "Vaults", "Sharing" and "Tags" (OK, arguably "tags" aren't as well known as "folders") would have almost no cognitive load.

To be blunt, if it takes me more than 5 minutes to understand how something works, it puts me off. If I have to go searching through documentation then that puts me off even further. If after searching that documentation I am still nowhere close to knowing what to do then I walk away.

I overlooked Bitwarden three times in my search for `LastPass.next()` (I'm a Clojure guy so `(.next LastPass)` ;-). I'm glad I came back

Just my 2cents - keep up the excellent work.

**Comment by kspearrin** [comment]
@yatesco It is true that our sharing features are geared more toward business use in their implementation. This was done purposefully since that is the main use-case for what we built those features for. What you are trying to achieve can be done with the existing implementation, things just probably need to be presented and/or documented better for the average non-business user.

- Collection = vault in your description. We actually originally called these "subvaults" when they were first created. They are like mini-vaults that exist inside of the overall "organization vault".
- Tagging logins to a vault is essentially means associating the login with a collection. A login can exist in one or more collections. A user can be associated with one or more collections. If a user and a vault are associated to the same collection that user gets access to the login.
- You can invite users to the collection with read only access.

Again, all of this can be achieved using our existing implementation, I think you are just getting a bit confused because of a difference in terminology from LastPass and 1Password.

**Comment by yatesco** [comment]
Thanks for the reply @kspearrin.

I did manage to get it all figured out (as you can hopefully see by the various PayPal dollars coming your way :-)).

My point wasn't understanding _how_ the translation happens, it was a suggestion to define a UI so that that translation wasn't necessary. 

I didn't realise that it was many to many between the collections and logins - that's perfect.
