### ISSUE TITLE
Ctrl + Shift + L Doesn't Work on Vivaldi

### ISSUE THREAD

**Issue by Nihal247** [bitwarden/browser#2222]
### Steps To Reproduce

1. Open Vivaldi
2. Make sure Bitwarden is unlocked
3. Go to site which's credentials has been saved
4. Press `Ctrl + Shift + L`

### Expected Result

Credentials should be autofilled

### Actual Result

Credentials are not autofilled

### Operating System

Windows

### Operating System Version

Windows 11 21H2 (22000.348)

### Web Browser

Vivaldi

### Browser Version

5.0.2497.28

### Build Version

1.55.0

**Comment by djsmith85** [comment]
Hi @Nihal247 thank you for your report. 

Unfortunately this is a known upstream issue in Vivaldi. Setting the extension shortcut to `Global` instead of `In Vivaldi` is currently the only known workaround.

See for example here: https://github.com/bitwarden/browser/issues/1212 and the link to the Vivaldi forums.

Closing this now, as this issue will have to solved by the Vivaldi team.
