### ISSUE TITLE
BW extension forgets settings repeatedly

### ISSUE THREAD

**Issue by Stooovie** [bitwarden/browser#2251]
### Steps To Reproduce

Use Bitwarden extension for a while.

### Expected Result

Settings such as Unlock with PIN, Vault Timeout and such are retained.

### Actual Result

Settings such as Unlock with PIN, Vault Timeout and such are reset to default, requiring the user to set them all over again.

### Additional Context

Happening to me on both Windows 10 and MacOS Monterey, on three different computers. I'm unable to 100% tell when this happens, but every few days, all settings get reset, I have to re-enter my master password. It's supremely annoying, to the point of me wanting to ditch BW altogether. It's happening for more than a year now.

All systems, apps and extensions are fully updated.

### Operating System

Windows, macOS, iOS

### Operating System Version

Windows 10, MacOS 12.1, iOS 15.2.

### Web Browser

Safari, Microsoft Edge

### Build Version

BW 1.30.0

**Comment by charma** [comment]
I can 100% approve this bug but my settings are never really saved in the first place. I can "visually" change the settings but they have no effect. Same for me on all OS and newest version installed.
Additionally I have to reenter my master password every(!) single time I close and reopen my browser, no matter what settings I select, even on timeout set to never.
I have this issue from the very beginning since I use bitwarden for many months now.

**Comment by Stooovie** [comment]
Happy to hear I'm not alone. It's not as severe on my system.

**Comment by eliykat** [comment]
All these settings (as well as your logged in state) are saved in the browser's local storage, on your local machine (not sync'd with cloud). We don't do anything to clear this, so there must be something else going on. Do you have any unusual configuration for your browser or OS that could affect local data? Are there any extensions that could be conflicting with it? Could you try another browser and see if you experience the same problem?

**Comment by Stooovie** [comment]
Hi, thank you. Edge does this resetting a lot less than Safari. I'm not aware of any special config I'd have, I certainly don't clear cache/history regularly. It also usually happens after updating of the BW app - is that expected?

**Comment by charma** [comment]
I don't think that this is a local-cache/history issue. I gave up and switched to never timeout so I am always logged in and my login is never lost even after days and weeks.
This is a major security flaw for me because everyone logging into my computer now has access to my bitwarden passwords but for my sanity and comfort I am going this way for now... too bad :(

**Comment by Stooovie** [comment]
My issue is the exact opposite. I want "never timeout" on my home computer but it kept resetting to "on browser restart".

**Comment by eliykat** [comment]
@charma: I don't understand your issue sorry, your first post said that
> I have to reenter my master password every(!) single time I close and reopen my browser, no matter what settings I select, even on timeout set to never

but your update says

> I gave up and switched to never timeout so I am always logged in

The expected behaviour is that your Bitwarden extension will lock when you restart your browser, and that requires your master password to unlock. Some alternatives are:
* use Never lock, as you have (but yes this has some security risks). More info about vault timeout options [here](https://bitwarden.com/help/vault-timeout/#vault-timeout)
* use a [PIN to unlock](https://bitwarden.com/help/unlock-with-pin/) or [biometric unlock](https://bitwarden.com/help/biometrics/), and untick the box that says "require master password on browser restart".

@Stooovie It is not expected/intended that your settings are cleared after each update (or randomly). Safari updates through the desktop app so I could at least imagine that, but Edge should be unrelated and should be a smooth update process.

In both your cases, I can't reproduce this bug, so I recommend contacting our Customer Success team so that they can help you debug it further. More info below. If they are able to reproduce it then I'll reopen this ticket for further investigation. Thanks!

---

Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by charma** [comment]
sorry for the confusion: what I meant in my first post was, that it doesnt matter if my timeout setting is set to "lock" or "logout". I am translating the settings and options from german out of my head here. Dunno what the settings and options are called in the english version.

I have two option fields:
an option to set timeout to some time and "never"
and an option to choose what to do when timeout is reached: lock or logout.

even if is set to "only" lock it keeps logging me out completly.

since this is an issue that I have now experienced on 3 systems with windows, ubuntu and macos (freshly installed os), i guess it is just a bug of the extension and has nothing to do with my personal setup or browser...

For now what works for me (most of the time) is to set timeout to "never" and I stay logged in (most of the time). Just hoping that this bug will be investigated in the future and fixed. Else I may stick to it the unsecure way or switch to a different password manager which works.

**Comment by eliykat** [comment]
@charma Thank you for that explanation, I understand your problem better now. I still think that contacting our Customer Success team is the best way to go, as I haven't been able to reproduce the bug, and they can provide you better 1-on-1 assistance than I can here. Please send them a message here: https://bitwarden.com/contact and include a link to this thread.

**Comment by pinchies** [comment]
If I'm having the exact same issue as described here intermittently on multiple platforms in 2024, should I contact support or post a new issue here?

**Comment by eliykat** [comment]
Hi @pinchies, I think [contacting support](https://bitwarden.com/contact/) is still the best way to go on this one. They can help you troubleshoot it and if they're able to reproduce it then they'll help log it as a bug.
