### ISSUE TITLE
Make generated passphrases stronger by appending a digit to each word, not just one word.

### ISSUE THREAD

**Issue by hdevarajan** [bitwarden/browser#2276]
### Steps To Reproduce

Generate a passphrase with any parameter for the number of words, choosing to "Include Number".  Observe that only one word gets a digit appended. 

### Expected Result

Ideally, a random digit would be appended to each word.

### Actual Result

Observe that only one word gets a digit appended. 

### Additional Context

Appending a random digit, and doing so to each randomly generated word, will increase the entropy of the generated passwords significantly while impacting the memorizability (or human friendliness) of the passwords only marginally.

Passphrases are recommended over passwords for human-friendliness. But as per defaults the entropy increases too slowly with the number of words. Say a user chooses a 3 word passphrase. As a typical word can be assumed to be chosen from a set of ~ 200k English words, the entropy is the same as having only a 11 letter long passwords all in lowercase. (Why? log to the base 26 of <200k to the power 3> is ~ 11).  This under some computing power and hashing algorithm assumptions, can be cracked in "1 day" (see https://www.security.org/how-secure-is-my-password/).  Note that that number goes up only to 3 weeks if capitalizations are allowed, as only the first letter is capitalized in this setting -- quite human friendly, but that implementation again doesn't increase entropy sharply.

Whereas appending a digit to *each* of the 3 randomly generated words will increase the all-lowercase entropy by 3 orders of magnitude. This will increase that "1 day" into the 1 year range, and if the user choose on capitalizations, that will go into the 50+y range which is more secure.

### Operating System

Linux

### Operating System Version

Independent

### Web Browser

Firefox

### Browser Version

Independent

### Build Version

1.54.0

**Comment by djsmith85** [comment]
@hdevarajan Thank you for your feature request.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
