### ISSUE TITLE
Fingerprint

### ISSUE THREAD

**Issue by YouveGotMeowxy** [bitwarden/browser#2374]
### Steps To Reproduce

Click the BW icon.

### Expected Result

See below

### Actual Result

See below

### Additional Context

Very happy to see Windows Hello stuff added to the chrome extension. Probably a dumb question but just wanted to know either way; is it _**necessary**_ to have the BW APP itself open at the same time in order to use the Fingerprint in the extension?

I'd rather be able to use the fingerprint in the extension w/out have  the app itself running at the same time (if possible). I realize that you've probably already though of this, and it may be a limitation of the abilities of an extension, but again, just wanted to throw the question out there.

Unfortunately, if the app is a must in order to use the thumbprint in the extension I (personally) probably will just disable the option in the extension, as I'm a lil bit OCD about always having unnecessary apps always running in the background, eating up resources.

Again, not intended as any sort of complaint; I genuinely appreciate that it was added, and the work the devs put into it. ;)

### Operating System

Windows

### Web Browser

Chrome

### Build Version

latest

**Comment by eliykat** [comment]
Yes, the way it works is that the browser extension communicates with the desktop app, which communicates with the native Windows Hello features. The browser extension (to my knowledge) can't talk to Windows Hello directly, so that's the current solution.

We use GitHub issues as a place to track bugs and other development related issues. If you have any other general questions or feature requests, I recommend heading over to the [Bitwarden Community Forums](https://community.bitwarden.com).

This issue will now be closed. Thanks!
