### ISSUE TITLE
Default Collection no longer available from Chrome Extension

### ISSUE THREAD

**Issue by thebalaa** [bitwarden/browser#2382]
### Steps To Reproduce

I had a single password in a `Default Collection` associated with an organization. Today, I returned to the chrome extension to find it was no longer available / is missing.

### Expected Result

Login item in Default Collection to still exist / be available.

### Actual Result

Can no longer find the Login item in "Default Collection"

### Operating System

macOS, Linux

### Web Browser

Brave

### Build Version

1.56.4

**Comment by eliykat** [comment]
Hi @thebalaa, I can still see my `Default Collection` and its passwords in a fresh install of v 1.56.5. Can you try uninstalling and then installing the latest version, and seeing if the problem persists?

Is the item still available in other clients, e.g. the web vault?

If you're still experiencing the issue, best to contact our Customer Success team using the details below, so that they can help you debug. Thanks!

---
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
