### ISSUE TITLE
Error handling response: TypeError: Cannot read properties of undefined (reading 'settings') and the app won't memorize my password

### ISSUE THREAD

**Issue by Temepest74** [bitwarden/browser#2387]
### Steps To Reproduce

Bug 1:
Install the extension on brave
Go to any website
Open dev tools
Bug 2 (this worked in previous version):
Install the extension
Add you password
Go to setting and set the extension to remember the password forever

### Expected Result

Bug 1:
No errors inside the console
Bug 2:
To never need to enter my password again

### Actual Result

Bug 1:
Your can see the console output in the first image
Bug 2:
It always resets my session on browser restart

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/28103890/154037739-7eda3cd2-ca43-4168-ab11-9943ce71e906.png)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Brave

### Browser Version

98.1.35.101

### Build Version

1.56.5

**Comment by cscharf** [comment]
Hi @Temepest74 , this has been resolved and released with https://github.com/bitwarden/browser/releases/tag/v1.56.6. These should be submitted to extension stores tomorrow AM.

**Comment by cscharf** [comment]
Hi @Temepest74 , generally only 1 issue should be submitted per Github issue, so it can be tracked, fixed and worked 1 by 1, otherwise things get buried and missed. Outside of that, the issue you're experiencing still is already open here, https://github.com/bitwarden/browser/issues/2395 and likely falls into the same context. If you feel the issue you're experiencing is different, please open a new, separate issue.
