### ISSUE TITLE
Fails to login into Microsoft Edge extension

### ISSUE THREAD

**Issue by crisan7** [bitwarden/browser#2401]
### Steps To Reproduce

1. Install extension on Microsoft Edge (latest version, Version 98.0.1108.56 (Official build) (64-bit))
2. Try to login into extension, receive **unexpected error**

### Expected Result

Successfully login.

### Actual Result

Unexpected error

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/82758487/154866062-1804b1d2-e638-4ba4-a22d-d54946c91cb2.png)

### Operating System

Windows

### Web Browser

Microsoft Edge

### Browser Version

Version 98.0.1108.56 (Official build) (64-bit)

### Build Version

1.55.0

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
