### ISSUE TITLE
Put the Logout button at the top and the Unlock button below the password input

### ISSUE THREAD

**Issue by tsunamistonefly** [bitwarden/browser#2415]
### Steps To Reproduce

When logging in, it's easy to mistaken the log out button as the unlock button especially if you use the Bitwarden phone app a lot. In the Android app, for example, the logout button is in the top, inside a ellipsis menu while the "Unlock" button is below the password input.

### Expected Result

A consistent login screen between the phone app and the web extension to avoid the problem described above.

### Actual Result

The logout button is below the password input.

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

97.0

### Build Version

1.56.6

**Comment by Hinton** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by tsunamistonefly** [comment]
> We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.
> 
> Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.
> 
> This issue will now be closed. Thanks!

Should I report this to xwayland or is this a limitation?
