### ISSUE TITLE
Wrong 2FA codes being generated on Windows 11

### ISSUE THREAD

**Issue by vmihokov** [bitwarden/browser#2437]
### Steps To Reproduce

1. Install Windows 11 Pro (Build 22000.527 or 22000.493)
2. Install Bitwarden extension in Microsoft Edge, Firefox, or Google Chrome (I tried all three)
3. Keep default settings in browser and don't install any other extensions to ensure it does not interfere in any way
4. Try to log into any website which requires TOTP that you can generate from Bitwarden

### Expected Result

Successful login

### Actual Result

Wrong TOTP code being generated under Windows 11

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/16282150/157023834-2552dc9c-6c44-48cc-9db2-f4c684c69dab.png)
![image](https://user-images.githubusercontent.com/16282150/157024415-f015e7bf-3288-4bb2-8b45-4917c05d44d9.png)

### Additional Context

The TOTP codes that are generated using the smartphone app or on the Bitwarden website directly are working as expected.
Also everything is working as expected under Linux environment.
Seems like only Windows 11 is affected.

### Operating System

Windows

### Operating System Version

11 Pro 22000.527

### Web Browser

Chrome, Microsoft Edge, Firefox

### Browser Version

latest

### Build Version

99.0.4844.51

**Comment by eliykat** [comment]
This is usually a problem with your device's clock being incorrect. Please contact our Customer Success team using the information below, they can help you debug it. Thanks!

---

Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
