### ISSUE TITLE
Cycle through the logins when using the hotkey

### ISSUE THREAD

**Issue by jmcbee** [bitwarden/browser#248]
I think it would be better to allow the only auto-fill hotkey option "Auto-fill the last used login for the current website." to cycle through your logins for a website ordered by the date it was last used. Right now you can only use the last login you have used; if you have to use another you have to use the context menu or the popup menu.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/cycle-through-multiple-logins-when-auto-filling-with-keyboard-shortcut/34

This issue will now be closed. Thanks!
