### ISSUE TITLE
Firefox extension does not copy to primary X11 clipboard

### ISSUE THREAD

**Issue by fischer-felix** [bitwarden/browser#2501]
### Steps To Reproduce

1. Install Bitwarden on Firefox on Linux (X11)
2. Copy a password, username or TOTP code via the buttons on the "Tab" page
3. Try pasting using the middle mouse button

### Expected Result

Username / password / TOTP code gets copied to both X11 clipboards, PRIMARY as well as CLIPBOARD (see [this article](https://wiki.archlinux.org/title/clipboard#Selections) for more details), so it can be pasted using either ctrl + v or the middle mouse button.

### Actual Result

Copied value can only be pasted using ctrl + v, unlike in chromium based browsers, where both the methods described above work.

### Screenshots or Videos

Turn on Audio!

https://user-images.githubusercontent.com/65448408/163430832-ac4b32b1-a025-4962-8fed-5fa3d99c540d.mp4

### Operating System

Linux

### Operating System Version

Arch Linux latest stable, xorg-server 21.1.3-6

### Web Browser

Firefox

### Browser Version

99.0-1

### Build Version

1.57.0

**Comment by tangowithfoxtrot** [comment]
Hi, @fischer-felix!

Thank you for reporting this! I use Arch Linux as well, and can confirm that this behavior is consistent on my system when using the Firefox extension. 

However, from my understanding of X11, the data copied this way _shouldn't_ actually be middle-click pastable, since the functionality is actually a selection buffer, rather than another clipboard. Since the PRIMARY selection actually needs to be _selected_ by the user's cursor, the fact that it works in the Chrome browser extension is kind of surprising.

Since the copy username, password, TOTP, etc. buttons were made to copy to the user's clipboard, rather than the clipboard + X11 selection buffer, I'd say this would actually be a feature request.

We use GitHub issues as a place to track bugs and other development-related bugs. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

For now, I'd recommend either pasting with Ctrl+V or selecting the text when using the Firefox extension so that it gets stored in the X11 selection buffer and will be middle-click pastable.

This issue will now be closed. Thanks!
