### ISSUE TITLE
LastPass import broke some passwords

### ISSUE THREAD

**Issue by tycho** [bitwarden/browser#268]
Most of my passwords are randomly generated, and a few of them have ampersands in them. Unfortunately, when importing my LastPass CSV, Bitwarden corrupted passwords like "foo&bar" into "foo&amp;bar". So when it fills a form, the website (rightly) rejects it as a bad password.

**Comment by kspearrin** [comment]
This is documented here https://help.bitwarden.com/article/import-from-lastpass/

**Comment by tycho** [comment]
@kspearrin Uhm, wow. Okay.

Why not check if there are any rows with common HTML entities in the password column (e.g. `&amp;`, `&lt;`, `&gt;`, etc) and ask the user whether or not they should be patched up on the fly? Surely that would be better than silently accepting the corrupted data, and letting the user live with that corruption for WEEKS without knowing about it before posting an issue here and finding out that "oh yeah, the weeks of changes you've made to passwords? well, now you don't know which ones are old ones that have surprise corruption in them!"

No, it's not *your fault* that the exported data was corrupt. But it is your fault if you silently and knowingly accept corrupted data when importing. I certainly didn't read the "import data from LastPass" page because the export/import process seems (and should be) so straightforward. Pointing to documentation and saying "nyaa nyaa nyaa, not our problem" isn't really a user friendly answer here.

**Comment by tycho** [comment]
Also, after digging into it, I don't think LastPass is really "corrupting" their export. They're just trying to encode as CSV without losing data. For example, a worst-case scenario password like "`test,password&><"`" gets encoded in CSV as:
```
url,username,password,extra,name,grouping,fav
http://testsite,testuser,"test,password&amp;&gt;&lt;""",,testing 1 2 3,,0
```
They use HTML entities to encode each field, escape the comma by quoting the field, and escape the double-quotes in the password by using two of them (per RFC4180). Does bitwarden correctly handle quoting on fields? I'd be concerned if it just did the equivalent of `line.split(',')` and imported it that way. Hopefully it's just a matter of adding a "please decode HTML entities in each field when importing" option.

**Comment by kspearrin** [comment]
We handle csv according to RFC specs. Papa parse is the library used.

**Comment by tycho** [comment]
Great. So why not add an option for bitwarden to decode the HTML entities?

**Comment by kspearrin** [comment]
What if my password really contained `&amp;`? If we html decode, now we’ve broken the password. This is a lastpass issue. We cannot reliably handle it, which is why it is documented.

**Comment by tycho** [comment]
It's documented where nobody finds it **until it's too late**. And there's a reason I said to have the *option* to decode HTML entities, not the *mandate*. Make it possible to decode LastPass CSVs properly. Why do you insist on letting new LastPass-to-bitwarden converts hang themselves?

**Comment by x11x** [comment]
Sorry to post in a closed issue.
Sure enough, this issue is clearly documented in the how to guide and indeed it is not bitwarden's problem. I read that article and still somehow missed that warning. I'm thinking lots of users would not even want to read that article and would find this a confusing hurdle for migrating from LastPass.
I'm just commenting because I think this is such a fantastic app and would like to promote its uptake over the major players. I think this issue will be offputting for non-technical users; nobody reads things carefully and non-technical people would be intimidated by the HTML codes.
I would agree that Bitwarden should not attempt to fix this problem, but would also agree with @tycho's suggestion that the user could be warned in a dialog at import time if HTML entities are detected in the imported passwords. And a simple button that lets the user automatically decode entities in their password would also be simple and helpful...
Just my 2c. Thanks again for this great software.
