### ISSUE TITLE
Option to disable badge text on icon

### ISSUE THREAD

**Issue by sgtfrankieboy** [bitwarden/browser#287]
I was wondering if it was possible to get an option to disable the badge notification.

This: https://i.imgur.com/2KQWPu9.png

**Comment by kspearrin** [comment]
I suppose it is possible. Is there a reason why?

**Comment by sgtfrankieboy** [comment]
I find it to be unnecessary and distracting. I've also recently moved from LastPass, where I could disable it in the settings. It's also possible to disable it in uBlock.

Whenever the badge in the corner appears / changes I think its because I got a new email.

**Comment by hrach** [comment]
> I find it to be unnecessary and distracting

Same for me, it its distracting and irrelevant to me.

**Comment by forteller** [comment]
Came here to open an issue just like this :)

**Comment by eskela123** [comment]
I would like functionality like this. When I ctrl+tab it changes constantly. It's irrelevant information for me, I know how many passwords I have for a site. Most of the times, I have 1, but for some, I have +9, seeing badge doesn't impact my behaviour in any way and doesn't help me either.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by forteller** [comment]
Why? Please don't tell me moving away from GitHub is a first step in closing up the source code! Then I will have to find something else to use and recommend.

**Comment by cassus** [comment]
This feature request on the forum: https://community.bitwarden.com/t/option-to-remove-number-of-matching-logins-badge/821
