### ISSUE TITLE
Larger fonts in extension popup

### ISSUE THREAD

**Issue by Phanx** [bitwarden/browser#300]
As a user with poor eyesight, I would love to see an option for larger fonts in the popup. Whether that took the form of a "small/medium/large" choice, a specific font size setting, or even just using the browser's default font size as a baseline instead of the current 14px, any improvement would be welcome.

**Comment by kspearrin** [comment]
Yea, its a shame the browser doesn't allow you `Ctrl +` to zoom the popup. We'll look into adding the option for increase font size, however, this likely means it will break existing designs since we're dealing with very small screen real estate.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
