### ISSUE TITLE
[Firefox] Clicking on the "launch website" icon in pop-out window opens a new tab in the pop-out window

### ISSUE THREAD

**Issue by aaronbauman** [bitwarden/browser#329]
Firefox 57.0b10
Bitwarden extension 1.19.1

- click on popout link from toolbar
- search for a site
- click on the "Launch Website" icon for a site

expected behavior:
- site opens in my main, usable window

observed behavior:
- site opens in the BW pop-out window
- BW pop-out is lost
- opened site is un-usable

**Comment by kspearrin** [comment]
How would we determine what is your "main" window? A user could have multiple windows open.

**Comment by aaronbauman** [comment]
The window from which the pop-out was deployed would be a good choice.
At the very least, some window other than the pop-out.

**Comment by kspearrin** [comment]
I'll have to investigate a bit more about what options we have with the window APIs.

**Comment by GeoDosch** [comment]
I just ran into this issue, and it's a bit disconcerting to the user.  (I wasn't aware of this bug report when it first occurred.)

When you click the 'pop out to a new window', the window that opens has all toolbars and tabs hidden/disabled.  When you click the 'launch site' icon, the new site opens in that window in a new tab.  However, no tabs are visible, and tabbing appears to be disabled, since \<ctrl-tab\> and \<shift-ctrl-tab\> does not allow for switching tabs. 

The only thing that can be done is to close the window, which gives the "You are about to close 2 tabs" warning.  Also, when running on Windows there is no apparent 'close' button, because the Title Bar is hidden by a blue bar, which doesn't appear until after the 'Launch Site' is clicked (though if you hover the mouse at the upper-right corner, you can see part of a red box appear which can be clicked to close the window.)  The hidden Title Bar does not occur on my Linux systems.

If nothing else, disabling the 'Launch Site' feature in a popped-out window would prevent confusion (if that's even possible)

**Comment by marataziat** [comment]
Why are you using chrome.tabs.create instead of just  window.open?

**Comment by eliykat** [comment]
I've been unable to recreate this issue using Bitwarden 1.4.1 and Firefox 85.0.2 on Windows 10 and Mac Big Sur. The launch button always opens a tab in a main Firefox window. This is an old issue, so it's probably been fixed by us or Firefox at some point.

I'm closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue, please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.
