### ISSUE TITLE
Toggle password view on log in

### ISSUE THREAD

**Issue by justinjk007** [bitwarden/browser#339]
I can't type 20 letter password couple of time every time I unlock the computer.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by justinjk007** [comment]
Ok thanks for the info
