### ISSUE TITLE
"Unable to auto-fill" for identities

### ISSUE THREAD

**Issue by benshep** [bitwarden/browser#347]
Trying to fill in name and address information on a [web form](https://caboodle.nationalbooktokens.com/win-national-theatre-play-in-a-box), I get "Unable to auto-fill the selected item on this page. Copy and paste the information instead."

**Comment by kspearrin** [comment]
This is expected at the moment since this website is not providing proper HTML attributes to cue the extension on how to autofill. See:

https://developers.google.com/web/fundamentals/design-and-ux/input/forms/
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill

We should probably try to make it more intelligent by also examining the input labels, which looks like it would work for this website.

**Comment by benshep** [comment]
Thanks. That's the impression I got on inspecting the DOM, the attributes are fairly opaque. I imagine that's quite a common issue though (this is the first form I tried to autofill with BW), and LastPass never had any problems with forms on that site.

**Comment by kspearrin** [comment]
This is fixed for next version which adds a lot more intelligence around autofilling cards/identities now.

**Comment by benshep** [comment]
Thank you!

**Comment by kspearrin** [comment]
Can you please try now with v1.21.x?

**Comment by benshep** [comment]
Works nicely, thanks! 

One field in that form is filled in incorrectly though - the label says "Postcode (Town in NI)" - I'd like it to fill in my postcode rather than my town. Can you move `postalCode` above `city` in the autofill order?

**Comment by chrissnell** [comment]
This issue has been happening again recently.  I'm running Firefox nightly.  It's not 100% consistent.  I'll get the error, then switch tabs, then come back and the fill works.
