### ISSUE TITLE
Callback Hell to Promises

### ISSUE THREAD

**Issue by ArtemNikolaev** [bitwarden/browser#35]
Find many code samples like that:
![Callback Hell](http://image.prntscr.com/image/12d4926a0a6a48698d69f23e534df664.png)

What about rewrite things like that to Promises?

 Angular has its own promise functionality: [$q](https://docs.angularjs.org/api/ng/service/$q), so there is no big problem to create clean and understandable code.

**Comment by kspearrin** [comment]
Yea, this is probably the most extreme example in the codebase. I started to implement `q` promises in many parts of the codebase which also suffered from the same issue, it just never made it to this part of the code since it was the only case that seemed so extreme and I didn't want to spend the time refactoring it all.

**Comment by kspearrin** [comment]
Closing this for now since there are no plans to change the mentioned piece of code.
