### ISSUE TITLE
Bitwarden doesn't prompt to save new login for gmail.com

### ISSUE THREAD

**Issue by yureiita** [bitwarden/browser#350]
Bitwarden doesn't prompt to save new login when logging in gmail.

**Comment by techionltd** [comment]
I've just encountered this problem on a Mac. Tested with Vivaldi (v1.13.1008.40) and Firefox (v59.0.2). Neither browser prompts to save details to BW when logging in for the first time.

**Comment by eliwaite** [comment]
Trying to teach a new user how to use BW and had this same issue on Chrome for Windows.

**Comment by Mokubyow** [comment]
I have the same issue

**Comment by Leyart** [comment]
Happens to me also

**Comment by Lapdogpdx** [comment]
Same on Firefox 65.0.2
Archlinux

**Comment by adamwinn** [comment]
I saw I didn't get the prompt and came here hoping for a solution

**Comment by tstilz** [comment]
still valid

**Comment by lateparty** [comment]
still occurring

**Comment by eliykat** [comment]
Thanks for reporting this issue. Although the "save password" prompt will never work 100% of the time due to different website designs, I agree its behaviour is currently inconsistent and could be improved. (Gmail should obviously be a high priority here.) I've noted down the website you're having issues with so we can look at it in the future as part of a broader review. In the meantime, please direct all general discussion to the megathread [here](https://github.com/bitwarden/browser/pull/1376).
