### ISSUE TITLE
Access to web vault on-premise server

### ISSUE THREAD

**Issue by jafreis** [bitwarden/browser#352]
Hi,

I have set up an on-premise bitwarden server, after configuring the browser extension (Chrome) with the URL's, when I click the "Bitwarden Web Vault" button it redirects to the site https://vault.bitwarden.com instead of redirecting the URL of the Web Vault configured in extension.

Sincerely,
José Reis

**Comment by amenk** [comment]
@jafreis How did you configure the URLs ?

**Comment by amenk** [comment]
Okay, found it .. in the login screen in settings.

I have the same issue here with the latest version of the browser extension in Chrome.

**Comment by kspearrin** [comment]
https://help.bitwarden.com/article/change-client-environment/

**Comment by amenk** [comment]
Yes that is what we did, but it does not seem to work.

**Comment by amenk** [comment]
URL is hard coded here:
https://github.com/bitwarden/browser/blob/master/src/popup/app/tools/tools.component.ts#L16

Shall I try a on pull request or will you fix it @kspearrin ?

**Comment by kspearrin** [comment]
Either way. We will eventually get to resolving this issue. PRs are always welcome.

**Comment by amenk** [comment]
I had a deeper look
My thoughts:

There is logic the gets the customWebVault Url is already in 

src/popup/app/accounts/accountsLoginTwoFactorController.js

        var customWebVaultUrl = null;
        if (environmentService.baseUrl) {
            customWebVaultUrl = environmentService.baseUrl;
        }
        else if (environmentService.webVaultUrl) {
            customWebVaultUrl = environmentService.webVaultUrl;
        }

I would extract that piece somewhere else (but where?) because we need it also apart from the TwoFactor Auth (in the "Open Webvault Tool")

Also the default vault URL should be extract to that place

(currently it is as well in `src/scripts/u2f.js`)

We need to replace the URLs in

src/popup/app/tools/tools.component.ts:16

with the new URL.

In the premium tab there are additional mentions of the vault URL - but I think those should always show to the official vault cause this is the one where the licenses can be purchased.
