### ISSUE TITLE
Bitwarden login field not auto-cleared if credentials is incorrect or invalid

### ISSUE THREAD

**Issue by Moxville** [bitwarden/browser#359]
Hi Kyle,
Bitwarden does not "auto-clear" credentials "field" 
a) when logging-in to the extension User has entered incorrect email-id / password
b) when User has entered incorrect password to unlock the account
It would be better, if bitwarden can auto-clear the login fields in these scenarios.
This is not a issue. Just a very minor thing I want to report
![untitled](https://user-images.githubusercontent.com/31923265/32477172-3feadc54-c3a2-11e7-99fe-dd21845505cb.png)

**Comment by eliykat** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
