### ISSUE TITLE
Sidebar keyboard Shortcut

### ISSUE THREAD

**Issue by cadecairos** [bitwarden/browser#392]
I'd love it if I could toggle the Bitwarden sidebar using a keyboard combo, similar to `Ctrl+Shift+U` (on Linux) to show the popup.

If you're open to this idea, I'd be glad to submit a PR.

**Comment by kspearrin** [comment]
Doesn’t Firefox already have a hotkey for opening the sidebar? Not sure if it Is possible for one to open bitwarden specifically that way. If it is, a PR would be great.

**Comment by cadecairos** [comment]
I don't know if there's a generic sidebar toggle shortcut, but I know that on Firefox you can specify a `_execute_sidebar_action` command to open and clise the sidebar of the extension.

It's detailed on [this MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands) page under "special shortcuts". I can create a PR tonight. And suggestions/requests for the key combo?

**Comment by kspearrin** [comment]
Well that should be pretty simple to add then. I'm not sure that key combo we want, but we'll have to make sure it is one that is available on all platforms without conflicting with other system shortcuts.

**Comment by cadecairos** [comment]
I'm having some trouble loading the dev version of the extension in chromium and Firefox. I'll give it another go tomorrow, I'm too tired to figure out what I missed 😴

**Comment by cadecairos** [comment]
@kspearrin: I can't seem to build the extension, I keep getting this error: `Error: EACCES: permission denied, mkdir '/home/images'` It's coming from the webpack step - do you have any insight into what could be causing it?

**Comment by kspearrin** [comment]
@cadecairos Sorry, I am not sure.

**Comment by frickenate** [comment]
In the meantime, for those who happen to be using macOS, it's possible to do this via a feature of the operating system itself.

1. Navigate to: `System Preferences` > `Keyboard` > `Shortcuts` > `App Shortcuts`

2. Click the small `+` button.

3. Select `Firefox` from the `Application` dropdown.

4. Set `Menu Title` to `bitwarden`.

5. Click in the `Keyboard Shortcut` field and press the shortcut you want. Personally I use `⌘⇧,`.

6. Repeat steps 2-5, but at step 4 set `Menu Title` to `bitwarden [1]` - set the same keyboard shortcut you used in step 5.

7. If you have any sites where you have more than login, repeat steps 2-5 and increase the number in square brackets. `bitwarden [2]` for at least two logins, `bitwarden [3]` for at least three, etc.

The `Menu Title` has to be an exact match to the text in the menu. Since bitwarden places the number of available logins for the current tab in square brackets, you need to add more than one entry to cover all cases.

This has been a lifesaver for me, so I sympathize with those who are not on macOS.

**Comment by jcrben** [comment]
For those that stumble on this from Google, alt+shift+u is the keyboard shortcut on Linux these days (see also: https://github.com/bitwarden/browser/issues/497).
