### ISSUE TITLE
Generate and fill password from context menu

### ISSUE THREAD

**Issue by aarikere** [bitwarden/browser#415]
Right now, when a new password is generated using the right-click context menu, the default action is to copy it to the clipboard. This adds an (unnecessary?) extra step to creating and using a strong password. 

Can this behaviour be modified so that the password is directly filled in to the highlighted field **without copying it to the clipboard**. This will make it easier to use bitwarden and (possibly?) make bitwarden more secure since the clipboard is bypassed.

**Comment by kspearrin** [comment]
We wouldn't modify existing behavior since many people expect it to remain working this way. We could explore adding it as a new one though.

**Comment by aarikere** [comment]
The reason I filed this issue is that right now, in Firefox, generating and using new passwords is a bit cumbersome. 

Here are the steps for bitwarden in Firefox:
Click on bitwarden icon on the toolbar > Add login > Generate password > Copy password > Click password field on the webpage > Paste generated password.

Compare this to Lastpass:
Click on the Lastpass overlay in the password field > Generate and fill
And that's it. (this is with the webextension version of Lastpass).

I know things are made a bit difficult in Firefox due to [not being allowed to copy to clipboard](https://github.com/bitwarden/browser/issues/102), but filling the generated password directly into highlighted field should hopefully be possible and would make things easier for Firefox users.

**Comment by Palf994** [comment]
I agree that this would be a great enhancement. I used to use LogMeOnce, and although the service wasn't great, the option to generate a password from the context menu worked very well and is one thing I really miss when using Bitwarden. When you clicked "generate password", a box popped up to allow you to adjust the length and characters that would be used and then put the password in the field automatically ([gener_5n97.jpg](http://sm.pcmag.com/pcmag_uk/photo/l/logmeonce-password-manager-ultimate-password-gener/logmeonce-password-manager-ultimate-password-gener_5n97.jpg)).

This was great because you could change the password criteria for an individual site, but it wouldn't change your default values. As it is now, if a site requires a password without special characters, for example, I have to go into the tools menu in Bitwarden, click on the password generator, change the options to match what the site requires and copy the password. Then I have to manually change the values back to what I want to be the default, otherwise the context menu option generates a less-secure password. There have been times when I've forgotten to change reset it and was generating less-than-optimal passwords for other sites.
