### ISSUE TITLE
FR: Add ability to search within login notes

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#446]
Currently, the search function within the browser extension does not search within login notes.

Can you please add this functionality?

Thanks!

**Comment by eskela123** [comment]
Huuuge +1 for it. I have various db passwords saved in notes, it's difficult to find correct note. My notes usually look like:
website.name / db_user / db_password
website.name / db_user / db_password
website.name / db_user / db_password

Since all notes created when needed, there's no single file, but maybe 30 of them in multiple folders. Name of the note is rarely of use (who knows 'New 1', 'New 2', 'New 3' syndrome...). I would usually search by website name, but it only gives login to the website and not the note. After the change, it would bring website login as well as note. 

I was already considering moving all db credentials to respective website entries, but it would be such a pain and wouldn't solve other problems. I have notes with things like license keys and I don't always have a separate login for each (and I won't create a separate notes for 1 license key just to give it nice name).

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/advanced-vault-searching/36

This issue will now be closed. Thanks!
