### ISSUE TITLE
TOTP copy icon in login list?

### ISSUE THREAD

**Issue by kriswilk** [bitwarden/browser#469]
Shortcut icons exist in the extension's site list to copy usernames and passwords to the clipboard. I propose that, for sites with TOTP configured, a third icon be present to copy the current TOTP to the clipboard.

In addition to being a convenience when you just need to copy the code, this would also give some visibility/reminder to sites that have stored TOTP data.

**Comment by kspearrin** [comment]
There's not enough room for 4 icons. Need a better UI strategy before we can add any more options.

**Comment by kriswilk** [comment]
I agree that clutter should be minimized.

One idea: since the username is already displayed under the site name, maybe make it clickable to copy the username to the clipboard? The same could be used for copying card numbers, which are already displayed (partially). Then again, maybe not as obvious/recognizable as the icons...

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/quick-copy-totp-code/38

This issue will now be closed. Thanks!
