### ISSUE TITLE
Opening one of multiple sites via extension should set the preferred login for autofill

### ISSUE THREAD

**Issue by kriswilk** [bitwarden/browser#470]
If I have multiple logins for the same site and I use the extension to launch/open one of them, bitwarden should set the "last used login" for the site to the one I just selected. Hence, if I autofill the intended login will be used.

e.g., if I launch "Amazon (Billy)" via bitwarden, then autofill should fill Billy's login, not Sally's or Tommy's.

This should also be tested with the experimental "autofill on page load"

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/opening-one-of-multiple-sites-via-popup-should-set-the-preferred-login-for-autofill/39

This issue will now be closed. Thanks!
