### ISSUE TITLE
"Confirm email" box not filled in

### ISSUE THREAD

**Issue by benshep** [bitwarden/browser#477]
When filling in a form using a BW identity, the **Confirm email** box is not filled in, even though the first *Email* box is. For instance on [this page](https://www.idmobile.co.uk/checkout/checkout.php?currentStep=1) (this is a checkout page, so it will be necessary to go through a couple of extra steps to be able to access it).

HTML source for the **Email** field: 
```html
<p class="control-label">Email</p>
<input class="inputText thin " name="personal_email" id="personal_email" value="" placeholder="E.g. email@website.com" data-error="Enter your email address" required="" data-com.agilebits.onepassword.user-edited="yes" type="email">
```

And for the **Confirm email** field:
```html
<p class="control-label">Confirm Email</p>
<input class="inputText thin" name="personal_email_repeat" id="personal_email_repeat" value="" placeholder="E.g. email@website.com" data-match="#personal_email" data-match-error="Email addresses do not match" required="" data-com.agilebits.onepassword.user-edited="yes" type="email">
```

**Comment by kriswilk** [comment]
I agree, this sort of thing seems to happen more frequently with BW than with LP (to be fair, LP has been working on this far longer than BW!).

The problem is not restricted to just email addresses...also things like the "state/province" and "country" fields/dropdowns when filling an identity. These can be extra complicated since choosing a country sometimes reloads the province field contents.

I would say this issue should be generalized as _"Better identify correspondence between form fields and stored site data"_

Really this is more of an ongoing task, since there will always be sites that do things in unexpected ways.

**Comment by benshep** [comment]
Yes, I agree. There are some other fields that aren't filled in consistently - county/state/province is a typical example, but also date of birth isn't usually handled (BW doesn't have a 'date' type for custom fields, so it's not too surprising that it isn't filled in when you get separate date/month/year fields). And yes, LastPass always handled this sort of thing flawlessly.

Of course, this doesn't usually have much impact on my life other than having to spend an extra couple of seconds filling in information. So it's not a huge issue.

**Comment by benshep** [comment]
Could we have an exception for email addresses, where it can be filled in up to twice? As I say, it's not a major issue in the grand scheme of things, but as a time-saving/annoyance-reducing app, I would expect BW to fill in both email fields.

**Comment by Ulti-FD** [comment]
I have not found a case yet in which a confirm email field has not been filled in. It seems that this has been fixed at some point since the opening of this issue. However:
> I would say this issue should be generalized as "Better identify correspondence between form fields and stored site/identity/card data"
is still an issue.

I have my email as a separate, custom field (named "Email") for the cases in which the two are seperate. I've noticed that the email field (usually for logins where there's only the email and password field to fill) fairly frequently does not get filled in or fills in username. I'm not exactly certain how the detection is coded, but it seems that the  `placeholder`/`autofill` tags get completely ignored, that `id` is prioritized over `name` and any surrounding text doesn't affect autofill. There are a lot of times where an `id` is something the lines of "accountName", "username", "user_email" (all real case examples) when it's actually an email field, yet it fills in username instead.

Fully willing to go through all my saved logins so I can post examples (I could probably find 20 or so) of sites that work and sites that don't. In the meanwhile, could anyone point me towards the code that distinguishes the different type of fields?

**Comment by benshep** [comment]
Take a look at [src/services/autofill.service.ts](https://github.com/bitwarden/browser/blob/master/src/services/autofill.service.ts) - it looks like that's where the field detection is being done.

**Comment by HandyHat** [comment]
An exception for email is definietly needed. When I come across a confirm email address field right now Bitwarden will fill in my address or my phone number

**Comment by HandyHat** [comment]
I believe this is still an issue

**Comment by Hinton** [comment]
Thanks for reporting this issue. This is a known problem that affects a number of sites, and we’re working on improving this feature. To help us track and analyze affected sites, please lodge a report using the Google Form mentioned in this issue: #1621. Please also direct any discussion or questions to that issue. This issue will now be closed.
