### ISSUE TITLE
Aufotill not working for George Internet Banking

### ISSUE THREAD

**Issue by Pryx** [bitwarden/browser#486]
Hi, autofill doesn't work for George internet banking app. Could you please take a look if anything can be done about that? Thanks.
Link: https://george.csas.cz/

**Comment by kspearrin** [comment]
Which autofill? Accessibility or Oreo?

**Comment by Pryx** [comment]
Sorry should've probably specified - I've got autofill enabled in the browser extension - desktop Firefox. Opening the vault and clicking on the credentials ends up displaying message that I have to copy and paste the username and password manually.

**Comment by kspearrin** [comment]
Whoops. Thought this was mobile.

**Comment by kspearrin** [comment]
Worked for me. Seems like you need to create a custom field called "nickname" for the first step since there is no password field on screen initially. Then autofill again for the password on step 2.

![screen shot 2018-01-18 at 8 37 14 pm](https://user-images.githubusercontent.com/1190944/35130552-787ad3d2-fc8f-11e7-9ec5-4e6488a53261.png)

**Comment by Pryx** [comment]
That might pretty much be it, totally forgot you added custom fields and so it didnt occur to me that it could be solved like that. Thank you :)
