### ISSUE TITLE
Get title from Website title

### ISSUE THREAD

**Issue by luismanson** [bitwarden/browser#496]
Hello, is it possible to get the title field populated from the website title and (maybe) URL? 
This could also be a something customizable with variables 

thanks

**Comment by kspearrin** [comment]
We could, but chose not to since website titles are usually not very short and concise. They are usually filled with SEO spam or are irrelevant to when out of context.

**Comment by luismanson** [comment]
I understand, in that case an option would be good, if you can. Or (adding a click) showing the title input box when i ask to save the login.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
