### ISSUE TITLE
add auto-login checkbox 

### ISSUE THREAD

**Issue by raingart** [bitwarden/browser#499]
You can add a checkbox-option of auto-login to the site. 
Sometimes it's too lazy to press the log in button

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/automatically-submit-loigin-form-on-autofill/24

This issue will now be closed. Thanks!
