### ISSUE TITLE
Chrome extension does not fetch updated passwords from the vault

### ISSUE THREAD

**Issue by vatjjar** [bitwarden/browser#50]
I just installed the latest extension to my latest Chrome, and noticed an issue with password updates. The procedure I did was this:

1) Create a login/password pair in the cloud interface for a new site
2) Install extension and login to bitwarden
3) Use extension to retrieve password for the test site -> this works
4) Update password of the site via cloud interface
5) The extension seems never get the update and proposes the old password all the time.
6) (did 30 minutes of waiting if the password updated, but no)

Page refresh does not help. Chrome restart does not help. Uninstalling the extension and reinstalling it works.

As a side remark, the android app sees the updated password immediately so this smells like the extension has the issue.

**Comment by kspearrin** [comment]
The android application has push notifications, so I am able to push things to it instantly. The chrome extension unfortunately does not have this option, so we have to poll the server for updates.

The extension with poll the server every 6 hours for new updates. We could reduce the polling to a shorter interval but that would lead to a lot of unnecessary traffic to the server (since 99% of polls will result in no changes). The decision for 6 hours was to try and keep traffic down and give you the latest updates 4 times per day. If you made a change that you know you need and it is not listed you can simply go to the settings tab and do a manual sync.

**Comment by jenmarketing** [comment]
Good to know, thanks for explaining this @kspearrin
