### ISSUE TITLE
add "Forced password input"

### ISSUE THREAD

**Issue by raingart** [bitwarden/browser#501]
You have the option "Auto-fill On Page Load". it's comfortable. But on some sites (banking, etc.) it is desirable to disable it. You can add the option "Forced password input".

**Comment by bfranske** [comment]
I'd like to see this too, but because there are some sites where the autofill just doesn't work quite right and fills in wrong fields when I'm editing my profile, etc. that I don't want it to fill. Most of the time I want autofill on but there are a couple problematic sites where I'd like it off.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests). Please [sign up on our forums](https://community.bitwarden.com/signup) if you want to continue contributing to feature requests.

Since this was a popular feature request we have already re-created it on the forums and linked back to this GitHub issue for reference. You can vote for this feature request there if you'd like.

https://community.bitwarden.com/t/disable-autofill-on-page-load-feature-for-specific-login/22

This issue will now be closed. Thanks!
