### ISSUE TITLE
Permit autofill from search results

### ISSUE THREAD

**Issue by kriswilk** [bitwarden/browser#502]
Sometimes the login details for a site don't turn up in the list of matches. So I start typing in the search box to find the login that I want. However once I find it, there is no way to autofill...clicking the login simply views its details.

I've mentioned this inconsistency in issue #473. There I originally argued that the default click behaviour in all modes should be "VIEW". But based on daily use, I much more frequently need to autofill.

With that in mind **I propose that the consistent click behaviour for a login in Tab / My Vault / Search should be to AUTOFILL.**

I hope that makes sense.

**Comment by kspearrin** [comment]
The need for searching for an entry to autofill from the "Vault" tab is much lower since it should really only need to be done in cases where the detection fails on the "Current Tab" tab. For this reason, making autofill the primary function seems unnecessary. Perhaps we tuck it away in some other menu available in the View page or something?

**Comment by kriswilk** [comment]
Well, I'd be satisfied with whatever you choose as long as there is a consistent behaviour when clicking on a login regardless of the way you got to it (that's the focus of #473). And as long as there is some way to accomplish an autofill from search results or the vault...

Another (more relevant) case I've run into: I have many credit cards and identities...when I want to fill one it's usually easiest to CTRL-SHIFT-Y then start typing what I want rather than scrolling through the list. But this won't currently work since I can't autofill what I find.

FWIW, this is also related to #361 (keyboard shortcuts), so the situation has a few angles that must all work together...

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
