### ISSUE TITLE
Hide collection items from the 'No Folder' group

### ISSUE THREAD

**Issue by RixzZ** [bitwarden/browser#503]
Hello,

I use some collections of my organization to save there items I don't want to see when I don't try to find them, like notes with software licenses or so.

As I see, collections count as items without folder, so when you see the 'No Folder' group of your vault, they appear there mixed with the other stuff.

Could there be an option to hide them from the other groups of the vault, so you can only find them if you go specifically to the Collection entry?

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
