### ISSUE TITLE
Make "sync now" more accessible

### ISSUE THREAD

**Issue by kriswilk** [bitwarden/browser#507]
I suggest that the manual "sync now" action be moved from the settings panel to the extension's persistent top bar, directly beside the "pop-out" button. Use the conventional "chasing arrows" icon and users will instinctively know what it does.

This would be very handy after making changes to items in the web vault (which I prefer for organizing/editing logins).

**Comment by RixzZ** [comment]
I would like that too. Sometimes if you change something in the web vault, you need to sync it manually and is a bit hidden.

**Comment by scotte** [comment]
Ideally, it would be nice if the extension synced smarter such that a manual sync would rarely ever be required.

**Comment by kriswilk** [comment]
Yes, more intelligent syncing would be nice...it's already been hinted at in #131. But regardless of such "smart" features, I think it's always a good idea to be able to do a manual sync, and I don't see any harm (in fact I only see the positive) in bringing it to the forefront.

**Comment by kspearrin** [comment]
@scotte How would you suggest that we make it smarter?

**Comment by scotte** [comment]
@kspearrin perhaps by being a bit more strategic about syncing, such as when opening the extension's vault/interacting with the UI. Basically being a bit more opportunistic about when to sync (I probably should have used that wording instead of "smarter" to begin with). Too frequent is equally bad, there's a balance somewhere.

I say this knowing nothing about the internals of bitwarden and so I don't know how reasonable it really is. Hopefully there's a light-weight API call to determine if it needs to sync.

I agree @kriswilk there's absolutely no down side to making manual sync easier to navigate to.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
