### ISSUE TITLE
Should Chrome extension be aware of two-factor authentication?

### ISSUE THREAD

**Issue by vatjjar** [bitwarden/browser#51]
I noticed that the Chrome extension does not react to enabling of two-factor authentication. I'm a little bit unsure if it needs to, but anyway here is the procedure I wonder whether is a bug or not:

1) Login to cloud interface (two factor disabled)
2) Login with extension to the vault
3) Enable two-factor auth in the cloud interface

Without forcing the extension to make a re-login there is no awareness of the two-factor auth. If after the mentioned steps 1-3 I edit entries in the vault via the extension interface (i.e. update a password of one site), the modification succeeds perfectly fine.

The question is that after enabling two-factor auth, should one enforce all active connections to re-authenticate) or is this legit behavior?

**Comment by kspearrin** [comment]
This sounds like an issue since enabling two factor authentication is suppose to force log you out the next time that you reach out to the server (via an update or sync for example). I will have to investigate.

**Comment by marcelpaulo** [comment]
This issue is still present. I'm running the Bitwarden free Chrome extension 1.29.0 with Google Chrome 68.0.3440.106 on Xubuntu 18.04.1, and I've just observed this, too: I enabled 2FA with Authenticator App (Authy):
![image](https://user-images.githubusercontent.com/10074769/44204466-09814d00-a129-11e8-9758-07bcfe157a9c.png)

but the extension only asks for the authenticator code if I explicitly log out. Even if I reboot my laptop, when I next open Chrome, the extension allows me to log in with just my master password.

I get the impression that the extension **never** logs out unless told so explicitly: even if Chrome is killed, the extension only locks. I guess this is the root cause.

If the extension is the primary access to Bitwarden, this issue renders 2FA ineffective, since it only kicks in after explicit logout.

**Comment by balboah** [comment]
Seems same with firefox extension and also the linux bitwarden client? I've enabled 2-factor on a different machine but on linux I can still login and vault sync works. Seems like a bug to me

**Comment by ElectricSwan** [comment]
I agree that the Chrome extension should ask for 2FA after lock (as well as after logout).
Alternatively, add an option to the Chrome extension to logout after a period (rather than only auto lock). 
The fact that Bitwarden doesn't force 2FA after auto lock puts Bitwarden behind LastPass for 2FA security.

**Comment by beatsandpics** [comment]
any update on this? 2FA is only asked if I explicitly log out out from my browser extension.

**Comment by fsergiojr** [comment]
Same thing happens on MacOS 10.15 and Safari. Quitting browser does not prompt for 2FA code. Even if computer gets restarted, 2FA code is not prompted either. The code is only asked if I explicitly choose to log out. It also would be nice that once the vault is locked it could be unlocked using the 2FA code

**Comment by daidekker** [comment]
I have the same issue. Chrome extension, not automatically asking for 2nd factor when login.
Proposing a simple fix. When the extension "locks" dont call the lock code but call the "log-out" code. When you log-out of the plug-in, and want to log back in, the plug does ask for the functionality.

**Comment by PinkDev1** [comment]
Same happens in Edge, 2FA is only pressent when you first log-in. But the 2FA OTP is not requested when you "unlock the vault". The 2FA OTP will only be required if you go to the settings and log-out.

**Comment by ascisco** [comment]
Having the same problem on Chromium. 2FA is enables and works when I login to the Bitwarden website but 2FA is not asked for when logging into Bitwarden extension. This is a big security problem imo, the whole point of 2FA is to add a second layer of protection to all login fields.

**Comment by HamsterHam88** [comment]
I would like to be able to set it up so when my browser is closed Bitwarden is logged out so therefore I would need to type in my password and 2FA again.

**Comment by Progdrasil** [comment]
I have this issue on firefox 72 as well as with the android app

**Comment by JacobRReed** [comment]
unsure why that commit is referencing this issue @Hinton

**Comment by Hinton** [comment]
@JacobRReed Hmm, not sure what happened there. Fairly certain all I did was sync my local fork with upstream.

**Comment by arobass** [comment]
What is happening with this issue? Still an issue with Chrome plugin, I log out in the plugin, close Chrome, reboot, open chrome and I'm able to log into my vault with the plugin only using password (does not prompt for 2fa). This is nonsense. Big security flaw here.

**Comment by Orlandoke** [comment]
It would be really nice if once the vault is locked (after a timeout for example) it could be unlocked using a 2FA code rather than a fixed PIN code.

**Comment by HamsterHam88** [comment]
I still think we need this. I would like on every shutdown/restart of my laptop I have to enter my 2FA.
