### ISSUE TITLE
Prompt for master password to unlock on browser restart

### ISSUE THREAD

**Issue by Gitsko** [bitwarden/browser#511]
Hi, i use the browser plugin for firefox.
I use the option to lock my fault by restart the browser.

Is there a way that the master passwort come in foreground when i start the browser or when the first login where needed ? (like the firefox internal passwort-vault)

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
