### ISSUE TITLE
Provide PGP signed sources and builds for each release

### ISSUE THREAD

**Issue by JSN190** [bitwarden/browser#522]
Whether you're downloading the extension from your browser's respective add-on store or cloning it using git and building from source, you'd have to trust the download source to provide you with a copy that has not been tampered with.

For a highly sensitive piece of software, like Bitwarden, there should be an easy way for a user to verify the authenticity of their download. One way to address this concern would be to provide sources and builds for _each_ release that is signed by a PGP key belonging to Bitwarden.

I am aware that modern browsers do require add-ons to be signed using an official key belonging to their respective add-on store, but this only means as much as the user's trust in the key owner. As far as I know, there would not be anything stopping you from signing your own build using GnuPG and also having it signed for distribution by Mozilla or Google.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
