### ISSUE TITLE
Separate favorites in the tab view

### ISSUE THREAD

**Issue by Crocmagnon** [bitwarden/browser#531]
I suggest to separate favorites in the tab view when multiple accounts for the service are detected. We could have them displayed like the vault view : separately at the top.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
