### ISSUE TITLE
Add functionality to export Cards

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#533]
There appears to be no functionality to export Cards data!

Please add it.

**Comment by GeoDosch** [comment]
Did you look at "Tools->Export Vault"?

**Comment by setyb** [comment]
Yes, that does not export Cards at all.  It only exports logins.  There appears to be no way to export Cards data.

**Comment by setyb** [comment]
@kspearrin Can this be fast-tracked?  Having a backup of data is essential!

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by setyb** [comment]
@kspearrin  Although this issue may sound like a feature request, I think it is more of a **bug report**, as the export function fails to export all the data.
