### ISSUE TITLE
Offer TOTP during autofill on page load

### ISSUE THREAD

**Issue by kriswilk** [bitwarden/browser#536]
During an auto-fill on page load, the TOTP is not automatically copied to the clipboard. I understand that this is to prevent accidental erasure of the clipboard contents while browsing.

But I've had enough experiences getting tripped up by the TOTP and needing to dig for it in the login details to know this could be done better. I've argued for the TOTP to be available via an icon just like username/password (#469).

Maybe even better would be a brief toast message when auto-filling which has a button/link to copy the TOTP?

It could (should) also be added to the context menu as "Copy TOTP", alongside "Copy username" and "Copy password".

**Comment by Crocmagnon** [comment]
At least related to #527

**Comment by kriswilk** [comment]
Missed that closed issue, yes it's related...

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
