### ISSUE TITLE
Edge extension "My Vault" tab not working

### ISSUE THREAD

**Issue by jocap** [bitwarden/browser#567]
Hello!

I'm using Microsoft Edge 40.15063.674.0 on Windows 10 Education version 1703 and I've installed and logged into the Bitwarden extension. Unfortunately, it doesn't seem to be working properly:

* The "My Vault" tab doesn't open when I click on it.
* Unlike the other browser extensions, the Edge extension doesn't appear to have a search bar.

Here's a screenshot of the extension's interface:

![Bitwarden GUI without search bar](https://user-images.githubusercontent.com/92702/37862791-485eb938-2f53-11e8-95fd-2e7f09ef41b6.png)

**Comment by kspearrin** [comment]
The missing search bar is expected, since we disabled it in Edge for performance reasons.

I am not sure why you wouldn't be able to access your vault though. Does the web vault work properly? Have you tried the extension in another browser to see if the same problem exists?

**Comment by kumarharsh** [comment]
+1 the vault is not accessible in Edge. It works fine in Chrome. Web-Vault also works.

**Comment by eliykat** [comment]
We now support the search bar in Edge and I haven't been able to recreate any UX problem with loading the My Vault page. This is an old issue, so I assume it's been fixed in subsequent updates.

I'm closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.
