### ISSUE TITLE
Firefox startup slow when auto-logging/unlock

### ISSUE THREAD

**Issue by daddy33** [bitwarden/browser#570]
Hello,

this is noticeable, especially you can see that the images on the start page take long to load.
When auto-login/connect is disabled (when it is locked upon restart), startup/1st page loading time is normal.

Thanks.

**Comment by kspearrin** [comment]
Duplicate https://github.com/bitwarden/browser/issues/530

**Comment by kspearrin** [comment]
What "images on the start page" are you referring to? The website icons?

**Comment by daddy33** [comment]
Well, on the Mozilla startup page, I have "Top sites" and "Hightlights". These two behave differently. "Top sites" icons are not affected by this, but the thumbnails of the "Highlights" sites take around 3/4 seconds to be displayed. Another example: the Google logo or the custom image replacing the logo on the Google main page is also affected (which as a result makes the Google main page load much slower upon startup if I set it as my starting page).

**Comment by daddy33** [comment]
I also confirm there is absolutely no such issue in vivaldi using the chrome extension.

**Comment by kspearrin** [comment]
I am having a hard time understanding the description of the problem. Are you saying that when you start the browser up it is noticeably slow for a few seconds and that this slowness is manifesting itself in the form of images on the page loading slow? And this problem only happens when lock options are set to "On Restart"?

**Comment by daddy33** [comment]
Exactly. But the slow image loading is only one of the symptoms. The browser takes a few seconds to be responsive, that's a bit more general. I have also tried with an empty firefox profile, and the problem remains.

**Comment by kspearrin** [comment]
The weird part about your description is that you say the problem does not exist when using the "Never" lock option. I would think the opposite would occur, since no decryption of the vault occurs with "On Restart" until you actually unlock the application with your master password. All that happens on browser startup in that case is a sync.

**Comment by daddy33** [comment]
OK sorry, I didn't read carefully enough your previous message. Of course, that's the opposit, the problem occurs when the lock option is set to "Never".

**Comment by kspearrin** [comment]
Ok, then that would make sense then. Your browser is decrypting your entire vault when it is first opened. If a vault is of significant size this would potentially cause performance problems on a device. Chromium browsers are probably more efficient at decryption than Firefox. Is this a low-end device with regards to performance?

**Comment by daddy33** [comment]
Not really a low-end device: 
Athlon(tm) X4 860K Quad Core with 16GB RAM and 480GB SSD, running antergos linux 64 bits.

**Comment by kspearrin** [comment]
Can you see if this is improved in the newly release 1.26? There were significant changes made to try and increase performance throughout the UI.

**Comment by kspearrin** [comment]
Should be resolved in v1.28. If not we can re-open.
