### ISSUE TITLE
Display warning when password autofill is longer than maxlength

### ISSUE THREAD

**Issue by Carbonyte** [bitwarden/browser#63]
When an \<input type="password"\> has a maxlength property, BitWarden will happily autofill into it, silently cutting off any characters that don't fit. This can cause problems if, for example, the user autofills a 64-character generated password when signing up for a site with maxlength=32; if the site ever decides to raise the maximum length, the user will suddenly find themselves unable to log in.

**Comment by elysium-12** [comment]
I have had the exact problem mentioned by Carbonyte, On multiple instances where maximum character length was 32, however bitwarden saved the 64 character generated password, then each login attempt is marked as invalid as the password login field doesn't limit and input to 32 characters. To bypass this issue I have to manually set the generate password length to the max allowed length for each site.
Evn: FF 58.0b5 (64-bit), Bitwarden 1.21.4

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by luckydonald** [comment]
@kspearrin How does one now contribute code for that?

**Comment by eliykat** [comment]
@luckydonald we still accept PRs on Github for code contributions, although we encourage you to float the proposal on the Community Forums first if it's a large/significant change. See contributing.md for more information.
