### ISSUE TITLE
Autofill hotkey for macOS Safari and Non-US keyboard layout

### ISSUE THREAD

**Issue by steffenhk** [bitwarden/browser#701]
The Autofill hotkey on macOS for Safari (Cmd+\) does not work on a DK keyboard layout.
On a DK layout I have to hold down option+shift and press 7 to make a '\\' but Shift+Cmd+\ is already a Safari shortcut for "Show Tab Overview".

**Comment by ehirsch** [comment]
+1 for German layout

**Comment by maurice-schleussinger** [comment]
I tried rebinding the overlapping shortcut in the macOS settings: 
<img width="780" alt="image" src="https://user-images.githubusercontent.com/1615089/52422535-8698e800-2af6-11e9-88ac-86b49636fc9c.png">

Now simply nothing happens as I press the correct combination (QWERTY, German layout). I considered switching from 1Password, this is a dealbreaker right now.

**Comment by Crocmagnon** [comment]
Any news on this? I'd like to give Safari a fair try again and this issue prevents me from using the browser + Bitwarden to its full potential.

I saw that <kbd>Cmd</kbd>+<kbd>8</kbd> was added since but it's still impossible to trigger on an AZERTY keyboard.

Please consider non-QWERTY layouts when assigning non-modifiable keyboard shortcuts 😕

I'd like to point out that <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd> and <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd> don't seem to be taken on Safari.

**Comment by cscharf** [comment]
<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd> could work.... 

is ⇧⌘P taken on anyone's current mappings? I see opportunity for all, but being native autofill (⇧⌘A) is already assigned to Safari and a JavaScript plugin could not override that key combo, but ⇧⌘P for "password" could definitely work if available (and still make sense).

**Comment by cscharf** [comment]
Notes to self,

see: https://github.com/bitwarden/browser/blob/master/src/content/shortcuts.ts
also: https://craig.is/killing/mice

**Comment by Crocmagnon** [comment]
⇧⌘P isn't taken on my side.
