### ISSUE TITLE
Problem with custom fields

### ISSUE THREAD

**Issue by dwf** [bitwarden/browser#706]
I'm trying to get a field autofilled based on a custom field with the label text "First" (see the label for `ctl00_OLSContent_txtFirst` below). 

Inspecting elements in Chrome, I see
```html
<label for="ctl00_OLSContent_txtFirst" id="ctl00_OLSContent_lblFirst" class="form-field--valign-center__inner charsLabel">First</label><span class="chars">&nbsp;character</span>
```
and
```html
<input name="ctl00$OLSContent$txtFirst" type="password" id="ctl00_OLSContent_txtFirst" maxlength="1" size="2" class="password" tabindex="0" onkeyup="return autotab('ctl00_OLSContent_txtFirst',1,'ctl00_OLSContent_txtSecond', event )">
```

Unfortunately I can't use the ID or the form element name, as the label changes from login to login and indicates which piece of information needs to get filled, hence trying to match on the contents of the label tag. 

Any idea why this isn't working?

**Comment by kspearrin** [comment]
First should work I would think. Can you share the website address?

**Comment by dwf** [comment]
I've redacted what I assume is private state but this should contain everything relevant https://gist.github.com/dwf/bd30b360704109e72d766ff9c0701014

**Comment by dwf** [comment]
(And yeah, it's a ridiculous prompt, don't get me started on UK financial institution authentication policies...)

**Comment by kspearrin** [comment]
Using your gist, I was able to autofill the field using `ctl00_OLSContent_txtFirst` just fine.

The label detection fails because of the broken HTML that exists on this page. The input has an associated label with for => id, as you've seen, however, the input itself is also wrapped in another label, which has the text values "Password character is invalid" and "Password character is required".

Due to this issue, the full label for this text field actually is:

```
First                      
                                    
                                    Password character is invalid
                                    Password character is required
                                
```

Which I don't think you're going to be able to specify properly as a custom field name.

**Comment by dwf** [comment]
Aha. Thanks for looking into it. Given that this was the problem I was able to work around using `regex=` fields. And for anyone else using Bitwarden with this site, [this snippet](https://gist.github.com/dwf/f7f0f2648c30ad931fb4fe178268a744) will automate converting their "grid card" into 10 custom (regex) fields for Bitwarden to autofill them for you.

Thanks @kspearrin! This is why I evangelize Bitwarden to anyone who will listen and urge folks to go Premium. :smile:
