### ISSUE TITLE
BUG - Bitwarden fills Forum Credentials in Biwarden Vault

### ISSUE THREAD

**Issue by OLLI-S** [bitwarden/browser#715]
In BW I have stored the credentials of the BW Forums (https://community.bitwarden.com/).
I have not stored the login for the BW vault (https://vault.bitwarden.com).

When I open Firefox and go to my vault then BW fills the credentials of the BW Forums into the Vault login.
But both information is not correct.
If I open the "Settings" in my vault, then BW fills all 4 password fields (I suppose with the credentials of the BW Forums).

**Comment by Crocmagnon** [comment]
That's because of how the extension performs URI match detection. Please read the article here : https://help.bitwarden.com/article/uri-match-detection/

By default, the match is on the base domain, so credentials in vault.bitwarden.com matches community.bitwarden.com since they share the same base domain.
To fix it, you can change the match detection rule for your community.bitwarden.com URL to "host"

**Comment by OLLI-S** [comment]
@Crocmagnon Thank you, that solved the problem!
