### ISSUE TITLE
I'm a bit confused as to how 2 Factor Auth is suppose to work?

### ISSUE THREAD

**Issue by lhorace** [bitwarden/browser#730]
Hello,

To better secure my vault, I recently enabled 2 factor authentication after an login attempt was blocked by google to one of my google accounts. While it works flawlessly on https://vault.bitwarden.com/, and I've tested it on Microsoft Edge. Unfortunately, it does not work in Firefox or Google Chrome. Once I login, I'm always taken to my vault?

Best Regards

**Comment by kspearrin** [comment]
2FA is only applied when logging in. Are you logging in or unlocking?

**Comment by lhorace** [comment]
Huh, there is a difference with 2FA between unlocking and logging in? I surmise that's what I'm confused about, I'd prefer 2FA even when unlocking the vault?

**Comment by kspearrin** [comment]
Logging in authenticates to the server, which requires you to be online. Unlocking authenticates locally and can be done offline.

**Comment by MarkCWEV** [comment]
This is a really bad design. I have my account auto-lock, shutdown my PC and not once will I promoted for 2FA. Is it at all reasonable (or sensible) to expect users to remember to logout. Couple that with the fact that in Chrome there is no logout when unlocked, you have to Lock it and then click logout in the Master Password dialog. Worst case, there should be an option to auto logout (instead of auto-lock) and to require 2FA on unlock
