### ISSUE TITLE
Autofill after search

### ISSUE THREAD

**Issue by Scifire** [bitwarden/browser#766]
I´m not sure if this is more a feature or a bug. 

if you have multiple logins for a single website and you open bitwarden browser plugin you can click on one of them and it will fill out the credential filed of the website. 
If you use the search in the plugin to find a login the auto-fill will not work anymore. If you click on the entry in the plugin it will open the information page of it. Then you need to copy and paste username and password manual in the credential field of the website. 

I would expect that auto-fill after clicking an entry will work all the time.

**Comment by kspearrin** [comment]
Hi. This would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
