### ISSUE TITLE
Unsigned extension no longer work in Firefox Android 64 (beta)

### ISSUE THREAD

**Issue by sandermarechal** [bitwarden/browser#773]
I use Firefox Android developer edition which is currently at version 64.0b7. It appears that unsigned addons no longer work in this version. The bitwarden addon is installed but disabled, and there is no way to enable it because "This add-on could not be verified by Firefox Beta", with a Learn Mode link that goes to https://support.mozilla.org/en-US/kb/add-signing-firefox-android

**Comment by kspearrin** [comment]
> Where can I find signed add-ons?
> 
> All add-ons hosted on addons.mozilla.org are signed before they are listed.
> 
> Add-ons hosted on other sites may or may not be signed by Mozilla. Firefox allows you to install add-ons from other sites, as long as they follow the add-on safety guidelines. 

If you are getting the extension from addons.mozilla.org, it should be signed. Sounds like a Firefox problem.

**Comment by sandermarechal** [comment]
Uninstalling and reinstalling fixed the issue. Not sure what the problem was. Thanks anyway!

**Comment by bithooked** [comment]
I ran into the same issue tonight.  Reading this thread, I uninstalled it. However trying to reinstall from Mozilla.org it throws an error that Bitwarden could not be installed because "it appears to be corrupt".  Something is going on.  I've been using Bitwarden on Firefox in Android for at least a year without trouble before today.

**Comment by sgraf-pub** [comment]
I got the same issue today like @bithooked . For uBlock Origin and HTTPS Everywhere addons on Firefox in Android.
