### ISSUE TITLE
Add attachment is conceptually broken because, focus => state is lost

### ISSUE THREAD

**Issue by jonasfj** [bitwarden/browser#793]
According to https://github.com/bitwarden/browser/issues/443#issuecomment-353094316 it is not a bug that bitwarden looses state when extension pop-up focus is lost.

Assuming the browser extension libraries don't give any good hooks. I would suspect that storing state in `localStorage` or `sessionStorage` would be possible.. but I can see that there might be security implication.

Anyways, if loss of state in case of loss of focus is indeed intended behavior and not a bug, then clearly attachments cannot possibly work. Because opening the filechooser causes the extension pop-up to loose focus.

Hence, attachments should be disabled when the extension is used in pop-up mode.
In fact it's probably best to not let people make modifications in pop-up mode. This makes it easy to loose passwords you've just generated or created elsewhere and trying to save. If the flow is a footgun, I would suggest removing it.

**Comment by kspearrin** [comment]
This is a known bug in Firefox. Other browser don't suffer from this.

https://bugzilla.mozilla.org/show_bug.cgi?id=1292701

**Comment by jonasfj** [comment]
I had the issue with chrome is under gnome.
Probably it has to do with the filechooser being the platform native filechooser.. Hence, Firefox and chrome will get the same focus behavior on gnome.

The underlying issue as far as bitwarden is aware is the fragility wrt. to focus #443. I would suggest finding a fix for that.

Can't you just serialize popup state to JSON and postMessage to the main extension?
Maybe with 100ms delay if changes are to the same text form, granted I doubt people write long essays... :)

**Comment by ajostergaard** [comment]
FWIW I use attachments and Firefox but dock BW in the sidebar FTW. ;)

**Comment by cben** [comment]
I didn't even realize BitWarden can live in a sidebar :tada:
I don't have premium so can't say about attachments, but sidebar works great for adding logins :heart: 
- [x] Sidebar is superior to the popup because it doesn't close when I press <kbd>Ctrl</kbd> trying to paste :+1: 
- [x] And sidebar is superior to pop out window because the pre-filled context like current URI is not lost :+1:

Any chance you can make actions like add / edit / pop out icon redirect to sidebar?

Instructions for others:
1. F10 or Alt to open menu bar -> View->Sidebar->Bitwarden.
2. That menu will likely show you a keyboard shortcut, Alt+Shift+U for me on linux, likely Alt+Shift+Y on other OSes per  https://github.com/bitwarden/browser/blob/f57be6561f164b643fbcc286a686e6a4d6d5e1d8/src/manifest.json#L91-L97

**Comment by eliykat** [comment]
Same issue as https://github.com/bitwarden/browser/issues/1354, fixed in https://github.com/bitwarden/browser/pull/1532. 🥳
