### ISSUE TITLE
Password Autofill: TOTP Token is not copied to clipboard

### ISSUE THREAD

**Issue by gerripeach** [bitwarden/browser#826]
The TOTP Token is copied to clipboard when some kind of form is filled manually.

When using the autofill function, the TOTP token is not copied to clipboard.

**Comment by kspearrin** [comment]
I assume you mean it is not copied when using the "autofill on page load" option? If so, this is expected. To prevent arbitrarily overwriting a users clipboard, we only copy the TOTP code when an explicit autofill action is performed.

**Comment by wehrstedt** [comment]
> I assume you mean it is not copied when using the "autofill on page load" option? If so, this is expected. To prevent arbitrarily overwriting a users clipboard, we only copy the TOTP code when an explicit autofill action is performed.

I searched for a while now why the totp code is not copied anymore to the clipboard (I could swear it worked before even with autofill on page load). Now I disabled autofill on page load and it works again.

Would be nice if this will be better documented in the option `Disable automatic TOTP copying` because it's not clear that this feature will not work with autofill on page load (at least in the german translation, I don't know if its better documeted in english.)

What about an option to enable both functions?
