### ISSUE TITLE
[Request] - Capture all login form fields

### ISSUE THREAD

**Issue by wondergryphon** [bitwarden/browser#83]
Something that LastPass/1Password had which I realize I'm missing with Bitwarden now, is the ability to capture other fields on a login form.

Example: https://www.paygate.co.za/boffice2/ <-- This particular form also requires a 'Company' field. 

So would be awesome if the plugin recognized + saved data from all fields in a login form, and not just username + password

**Comment by kspearrin** [comment]
Custom fields other than username/password is on our future roadmap. Thanks for the feedback.

**Comment by hugodantediaz** [comment]
Yes, please. This enhacenment is fantastic! Most websites work with many fields for login.

**Comment by kspearrin** [comment]
Custom fields is now available in 1.17.x and up. Capturing the fields automatically is still not available. You just need to set them up manually for now still.

**Comment by kspearrin** [comment]
We are moving away from tracking Bitwarden feature requests like this one as GitHub issues. We have created a [Bitwarden Community Forum](https://community.bitwarden.com) which has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup), search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
