### ISSUE TITLE
paste OTP overwrites clipboard

### ISSUE THREAD

**Issue by j0hnsmith** [bitwarden/browser#858]
When signing into a site that uses OTP, bitwarden (on chrome) puts the OTP in the clipboard, after pasting the OTP it should put back whatever was previously in the clipboard.

**Comment by Crocmagnon** [comment]
It looks more like a feature request than an issue to me. You can post it at community.bitwarden.com.
For reference, there is a setting to disable the copy of the TOTP to the clipboard.

**Comment by eliykat** [comment]
This is the expected behaviour. I think users might be alarmed if we were scraping and (temporarily) saving their existing clipboard data.

I suggest that you use a clipboard manager in the meantime as a workaround. You can also lodge a feature request on our forums using the instructions below.

---

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
