### ISSUE TITLE
Searching Auto-Fill/View Item

### ISSUE THREAD

**Issue by chrisrowley14** [bitwarden/browser#860]
I have about 40 different logins for one website so i need to use the search feature. When i don't search i can click the login and it will auto-fill

If i search for the login I'm after i only get the option to view the login details and not to auto fill them.

Is this intentional? Can i turn it off?

**Comment by kspearrin** [comment]
This is expected at the moment. We're still working on figuring out a way to display view and autofill actions in the same context.

**Comment by junaid-sendoso** [comment]
@kspearrin How soon this feature will get implemented. I'm also facing the same problem its implementation will be very helpful.

**Comment by junaideqbal** [comment]
@kspearrin  How soon this feature will get implemented. I'm also facing the same problem its implementation will be very helpful.
A simplest can do is add an icon of autofill when user search.
<img width="509" alt="Image 2020-01-05 at 07 01 18" src="https://user-images.githubusercontent.com/16623553/71774084-2ae71100-2f8a-11ea-944d-5fe55e79d88c.png">

**Comment by eliykat** [comment]
We've since added an Auto-fill button on the View Item screen. You can now search for your item > click the item > click the Auto-fill button.

If you would rather a different flow/UX, you can discuss it in the [community forums thread about this topic](https://community.bitwarden.com/t/autofill-after-search/2808). We use the community forums to track and vote on feature requests, so I'll close this issue for now.
