### ISSUE TITLE
Strange results when dash used in search field

### ISSUE THREAD

**Issue by setyb** [bitwarden/browser#863]
Strange things happen when a dash is used in the search field.  This causes issues when searching for phone numbers.

For example, create an item that includes the string `12-345-67890` in the *Notes* section.

Now search for `"12-345-88"` (with the quotes).  The item you just created will match, even though it does not have that string.

As another example, search for `12-345-67890` (without any quotes).  Items with just the string `12` will be returned, even if they don't have the rest of the string.

**Comment by kspearrin** [comment]
I am guessing this probably has something to so with dash being a "term presence" key character in lunr.js (the lib we use for searching)

https://lunrjs.com/guides/searching.html#term-presence

**Comment by setyb** [comment]
That's a good guess.  I took a look at the page you linked (thanks!), but I'm not sure if it explains what happens in the first example.

**Comment by Blazeflack** [comment]
I was looking into possible solutions to an issue I was having, and came across this ticket.

In my case the issue was also caused by a dash, but in the custom field name when trying to utilize auto-fill.

**The URL you need for testing**: selvbetjening.medarbejderkoncepter.dk

The first label has no attributes and its value is more than just a string, so I initially used the following regex to find the first label named CVR-nummer: "regex=.*CVR-nummer.*"
The above field name would not allow the auto-fill to happen though.

I also tried escaping the dash, just in case it was treated as a special character for some reason: "regex=.*CVR\-nummer.*"
This did not work either.

Then I came across this ticket, and tried this: "regex=.*CVR.*"
This one worked.

If you just want the label HTML to test on then here it is:
```
<label>
            CVR-nummer<span class="g_flow_required">*</span><a id="ctl00_Content__ucOpenDatawebCredentialEditor__lbtnLookupAddress" class="pull-right" href='javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions("ctl00$Content$_ucOpenDatawebCredentialEditor$_lbtnLookupAddress", "", true, "", "", false, true))'>Find adresse</a></label>
```

**Comment by setyb** [comment]
@Blazeflack I think in your case it's because `regex=.CVR-nummer.` has to match a character after `nummer`.  Since there isn't a character, it doesn't match.  But with `regex=.CVR.`, there is a character (which just happens to be a dash) after `CVR`, therefore, it matches.
