### ISSUE TITLE
Yubikey 2FA not used on unlocking the extension vault in Opera

### ISSUE THREAD

**Issue by gumshoe2020** [bitwarden/browser#891]
After activating the Yubikey 2FA, I expected it to be utilized in unlocking the browser extension also.
It is not currently, from my testing in Opera.

**Comment by kspearrin** [comment]
2FA only occurs when logging in, not unlocking.

**Comment by pahakalle** [comment]
@kspearrin That could be a nice way to unlock the vault

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by gumshoe2020** [comment]
So, presuming I would want to add this, where would I start?  
I would have to execute the `init2fa` in the unlock operation?
Or presumably it might be easier to simply logout the user when the timer expires (after checking the appropriate option).

**Comment by actuallymentor** [comment]
Relevant feature request: [2FA when unlocking](https://community.bitwarden.com/t/2fa-when-unlocking/353).

There are a lot of ex-lastpass people who want to combine 'logout after X minutes' with 'unlock using 2FA instead of password'. If you are one of them, be sure to upvote that feature request.
