### ISSUE TITLE
There is no possibility to fill in the data from the search

### ISSUE THREAD

**Issue by proea** [bitwarden/browser#915]
Hi!
_Environment_ 
- Google Chrome + Extension. latest version (browser & extension)
- Firefox + Extension, Safari + Extension

_There is no possibility to fill in the data in the form of search results._

Sometimes I need to select an account from the search to fill in the login and password, but this is not possible to do this. (only by copying the username and password separately, however, the search results are lost immediately after the browser extension window is minimized.)

lastpassword extension is more convenient In terms of usability (for example, even a window offering to save a new password, or a window offering passwords right in the form)

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
