### ISSUE TITLE
Keyboard Shortcut for copying notes

### ISSUE THREAD

**Issue by holmesb** [bitwarden/browser#921]
As asked for in one of the most popular [Feature Requests](https://community.bitwarden.com/t/add-essential-keyboard-shortcuts-navigation/76/25), please add the same\similar keyboard shortcut as LastPass uses for copying Secure Notes.  

Currently, can Ctrl-Shift-Y, type the note, tab to the one I want, but then I’m stuck.  Have to switch to mouse to actually perform the copy. I used to do this all the time using LP, so it is a big loss of productivity. 

Quickly copying notes using keyboard shortcuts is a basic feature that should be top priority IMO.  They can't be auto-filled.

**Comment by kspearrin** [comment]
This is being tracked in the feature request that you referenced.

--------------

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by holmesb** [comment]
Is it really tracked though @kspearrin ?  Feature requests in a forum have no associated Github issue, so no link with the actual product development in terms of commits\PRs.  Hence there are no real progress updates in Feature Requests.  They can be open forever without any status changes and feedback to users.  

GitHub issues get version milestones and visibility on the product roadmap.  Feature requests in a forum do not.  

Github issues can go stale after inactivity.  Feature requests in a forum do not. Too many GitHub issues that go stale look bad reputationally for the project and encourage regular updates.  Too many Feature requests remain open for years?  Meh, who cares?  I expect this is an unfair exaggeration of the attitude in this project, but the jist of this point holds.

IMO, should be both.  As now, users should request features in the forum using their language (not always precise enough), then devs\admins create one or more associated GitHub issue with the necessary precision and post links to these in the forum Feature Request.  Other FOSS projects, eg RockStor work well with this setup.

**Comment by kspearrin** [comment]
> GitHub issues get version milestones and visibility on the product roadmap. Feature requests in a forum do not.

Currently, we do not use GitHub in this way. GitHub issues are mostly just used for managing bug reports.

We do monitor the feature requests forum votes for visibility into what users want most.

**Comment by holmesb** [comment]
> We do monitor the feature requests forum votes
Not really good enough for paying customers @kspearrin.  This could be interpretted as: "We promise to occasionally keep an eye on what you've asked for".  This attitude is how businesses\projects fail.  Meaningful feedback via GitHub issues is a necessary addition to the forum.  They serve different purposes and types of users, but both are needed.
