### ISSUE TITLE
Allow passwordless access (without PIN)

### ISSUE THREAD

**Issue by Bodup** [bitwarden/browser#935]
We should allow the user to store the password so that Bitwarden is always unlocked (even without a PIN). If it is assumed that the system is malicious/compromised then it might as well wait for the user to enter his/her credentials or extract it from memory. Typing the full password (or a pin for that matter) is security theater because it doesn't meaningfully mitigate a well defined threat scenario. Leaving Bitwarden unlocked on the other hand does make it significantly more convenient to use.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by Bodup** [comment]
This is a development related issue. I'm pointing out the fact that the PIN entry attempts mitigate a threat which it cannot meaningfully mitigate.

**Comment by Bodup** [comment]
You've literally closed the issue within a minute without even considering what I've written.

**Comment by kspearrin** [comment]
Passwords and PINs are usually meant to prevent access prior to the system being compromised. For example, your device is stolen. A password/PIN would prevent this thief from accessing your locked vault. A device that is actively compromised while a user is still using it cannot be protected against from our prospective.

**Comment by kspearrin** [comment]
> We should allow the user to store the password so that Bitwarden is always unlocked (even without a PIN)

You can already do this. Settings > Lock Options > Never.

**Comment by Bodup** [comment]
> > We should allow the user to store the password so that Bitwarden is always unlocked (even without a PIN)
> 
> You can already do this. Settings > Lock Options > Never.

Thank you, I hadn't noticed that was an option.
