### ISSUE TITLE
Add Support For Firefox's Mobile Browser

### ISSUE THREAD

**Issue by cwmke** [bitwarden/browser#95]
Currently the mobile browser can install the addon, but I have been unable to find a way to use it as there is no menu entry or way to login. Any chance of adding some mobile Firefox support in the future (essentially a switch from icon to menu entry)?

**Comment by kspearrin** [comment]
There was no intention of the addon working in Firefox at it's current state. I never tested that so I'll have to look into how Firefox addons work.

**Comment by Primokorn** [comment]
@kspearrin Did you have time to check this out?

**Comment by kspearrin** [comment]
I have not yet. How are extensions normally used in Firefox mobile?

**Comment by mhammond** [comment]
webextensions have (mostly?) landed there, but docs on testing/debugging seem fairly thin on the ground.

**Comment by kspearrin** [comment]
@mhammond Do browser action popups work with it? Seems kind of odd. I am having a hard time visioning how the popup would look/work on a tiny mobile device.

**Comment by mhammond** [comment]
No idea at all I'm afraid. I might end up trying to work out how to play with this, but it's unlikely to be soon...

**Comment by cwmke** [comment]
I would recommend looking at [ublock origin's](https://github.com/gorhill/) implementation. They pop open their window in a tab.

**Comment by zygous** [comment]
LastPass doesn't use a web extension, but their Firefox extension does support Firefox Mobile. It's invaluable because Android password manager apps don't seem to be able to autofill fields in Firefox. The extension opens a new tab for logging in, and is really basic, but does fill password fields. I use it in combination with the Android app.
I'd happily switch to Bitwarden (in fact was in the process of doing so) if it supported Firefox Mobile.

**Comment by rekrapg** [comment]
exactly the same as zygous - I prefer bitwarden, but lack of Firefox Mobile support means I cannot use it on my mobile browser of choice.  However, lastpass does work on Firefox Mobile, so i'm currently using lastpass instead of using bitwarden!

**Comment by zygous** [comment]
I'm hoping that the new Autofill API in Android Oreo will help with auto-filling Firefox from the Bitwarden app; not needing a Firefox Mobile add-on would be best.

I actually use Firefox Nightly (apparently I'm a glutton for punishment), and since version 57 LastPass's extension no longer works either; I've resorted to using Firefox's built-in password management, which is a big compromise.

**Comment by Primokorn** [comment]
@zygous I use Firefox Klar as a replacement of Firefox beta/nightly when I need bitwarden.
It uses Blink but it's a good compromise IMO.

**Comment by kspearrin** [comment]
Looks like the latest Firefox Nightly on Android works great with the bitwarden web extension. Closing this since it seems we have compatibility now.

**Comment by zygous** [comment]
Awesome! 👍

**Comment by Primokorn** [comment]
Nothing on my end despite an update this morning...

**Comment by rekrapg** [comment]
Yeah doesn't work for me either, I can only use bitwarden if I have it
persistent, then copy/paste credentials

On 6 Sep. 2017 16:57, "Primokorn" <notifications@github.com> wrote:

Nothing on my end despite an update this morning...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/bitwarden/browser/issues/95#issuecomment-327393157>,
or mute
the thread

**Comment by kspearrin** [comment]
@rekrapg This issue is not able the bitwarden mobile app. It's about the web extension addon.

**Comment by Primokorn** [comment]
@kspearrin I was talking about the mobile app since bitwarden is not available on AMO mobile here...

**Comment by kspearrin** [comment]
You have to navigate directly to https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/ and add it. It doesn't show up in search results on AMO android.

**Comment by rekrapg** [comment]
Yes, working, of sorts.  So i'd love it searchable, but not a big issue.
What I did find though, it's impossible to use a 2 factor auth app with the
firefox mobile version.  Only option was email for 2 factor.


Cheers,

Greg Parker
rekrapg@gmail.com

**Comment by kspearrin** [comment]
@rekrapg Searching should work just fine in it?

2FA will only show you options that work on the platform/device you are using. Which 2FA wasn't available?

**Comment by rekrapg** [comment]
If I used an app, like google authenticator or authy, I could get and enter
a code, but it just sat there spinning away after I clicked "continue".  As
such, bitwarden never logged in.  I switched my 2FA to email, and it worked
straight away.  So I feel that it's the time-based part of an app 2FA
that's failing in the mobile browser.


Cheers,

Greg Parker
rekrapg@gmail.com

**Comment by Primokorn** [comment]
The 2FA code is not copied in the clipboard but we can get it from the addon (press the pencil).

**Comment by rekrapg** [comment]
Yeah I manually typed the code into bitwarden, clicked continue, and it
just sat there spinning. I made sure that I did it soon as new numbers to
ensure time was ok. It just would keep spinning when clicking continue and
never get to logging me in. Only on 2FA with either Authy or Google
authenticator. Email = fine. It's a problem communicating back to verify
the entered time based passcode, only thing makes sense.
